// Auto-generated by codegen/generate-bindings.ts — DO NOT EDIT

import type { EmscriptenModule } from "../wasm/types.js";

export type Ptr = number;

export function version(M: EmscriptenModule): string {
  return M.ccall("ifcopenshell_ifcparse_version", "string", [], []);
}

export function guess_file_type(M: EmscriptenModule, path: string): number {
  return M.ccall("ifcopenshell_ifcparse_guess_file_type", "number", ["string"], [path]);
}

export function create_timestamp(M: EmscriptenModule): string {
  return M.ccall("ifcopenshell_ifcparse_create_timestamp", "string", [], []);
}

export function file_create_empty(M: EmscriptenModule, schema_name: string): number {
  return M.ccall("ifcopenshell_ifcparse_file_create_empty", "number", ["string"], [schema_name]);
}

export function file_open_from_memory(M: EmscriptenModule, data: string, length: number): number {
  return M.ccall("ifcopenshell_ifcparse_file_open_from_memory", "number", ["string", "number"], [data, length]);
}

export function file_open(M: EmscriptenModule, path: string, filetype: number, readonly: number): number {
  return M.ccall("ifcopenshell_ifcparse_file_open", "number", ["string", "number", "number"], [path, filetype, readonly]);
}

export function file_close(M: EmscriptenModule, file: number): void {
  return M.ccall("ifcopenshell_ifcparse_file_close", null, ["number"], [file]);
}

export function file_status(M: EmscriptenModule, file: number): number {
  return M.ccall("ifcopenshell_ifcparse_file_status", "number", ["number"], [file]);
}

export function file_status_message(M: EmscriptenModule, status: number): string {
  return M.ccall("ifcopenshell_ifcparse_file_status_message", "string", ["number"], [status]);
}

export function file_schema_name(M: EmscriptenModule, file: number): string {
  return M.ccall("ifcopenshell_ifcparse_file_schema_name", "string", ["number"], [file]);
}

export function file_header_file_description(M: EmscriptenModule, file: number): number {
  return M.ccall("ifcopenshell_ifcparse_file_header_file_description", "number", ["number"], [file]);
}

export function file_header_file_name(M: EmscriptenModule, file: number): number {
  return M.ccall("ifcopenshell_ifcparse_file_header_file_name", "number", ["number"], [file]);
}

export function file_header_file_schema(M: EmscriptenModule, file: number): number {
  return M.ccall("ifcopenshell_ifcparse_file_header_file_schema", "number", ["number"], [file]);
}

export function file_entity_count(M: EmscriptenModule, file: number): number {
  return M.ccall("ifcopenshell_ifcparse_file_entity_count", "number", ["number"], [file]);
}

export function file_entities(M: EmscriptenModule, file: number): number {
  return M.ccall("ifcopenshell_ifcparse_file_entities", "number", ["number"], [file]);
}

export function file_entity_ids(M: EmscriptenModule, file: number): number {
  return M.ccall("ifcopenshell_ifcparse_file_entity_ids", "number", ["number"], [file]);
}

export function file_instance_by_id(M: EmscriptenModule, file: number, id: number): number {
  return M.ccall("ifcopenshell_ifcparse_file_instance_by_id", "number", ["number", "number"], [file, id]);
}

export function file_instance_by_guid(M: EmscriptenModule, file: number, guid: string): number {
  return M.ccall("ifcopenshell_ifcparse_file_instance_by_guid", "number", ["number", "string"], [file, guid]);
}

export function file_instances_by_type(M: EmscriptenModule, file: number, type_name: string, include_subtypes: number): number {
  return M.ccall("ifcopenshell_ifcparse_file_instances_by_type", "number", ["number", "string", "number"], [file, type_name, include_subtypes]);
}

export function file_instances_by_reference(M: EmscriptenModule, file: number, id: number): number {
  return M.ccall("ifcopenshell_ifcparse_file_instances_by_reference", "number", ["number", "number"], [file, id]);
}

export function file_get_inverse(M: EmscriptenModule, file: number, instance_id: number, type_name: string, attribute_index: number): number {
  return M.ccall("ifcopenshell_ifcparse_file_get_inverse", "number", ["number", "number", "string", "number"], [file, instance_id, type_name, attribute_index]);
}

export function file_get_total_inverses(M: EmscriptenModule, file: number, instance_id: number): number {
  return M.ccall("ifcopenshell_ifcparse_file_get_total_inverses", "number", ["number", "number"], [file, instance_id]);
}

export function file_get_inverse_indices(M: EmscriptenModule, file: number, instance_id: number): number {
  return M.ccall("ifcopenshell_ifcparse_file_get_inverse_indices", "number", ["number", "number"], [file, instance_id]);
}

export function file_traverse_by_id(M: EmscriptenModule, file: number, instance_id: number, max_level: number, breadth_first: number): number {
  return M.ccall("ifcopenshell_ifcparse_file_traverse_by_id", "number", ["number", "number", "number", "number"], [file, instance_id, max_level, breadth_first]);
}

export function file_traverse(M: EmscriptenModule, file: number, entity: number, max_level: number, breadth_first: number): number {
  return M.ccall("ifcopenshell_ifcparse_file_traverse", "number", ["number", "number", "number", "number"], [file, entity, max_level, breadth_first]);
}

export function file_create_entity_by_type(M: EmscriptenModule, file: number, type_name: string): number {
  return M.ccall("ifcopenshell_ifcparse_file_create_entity_by_type", "number", ["number", "string"], [file, type_name]);
}

export function file_create_entity_by_type_with_id(M: EmscriptenModule, file: number, type_name: string, id: number): number {
  return M.ccall("ifcopenshell_ifcparse_file_create_entity_by_type_with_id", "number", ["number", "string", "number"], [file, type_name, id]);
}

export function file_add_entity(M: EmscriptenModule, file: number, entity: number, id: number): number {
  return M.ccall("ifcopenshell_ifcparse_file_add_entity", "number", ["number", "number", "number"], [file, entity, id]);
}

export function file_add_entities(M: EmscriptenModule, file: number, entities: number, entity_count: number): number {
  return M.ccall("ifcopenshell_ifcparse_file_add_entities", "number", ["number", "number", "number"], [file, entities, entity_count]);
}

export function file_remove_entity_by_id(M: EmscriptenModule, file: number, id: number): number {
  return M.ccall("ifcopenshell_ifcparse_file_remove_entity_by_id", "number", ["number", "number"], [file, id]);
}

export function file_remove_entity(M: EmscriptenModule, file: number, entity: number): number {
  return M.ccall("ifcopenshell_ifcparse_file_remove_entity", "number", ["number", "number"], [file, entity]);
}

export function file_batch_begin(M: EmscriptenModule, file: number): void {
  return M.ccall("ifcopenshell_ifcparse_file_batch_begin", null, ["number"], [file]);
}

export function file_batch_end(M: EmscriptenModule, file: number): void {
  return M.ccall("ifcopenshell_ifcparse_file_batch_end", null, ["number"], [file]);
}

export function file_max_id(M: EmscriptenModule, file: number): number {
  return M.ccall("ifcopenshell_ifcparse_file_max_id", "number", ["number"], [file]);
}

export function file_recalculate_id_counter(M: EmscriptenModule, file: number): void {
  return M.ccall("ifcopenshell_ifcparse_file_recalculate_id_counter", null, ["number"], [file]);
}

export function file_write_spf(M: EmscriptenModule, file: number, path: string): number {
  return M.ccall("ifcopenshell_ifcparse_file_write_spf", "number", ["number", "string"], [file, path]);
}

export function file_to_spf(M: EmscriptenModule, file: number): string {
  return M.ccall("ifcopenshell_ifcparse_file_to_spf", "string", ["number"], [file]);
}

export function file_unit_scale(M: EmscriptenModule, file: number, unit_type: string): number {
  return M.ccall("ifcopenshell_ifcparse_file_unit_scale", "number", ["number", "string"], [file, unit_type]);
}

export function file_unit_entity(M: EmscriptenModule, file: number, unit_type: string): number {
  return M.ccall("ifcopenshell_ifcparse_file_unit_entity", "number", ["number", "string"], [file, unit_type]);
}

export function entity_list_close(M: EmscriptenModule, list: number): void {
  return M.ccall("ifcopenshell_ifcparse_entity_list_close", null, ["number"], [list]);
}

export function entity_list_count(M: EmscriptenModule, list: number): number {
  return M.ccall("ifcopenshell_ifcparse_entity_list_count", "number", ["number"], [list]);
}

export function entity_list_reset(M: EmscriptenModule, list: number): void {
  return M.ccall("ifcopenshell_ifcparse_entity_list_reset", null, ["number"], [list]);
}

export function entity_list_get(M: EmscriptenModule, list: number, index: number): number {
  return M.ccall("ifcopenshell_ifcparse_entity_list_get", "number", ["number", "number"], [list, index]);
}

export function entity_list_next(M: EmscriptenModule, list: number): number {
  return M.ccall("ifcopenshell_ifcparse_entity_list_next", "number", ["number"], [list]);
}

export function entity_id(M: EmscriptenModule, entity: number): number {
  return M.ccall("ifcopenshell_ifcparse_entity_id", "number", ["number"], [entity]);
}

export function entity_type_name(M: EmscriptenModule, entity: number): string {
  return M.ccall("ifcopenshell_ifcparse_entity_type_name", "string", ["number"], [entity]);
}

export function entity_type_name_with_schema(M: EmscriptenModule, entity: number): string {
  return M.ccall("ifcopenshell_ifcparse_entity_type_name_with_schema", "string", ["number"], [entity]);
}

export function entity_is_a(M: EmscriptenModule, entity: number, type_name: string): number {
  return M.ccall("ifcopenshell_ifcparse_entity_is_a", "number", ["number", "string"], [entity, type_name]);
}

export function entity_attribute_category(M: EmscriptenModule, entity: number, attribute_name: string): number {
  return M.ccall("ifcopenshell_ifcparse_entity_attribute_category", "number", ["number", "string"], [entity, attribute_name]);
}

export function entity_attribute_names(M: EmscriptenModule, entity: number): number {
  return M.ccall("ifcopenshell_ifcparse_entity_attribute_names", "number", ["number"], [entity]);
}

export function entity_inverse_attribute_names(M: EmscriptenModule, entity: number): number {
  return M.ccall("ifcopenshell_ifcparse_entity_inverse_attribute_names", "number", ["number"], [entity]);
}

export function entity_argument_count(M: EmscriptenModule, entity: number): number {
  return M.ccall("ifcopenshell_ifcparse_entity_argument_count", "number", ["number"], [entity]);
}

export function entity_argument_index(M: EmscriptenModule, entity: number, argument_name: string): number {
  return M.ccall("ifcopenshell_ifcparse_entity_argument_index", "number", ["number", "string"], [entity, argument_name]);
}

export function entity_argument_name(M: EmscriptenModule, entity: number, index: number): string {
  return M.ccall("ifcopenshell_ifcparse_entity_argument_name", "string", ["number", "number"], [entity, index]);
}

export function entity_argument_declared_type(M: EmscriptenModule, entity: number, index: number): number {
  return M.ccall("ifcopenshell_ifcparse_entity_argument_declared_type", "number", ["number", "number"], [entity, index]);
}

export function entity_argument_value_type(M: EmscriptenModule, entity: number, index: number): number {
  return M.ccall("ifcopenshell_ifcparse_entity_argument_value_type", "number", ["number", "number"], [entity, index]);
}

export function entity_argument_is_null(M: EmscriptenModule, entity: number, index: number): number {
  return M.ccall("ifcopenshell_ifcparse_entity_argument_is_null", "number", ["number", "number"], [entity, index]);
}

export function entity_to_string(M: EmscriptenModule, entity: number, valid_spf: number): string {
  return M.ccall("ifcopenshell_ifcparse_entity_to_string", "string", ["number", "number"], [entity, valid_spf]);
}

export function entity_get_argument_as_int(M: EmscriptenModule, entity: number, index: number, out_value: number): number {
  return M.ccall("ifcopenshell_ifcparse_entity_get_argument_as_int", "number", ["number", "number", "number"], [entity, index, out_value]);
}

export function entity_get_argument_as_bool(M: EmscriptenModule, entity: number, index: number, out_value: number): number {
  return M.ccall("ifcopenshell_ifcparse_entity_get_argument_as_bool", "number", ["number", "number", "number"], [entity, index, out_value]);
}

export function entity_get_argument_as_logical(M: EmscriptenModule, entity: number, index: number, out_value: number): number {
  return M.ccall("ifcopenshell_ifcparse_entity_get_argument_as_logical", "number", ["number", "number", "number"], [entity, index, out_value]);
}

export function entity_get_argument_as_double(M: EmscriptenModule, entity: number, index: number, out_value: number): number {
  return M.ccall("ifcopenshell_ifcparse_entity_get_argument_as_double", "number", ["number", "number", "number"], [entity, index, out_value]);
}

export function entity_get_argument_as_string(M: EmscriptenModule, entity: number, index: number): string {
  return M.ccall("ifcopenshell_ifcparse_entity_get_argument_as_string", "string", ["number", "number"], [entity, index]);
}

export function entity_get_argument_as_entity(M: EmscriptenModule, entity: number, index: number): number {
  return M.ccall("ifcopenshell_ifcparse_entity_get_argument_as_entity", "number", ["number", "number"], [entity, index]);
}

export function entity_get_argument_as_int_list(M: EmscriptenModule, entity: number, index: number): number {
  return M.ccall("ifcopenshell_ifcparse_entity_get_argument_as_int_list", "number", ["number", "number"], [entity, index]);
}

export function entity_get_argument_as_double_list(M: EmscriptenModule, entity: number, index: number): number {
  return M.ccall("ifcopenshell_ifcparse_entity_get_argument_as_double_list", "number", ["number", "number"], [entity, index]);
}

export function entity_get_argument_as_string_list(M: EmscriptenModule, entity: number, index: number): number {
  return M.ccall("ifcopenshell_ifcparse_entity_get_argument_as_string_list", "number", ["number", "number"], [entity, index]);
}

export function entity_get_argument_as_entity_list(M: EmscriptenModule, entity: number, index: number): number {
  return M.ccall("ifcopenshell_ifcparse_entity_get_argument_as_entity_list", "number", ["number", "number"], [entity, index]);
}

export function entity_get_inverse(M: EmscriptenModule, entity: number, inverse_name: string): number {
  return M.ccall("ifcopenshell_ifcparse_entity_get_inverse", "number", ["number", "string"], [entity, inverse_name]);
}

export function entity_get_argument_as_int_matrix(M: EmscriptenModule, entity: number, index: number): number {
  return M.ccall("ifcopenshell_ifcparse_entity_get_argument_as_int_matrix", "number", ["number", "number"], [entity, index]);
}

export function entity_get_argument_as_double_matrix(M: EmscriptenModule, entity: number, index: number): number {
  return M.ccall("ifcopenshell_ifcparse_entity_get_argument_as_double_matrix", "number", ["number", "number"], [entity, index]);
}

export function entity_get_argument_as_entity_matrix(M: EmscriptenModule, entity: number, index: number): number {
  return M.ccall("ifcopenshell_ifcparse_entity_get_argument_as_entity_matrix", "number", ["number", "number"], [entity, index]);
}

export function entity_set_argument_null(M: EmscriptenModule, entity: number, index: number): number {
  return M.ccall("ifcopenshell_ifcparse_entity_set_argument_null", "number", ["number", "number"], [entity, index]);
}

export function entity_unset_argument(M: EmscriptenModule, entity: number, index: number): number {
  return M.ccall("ifcopenshell_ifcparse_entity_unset_argument", "number", ["number", "number"], [entity, index]);
}

export function entity_set_argument_int(M: EmscriptenModule, entity: number, index: number, value: number): number {
  return M.ccall("ifcopenshell_ifcparse_entity_set_argument_int", "number", ["number", "number", "number"], [entity, index, value]);
}

export function entity_set_argument_bool(M: EmscriptenModule, entity: number, index: number, value: number): number {
  return M.ccall("ifcopenshell_ifcparse_entity_set_argument_bool", "number", ["number", "number", "number"], [entity, index, value]);
}

export function entity_set_argument_logical(M: EmscriptenModule, entity: number, index: number, value: number): number {
  return M.ccall("ifcopenshell_ifcparse_entity_set_argument_logical", "number", ["number", "number", "number"], [entity, index, value]);
}

export function entity_set_argument_double(M: EmscriptenModule, entity: number, index: number, value: number): number {
  return M.ccall("ifcopenshell_ifcparse_entity_set_argument_double", "number", ["number", "number", "number"], [entity, index, value]);
}

export function entity_set_argument_string(M: EmscriptenModule, entity: number, index: number, value: string): number {
  return M.ccall("ifcopenshell_ifcparse_entity_set_argument_string", "number", ["number", "number", "string"], [entity, index, value]);
}

export function entity_set_argument_entity(M: EmscriptenModule, entity: number, index: number, value: number): number {
  return M.ccall("ifcopenshell_ifcparse_entity_set_argument_entity", "number", ["number", "number", "number"], [entity, index, value]);
}

export function entity_set_argument_int_list(M: EmscriptenModule, entity: number, index: number, values: number, value_count: number): number {
  return M.ccall("ifcopenshell_ifcparse_entity_set_argument_int_list", "number", ["number", "number", "number", "number"], [entity, index, values, value_count]);
}

export function entity_set_argument_double_list(M: EmscriptenModule, entity: number, index: number, values: number, value_count: number): number {
  return M.ccall("ifcopenshell_ifcparse_entity_set_argument_double_list", "number", ["number", "number", "number", "number"], [entity, index, values, value_count]);
}

export function entity_set_argument_string_list(M: EmscriptenModule, entity: number, index: number, values: number, value_count: number): number {
  return M.ccall("ifcopenshell_ifcparse_entity_set_argument_string_list", "number", ["number", "number", "number", "number"], [entity, index, values, value_count]);
}

export function entity_set_argument_entity_list(M: EmscriptenModule, entity: number, index: number, values: number, value_count: number): number {
  return M.ccall("ifcopenshell_ifcparse_entity_set_argument_entity_list", "number", ["number", "number", "number", "number"], [entity, index, values, value_count]);
}

export function entity_set_argument_int_matrix(M: EmscriptenModule, entity: number, index: number, values: number, value_count: number, row_offsets: number, row_count: number): number {
  return M.ccall("ifcopenshell_ifcparse_entity_set_argument_int_matrix", "number", ["number", "number", "number", "number", "number", "number"], [entity, index, values, value_count, row_offsets, row_count]);
}

export function entity_set_argument_double_matrix(M: EmscriptenModule, entity: number, index: number, values: number, value_count: number, row_offsets: number, row_count: number): number {
  return M.ccall("ifcopenshell_ifcparse_entity_set_argument_double_matrix", "number", ["number", "number", "number", "number", "number", "number"], [entity, index, values, value_count, row_offsets, row_count]);
}

export function entity_set_argument_entity_matrix(M: EmscriptenModule, entity: number, index: number, values: number, value_count: number, row_offsets: number, row_count: number): number {
  return M.ccall("ifcopenshell_ifcparse_entity_set_argument_entity_matrix", "number", ["number", "number", "number", "number", "number", "number"], [entity, index, values, value_count, row_offsets, row_count]);
}

export function int_list_close(M: EmscriptenModule, list: number): void {
  return M.ccall("ifcopenshell_ifcparse_int_list_close", null, ["number"], [list]);
}

export function int_list_count(M: EmscriptenModule, list: number): number {
  return M.ccall("ifcopenshell_ifcparse_int_list_count", "number", ["number"], [list]);
}

export function int_list_reset(M: EmscriptenModule, list: number): void {
  return M.ccall("ifcopenshell_ifcparse_int_list_reset", null, ["number"], [list]);
}

export function int_list_get(M: EmscriptenModule, list: number, index: number): number {
  return M.ccall("ifcopenshell_ifcparse_int_list_get", "number", ["number", "number"], [list, index]);
}

export function int_list_next(M: EmscriptenModule, list: number): number {
  return M.ccall("ifcopenshell_ifcparse_int_list_next", "number", ["number"], [list]);
}

export function double_list_close(M: EmscriptenModule, list: number): void {
  return M.ccall("ifcopenshell_ifcparse_double_list_close", null, ["number"], [list]);
}

export function double_list_count(M: EmscriptenModule, list: number): number {
  return M.ccall("ifcopenshell_ifcparse_double_list_count", "number", ["number"], [list]);
}

export function double_list_reset(M: EmscriptenModule, list: number): void {
  return M.ccall("ifcopenshell_ifcparse_double_list_reset", null, ["number"], [list]);
}

export function double_list_get(M: EmscriptenModule, list: number, index: number): number {
  return M.ccall("ifcopenshell_ifcparse_double_list_get", "number", ["number", "number"], [list, index]);
}

export function double_list_next(M: EmscriptenModule, list: number): number {
  return M.ccall("ifcopenshell_ifcparse_double_list_next", "number", ["number"], [list]);
}

export function int_matrix_close(M: EmscriptenModule, matrix: number): void {
  return M.ccall("ifcopenshell_ifcparse_int_matrix_close", null, ["number"], [matrix]);
}

export function int_matrix_row_count(M: EmscriptenModule, matrix: number): number {
  return M.ccall("ifcopenshell_ifcparse_int_matrix_row_count", "number", ["number"], [matrix]);
}

export function int_matrix_col_count(M: EmscriptenModule, matrix: number, row: number): number {
  return M.ccall("ifcopenshell_ifcparse_int_matrix_col_count", "number", ["number", "number"], [matrix, row]);
}

export function int_matrix_get(M: EmscriptenModule, matrix: number, row: number, col: number): number {
  return M.ccall("ifcopenshell_ifcparse_int_matrix_get", "number", ["number", "number", "number"], [matrix, row, col]);
}

export function double_matrix_close(M: EmscriptenModule, matrix: number): void {
  return M.ccall("ifcopenshell_ifcparse_double_matrix_close", null, ["number"], [matrix]);
}

export function double_matrix_row_count(M: EmscriptenModule, matrix: number): number {
  return M.ccall("ifcopenshell_ifcparse_double_matrix_row_count", "number", ["number"], [matrix]);
}

export function double_matrix_col_count(M: EmscriptenModule, matrix: number, row: number): number {
  return M.ccall("ifcopenshell_ifcparse_double_matrix_col_count", "number", ["number", "number"], [matrix, row]);
}

export function double_matrix_get(M: EmscriptenModule, matrix: number, row: number, col: number): number {
  return M.ccall("ifcopenshell_ifcparse_double_matrix_get", "number", ["number", "number", "number"], [matrix, row, col]);
}

export function entity_matrix_close(M: EmscriptenModule, matrix: number): void {
  return M.ccall("ifcopenshell_ifcparse_entity_matrix_close", null, ["number"], [matrix]);
}

export function entity_matrix_row_count(M: EmscriptenModule, matrix: number): number {
  return M.ccall("ifcopenshell_ifcparse_entity_matrix_row_count", "number", ["number"], [matrix]);
}

export function entity_matrix_col_count(M: EmscriptenModule, matrix: number, row: number): number {
  return M.ccall("ifcopenshell_ifcparse_entity_matrix_col_count", "number", ["number", "number"], [matrix, row]);
}

export function entity_matrix_get(M: EmscriptenModule, matrix: number, row: number, col: number): number {
  return M.ccall("ifcopenshell_ifcparse_entity_matrix_get", "number", ["number", "number", "number"], [matrix, row, col]);
}

export function file_types(M: EmscriptenModule, file: number): number {
  return M.ccall("ifcopenshell_ifcparse_file_types", "number", ["number"], [file]);
}

export function type_list_close(M: EmscriptenModule, list: number): void {
  return M.ccall("ifcopenshell_ifcparse_type_list_close", null, ["number"], [list]);
}

export function type_list_count(M: EmscriptenModule, list: number): number {
  return M.ccall("ifcopenshell_ifcparse_type_list_count", "number", ["number"], [list]);
}

export function type_list_reset(M: EmscriptenModule, list: number): void {
  return M.ccall("ifcopenshell_ifcparse_type_list_reset", null, ["number"], [list]);
}

export function type_list_get(M: EmscriptenModule, list: number, index: number): number {
  return M.ccall("ifcopenshell_ifcparse_type_list_get", "number", ["number", "number"], [list, index]);
}

export function type_list_next(M: EmscriptenModule, list: number): number {
  return M.ccall("ifcopenshell_ifcparse_type_list_next", "number", ["number"], [list]);
}

export function type_name(M: EmscriptenModule, type_ref: number): string {
  return M.ccall("ifcopenshell_ifcparse_type_name", "string", ["number"], [type_ref]);
}

export function type_index(M: EmscriptenModule, type_ref: number): number {
  return M.ccall("ifcopenshell_ifcparse_type_index", "number", ["number"], [type_ref]);
}

export function schema_declaration_by_name(M: EmscriptenModule, schema_name: string, declaration_name: string): number {
  return M.ccall("ifcopenshell_ifcparse_schema_declaration_by_name", "number", ["string", "string"], [schema_name, declaration_name]);
}

export function schema_entities(M: EmscriptenModule, schema_name: string): number {
  return M.ccall("ifcopenshell_ifcparse_schema_entities", "number", ["string"], [schema_name]);
}

export function type_schema_name(M: EmscriptenModule, type_ref: number): string {
  return M.ccall("ifcopenshell_ifcparse_type_schema_name", "string", ["number"], [type_ref]);
}

export function type_is_a(M: EmscriptenModule, type_ref: number, type_name: string): number {
  return M.ccall("ifcopenshell_ifcparse_type_is_a", "number", ["number", "string"], [type_ref, type_name]);
}

export function type_kind(M: EmscriptenModule, type_ref: number): number {
  return M.ccall("ifcopenshell_ifcparse_type_kind", "number", ["number"], [type_ref]);
}

export function type_is_abstract(M: EmscriptenModule, type_ref: number): number {
  return M.ccall("ifcopenshell_ifcparse_type_is_abstract", "number", ["number"], [type_ref]);
}

export function type_supertype(M: EmscriptenModule, type_ref: number): number {
  return M.ccall("ifcopenshell_ifcparse_type_supertype", "number", ["number"], [type_ref]);
}

export function type_subtypes(M: EmscriptenModule, type_ref: number): number {
  return M.ccall("ifcopenshell_ifcparse_type_subtypes", "number", ["number"], [type_ref]);
}

export function type_declared_type(M: EmscriptenModule, type_ref: number): number {
  return M.ccall("ifcopenshell_ifcparse_type_declared_type", "number", ["number"], [type_ref]);
}

export function type_select_list(M: EmscriptenModule, type_ref: number): number {
  return M.ccall("ifcopenshell_ifcparse_type_select_list", "number", ["number"], [type_ref]);
}

export function type_enumeration_items(M: EmscriptenModule, type_ref: number): number {
  return M.ccall("ifcopenshell_ifcparse_type_enumeration_items", "number", ["number"], [type_ref]);
}

export function type_attribute_index(M: EmscriptenModule, type_ref: number, attribute_name: string): number {
  return M.ccall("ifcopenshell_ifcparse_type_attribute_index", "number", ["number", "string"], [type_ref, attribute_name]);
}

export function type_attributes(M: EmscriptenModule, type_ref: number, include_inherited: number): number {
  return M.ccall("ifcopenshell_ifcparse_type_attributes", "number", ["number", "number"], [type_ref, include_inherited]);
}

export function type_inverse_attributes(M: EmscriptenModule, type_ref: number, include_inherited: number): number {
  return M.ccall("ifcopenshell_ifcparse_type_inverse_attributes", "number", ["number", "number"], [type_ref, include_inherited]);
}

export function attribute_list_close(M: EmscriptenModule, list: number): void {
  return M.ccall("ifcopenshell_ifcparse_attribute_list_close", null, ["number"], [list]);
}

export function attribute_list_count(M: EmscriptenModule, list: number): number {
  return M.ccall("ifcopenshell_ifcparse_attribute_list_count", "number", ["number"], [list]);
}

export function attribute_list_reset(M: EmscriptenModule, list: number): void {
  return M.ccall("ifcopenshell_ifcparse_attribute_list_reset", null, ["number"], [list]);
}

export function attribute_list_get(M: EmscriptenModule, list: number, index: number): number {
  return M.ccall("ifcopenshell_ifcparse_attribute_list_get", "number", ["number", "number"], [list, index]);
}

export function attribute_list_next(M: EmscriptenModule, list: number): number {
  return M.ccall("ifcopenshell_ifcparse_attribute_list_next", "number", ["number"], [list]);
}

export function attribute_name(M: EmscriptenModule, attribute_ref: number): string {
  return M.ccall("ifcopenshell_ifcparse_attribute_name", "string", ["number"], [attribute_ref]);
}

export function attribute_optional(M: EmscriptenModule, attribute_ref: number): number {
  return M.ccall("ifcopenshell_ifcparse_attribute_optional", "number", ["number"], [attribute_ref]);
}

export function attribute_parameter_type(M: EmscriptenModule, attribute_ref: number): number {
  return M.ccall("ifcopenshell_ifcparse_attribute_parameter_type", "number", ["number"], [attribute_ref]);
}

export function inverse_attribute_list_close(M: EmscriptenModule, list: number): void {
  return M.ccall("ifcopenshell_ifcparse_inverse_attribute_list_close", null, ["number"], [list]);
}

export function inverse_attribute_list_count(M: EmscriptenModule, list: number): number {
  return M.ccall("ifcopenshell_ifcparse_inverse_attribute_list_count", "number", ["number"], [list]);
}

export function inverse_attribute_list_reset(M: EmscriptenModule, list: number): void {
  return M.ccall("ifcopenshell_ifcparse_inverse_attribute_list_reset", null, ["number"], [list]);
}

export function inverse_attribute_list_get(M: EmscriptenModule, list: number, index: number): number {
  return M.ccall("ifcopenshell_ifcparse_inverse_attribute_list_get", "number", ["number", "number"], [list, index]);
}

export function inverse_attribute_list_next(M: EmscriptenModule, list: number): number {
  return M.ccall("ifcopenshell_ifcparse_inverse_attribute_list_next", "number", ["number"], [list]);
}

export function inverse_attribute_name(M: EmscriptenModule, inverse_attribute_ref: number): string {
  return M.ccall("ifcopenshell_ifcparse_inverse_attribute_name", "string", ["number"], [inverse_attribute_ref]);
}

export function inverse_attribute_aggregation_type(M: EmscriptenModule, inverse_attribute_ref: number): number {
  return M.ccall("ifcopenshell_ifcparse_inverse_attribute_aggregation_type", "number", ["number"], [inverse_attribute_ref]);
}

export function inverse_attribute_bound1(M: EmscriptenModule, inverse_attribute_ref: number): number {
  return M.ccall("ifcopenshell_ifcparse_inverse_attribute_bound1", "number", ["number"], [inverse_attribute_ref]);
}

export function inverse_attribute_bound2(M: EmscriptenModule, inverse_attribute_ref: number): number {
  return M.ccall("ifcopenshell_ifcparse_inverse_attribute_bound2", "number", ["number"], [inverse_attribute_ref]);
}

export function inverse_attribute_entity_reference(M: EmscriptenModule, inverse_attribute_ref: number): number {
  return M.ccall("ifcopenshell_ifcparse_inverse_attribute_entity_reference", "number", ["number"], [inverse_attribute_ref]);
}

export function inverse_attribute_attribute_reference(M: EmscriptenModule, inverse_attribute_ref: number): number {
  return M.ccall("ifcopenshell_ifcparse_inverse_attribute_attribute_reference", "number", ["number"], [inverse_attribute_ref]);
}

export function parameter_type_kind(M: EmscriptenModule, parameter_type_ref: number): number {
  return M.ccall("ifcopenshell_ifcparse_parameter_type_kind", "number", ["number"], [parameter_type_ref]);
}

export function parameter_type_named_declared_type(M: EmscriptenModule, parameter_type_ref: number): number {
  return M.ccall("ifcopenshell_ifcparse_parameter_type_named_declared_type", "number", ["number"], [parameter_type_ref]);
}

export function parameter_type_simple_declared_type(M: EmscriptenModule, parameter_type_ref: number): number {
  return M.ccall("ifcopenshell_ifcparse_parameter_type_simple_declared_type", "number", ["number"], [parameter_type_ref]);
}

export function parameter_type_aggregation_type(M: EmscriptenModule, parameter_type_ref: number): number {
  return M.ccall("ifcopenshell_ifcparse_parameter_type_aggregation_type", "number", ["number"], [parameter_type_ref]);
}

export function parameter_type_aggregation_bound1(M: EmscriptenModule, parameter_type_ref: number): number {
  return M.ccall("ifcopenshell_ifcparse_parameter_type_aggregation_bound1", "number", ["number"], [parameter_type_ref]);
}

export function parameter_type_aggregation_bound2(M: EmscriptenModule, parameter_type_ref: number): number {
  return M.ccall("ifcopenshell_ifcparse_parameter_type_aggregation_bound2", "number", ["number"], [parameter_type_ref]);
}

export function parameter_type_aggregation_element_type(M: EmscriptenModule, parameter_type_ref: number): number {
  return M.ccall("ifcopenshell_ifcparse_parameter_type_aggregation_element_type", "number", ["number"], [parameter_type_ref]);
}

export function schema_names(M: EmscriptenModule): number {
  return M.ccall("ifcopenshell_ifcparse_schema_names", "number", [], []);
}

export function string_list_close(M: EmscriptenModule, list: number): void {
  return M.ccall("ifcopenshell_ifcparse_string_list_close", null, ["number"], [list]);
}

export function string_list_count(M: EmscriptenModule, list: number): number {
  return M.ccall("ifcopenshell_ifcparse_string_list_count", "number", ["number"], [list]);
}

export function string_list_reset(M: EmscriptenModule, list: number): void {
  return M.ccall("ifcopenshell_ifcparse_string_list_reset", null, ["number"], [list]);
}

export function string_list_get(M: EmscriptenModule, list: number, index: number): string {
  return M.ccall("ifcopenshell_ifcparse_string_list_get", "string", ["number", "number"], [list, index]);
}

export function string_list_next(M: EmscriptenModule, list: number): string {
  return M.ccall("ifcopenshell_ifcparse_string_list_next", "string", ["number"], [list]);
}

export function file_native(M: EmscriptenModule, file: number): number {
  return M.ccall("ifcopenshell_ifcparse_file_native", "number", ["number"], [file]);
}

export function file_native_const(M: EmscriptenModule, file: number): number {
  return M.ccall("ifcopenshell_ifcparse_file_native_const", "number", ["number"], [file]);
}

export function entity_native(M: EmscriptenModule, entity: number): number {
  return M.ccall("ifcopenshell_ifcparse_entity_native", "number", ["number"], [entity]);
}

export function file_last_error(M: EmscriptenModule, file: number): string {
  return M.ccall("ifcopenshell_ifcparse_file_last_error", "string", ["number"], [file]);
}

export function last_error(M: EmscriptenModule): string {
  return M.ccall("ifcopenshell_ifcparse_last_error", "string", [], []);
}
