# This file was generated with the assistance of an AI coding tool.

from __future__ import annotations

from pathlib import Path
from textwrap import dedent

from src.ifcwrap.binding_generator.binding_inventory import build_inventory, parse_c_functions, parse_ctypes_symbols


def test_parse_c_functions_handles_exported_multiline_declarations(tmp_path: Path) -> None:
    header = tmp_path / "api.h"
    header.write_text(
        dedent(
            """
            #define IFCAPI_EXPORT
            IFCAPI_EXPORT struct ifcopenshell_ifc_instance_t*
            ifcopenshell_file_create_entity(
                ifcopenshell_ifc_file_t* file,
                const char* type_name);

            bool ifcopenshell_ifc_file_by_type(
                ifcopenshell_ifc_file_t* self,
                const char* type,
                ifcopenshell_ifcparse_instance_list_t** out_result);
            """
        ),
        encoding="utf-8",
    )

    functions = {function.name: function for function in parse_c_functions(header, tmp_path)}

    assert set(functions) == {"ifcopenshell_file_create_entity", "ifcopenshell_ifc_file_by_type"}
    assert functions["ifcopenshell_file_create_entity"].return_type == "struct ifcopenshell_ifc_instance_t*"
    assert "const char* type_name" in functions["ifcopenshell_file_create_entity"].params


def test_parse_ctypes_symbols_finds_signature_dicts_and_direct_assignments(tmp_path: Path) -> None:
    source = tmp_path / "wrapper.py"
    source.write_text(
        dedent(
            """
            def _bind(lib):
                sigs = {
                    "ifcopenshell_ifc_file_by_type": (c_bool, []),
                    "ifcopenshell_string_destroy": (None, []),
                }
                lib.ifcopenshell_file_create_entity.restype = c_void_p
                lib.ifcopenshell_file_create_entity.argtypes = [c_void_p]
                getattr(lib, "ifcopenshell_last_error_message").restype = c_char_p
            """
        ),
        encoding="utf-8",
    )

    symbols = parse_ctypes_symbols(source, tmp_path)

    assert set(symbols) == {
        "ifcopenshell_file_create_entity",
        "ifcopenshell_ifc_file_by_type",
        "ifcopenshell_last_error_message",
        "ifcopenshell_string_destroy",
    }


def test_build_inventory_reports_generated_highlevel_and_duplicate_concepts(tmp_path: Path) -> None:
    generated_dir = tmp_path / "src" / "ifcwrap" / "binding_generator" / "generated"
    generated_dir.mkdir(parents=True)
    (generated_dir / "ifcopenshell_api.h").write_text(
        dedent(
            """
            bool ifcopenshell_ifc_file_by_type(ifcopenshell_ifc_file_t* self, const char* type, void** out_result);
            bool ifcopenshell_ifcparse_schema_names(ifcopenshell_string_list_t* out_result);
            void ifcopenshell_string_destroy(ifcopenshell_string_t* value);
            """
        ),
        encoding="utf-8",
    )

    highlevel_dir = tmp_path / "src" / "ifcapi" / "include" / "ifcapi"
    highlevel_dir.mkdir(parents=True)
    (highlevel_dir / "ifcapi.h").write_text(
        "IFCAPI_EXPORT int32_t ifcopenshell_file_by_type(const ifcopenshell_ifc_file_t* file, const char* type, void** out);\n",
        encoding="utf-8",
    )

    python_dir = tmp_path / "src" / "ifcapi" / "python" / "ifcopenshell"
    python_dir.mkdir(parents=True)
    (python_dir / "ifcopenshell_wrapper.py").write_text(
        'sigs = {"ifcopenshell_ifc_file_by_type": (c_bool, []), "ifcopenshell_file_by_type": (c_int, [])}\n',
        encoding="utf-8",
    )
    (python_dir / "_generated_capi.py").write_text(
        "\n".join(
            [
                "# This file was generated by IfcOpenShell's binding generator. Do not edit manually.",
                "FUNCTION_SIGNATURES = {",
                '    "ifcopenshell_ifcparse_schema_names": (c_bool, []),',
                "}",
                "",
            ]
        ),
        encoding="utf-8",
    )

    inventory = build_inventory(tmp_path)

    assert inventory["generated_c"]["symbol_count"] == 3
    assert inventory["generated_highlevel_c"]["symbol_count"] == 0
    assert inventory["handwritten_highlevel_c"]["symbol_count"] == 1
    assert inventory["generated_python_ctypes"]["symbol_count"] == 1
    assert inventory["generated_python_ctypes"]["missing_generated_c_symbols"] == [
        "ifcopenshell_ifc_file_by_type",
        "ifcopenshell_string_destroy",
    ]
    assert inventory["manual_python_ctypes"]["symbol_count"] == 2
    assert inventory["manual_python_ctypes"]["unexpected_generated_c_redeclarations"] == [
        {"name": "ifcopenshell_ifc_file_by_type", "source": "src/ifcapi/python/ifcopenshell/ifcopenshell_wrapper.py"}
    ]
    assert inventory["duplication"]["potential_core_highlevel_count"] == 1
    duplicate = inventory["duplication"]["potential_core_highlevel"][0]
    assert duplicate["highlevel"] == "ifcopenshell_file_by_type"
    assert duplicate["exact_core_matches"] == ["ifcopenshell_ifc_file_by_type"]


def test_generated_python_ctypes_cover_generated_c_api() -> None:
    repo_root = Path(__file__).resolve().parents[3]
    inventory = build_inventory(repo_root)

    assert inventory["generated_python_ctypes"]["missing_from_c_headers"] == []
    assert inventory["generated_python_ctypes"]["missing_generated_c_symbols"] == []


def test_manual_ctypes_generated_c_redeclarations_are_classified() -> None:
    repo_root = Path(__file__).resolve().parents[3]
    inventory = build_inventory(repo_root)

    assert inventory["manual_python_ctypes"]["unexpected_generated_c_redeclarations"] == []
    assert inventory["manual_python_ctypes"]["allowed_generated_c_redeclarations"] == []


def test_no_unknown_manual_ctypes_or_duplicate_c_exports() -> None:
    repo_root = Path(__file__).resolve().parents[3]
    inventory = build_inventory(repo_root)

    assert inventory["manual_python_ctypes"]["missing_from_c_headers"] == []
    assert inventory["duplication"]["exact_symbol_collisions"] == []
    assert inventory["duplication"]["potential_core_highlevel"] == []


def test_generated_highlevel_c_symbols_are_reported_separately() -> None:
    repo_root = Path(__file__).resolve().parents[3]
    inventory = build_inventory(repo_root)

    generated_highlevel = inventory["generated_highlevel_c"]["symbols"]
    assert inventory["generated_highlevel_c"]["symbol_count"] == len(generated_highlevel)
    assert "ifcopenshell_ifcapi_unit_convert" in generated_highlevel
    assert "ifcopenshell_ifcapi_value_kind" in generated_highlevel
