// Auto-generated by codegen/generate-bindings.ts — DO NOT EDIT

import type { EmscriptenModule } from "../wasm/types.js";

export type Ptr = number;

export function settings_create(M: EmscriptenModule): number {
  return M.ccall("ifcopenshell_ifcgeom_settings_create", "number", [], []);
}

export function settings_destroy(M: EmscriptenModule, settings: number): void {
  return M.ccall("ifcopenshell_ifcgeom_settings_destroy", null, ["number"], [settings]);
}

export function settings_set_bool(M: EmscriptenModule, settings: number, name: string, value: number): number {
  return M.ccall("ifcopenshell_ifcgeom_settings_set_bool", "number", ["number", "string", "number"], [settings, name, value]);
}

export function settings_set_int(M: EmscriptenModule, settings: number, name: string, value: number): number {
  return M.ccall("ifcopenshell_ifcgeom_settings_set_int", "number", ["number", "string", "number"], [settings, name, value]);
}

export function settings_set_double(M: EmscriptenModule, settings: number, name: string, value: number): number {
  return M.ccall("ifcopenshell_ifcgeom_settings_set_double", "number", ["number", "string", "number"], [settings, name, value]);
}

export function settings_set_string(M: EmscriptenModule, settings: number, name: string, value: string): number {
  return M.ccall("ifcopenshell_ifcgeom_settings_set_string", "number", ["number", "string", "string"], [settings, name, value]);
}

export function settings_set_int_set(M: EmscriptenModule, settings: number, name: string, values: number, value_count: number): number {
  return M.ccall("ifcopenshell_ifcgeom_settings_set_int_set", "number", ["number", "string", "number", "number"], [settings, name, values, value_count]);
}

export function settings_set_string_set(M: EmscriptenModule, settings: number, name: string, values: number, value_count: number): number {
  return M.ccall("ifcopenshell_ifcgeom_settings_set_string_set", "number", ["number", "string", "number", "number"], [settings, name, values, value_count]);
}

export function settings_set_double_vector(M: EmscriptenModule, settings: number, name: string, values: number, value_count: number): number {
  return M.ccall("ifcopenshell_ifcgeom_settings_set_double_vector", "number", ["number", "string", "number", "number"], [settings, name, values, value_count]);
}

export function settings_get_bool(M: EmscriptenModule, settings: number, name: string, out_value: number): number {
  return M.ccall("ifcopenshell_ifcgeom_settings_get_bool", "number", ["number", "string", "number"], [settings, name, out_value]);
}

export function settings_get_int(M: EmscriptenModule, settings: number, name: string, out_value: number): number {
  return M.ccall("ifcopenshell_ifcgeom_settings_get_int", "number", ["number", "string", "number"], [settings, name, out_value]);
}

export function settings_get_double(M: EmscriptenModule, settings: number, name: string, out_value: number): number {
  return M.ccall("ifcopenshell_ifcgeom_settings_get_double", "number", ["number", "string", "number"], [settings, name, out_value]);
}

export function settings_get_string(M: EmscriptenModule, settings: number, name: string): string {
  return M.ccall("ifcopenshell_ifcgeom_settings_get_string", "string", ["number", "string"], [settings, name]);
}

export function settings_get_type(M: EmscriptenModule, settings: number, name: string): string {
  return M.ccall("ifcopenshell_ifcgeom_settings_get_type", "string", ["number", "string"], [settings, name]);
}

export function settings_setting_names(M: EmscriptenModule, settings: number): number {
  return M.ccall("ifcopenshell_ifcgeom_settings_setting_names", "number", ["number"], [settings]);
}

export function settings_last_error(M: EmscriptenModule, settings: number): string {
  return M.ccall("ifcopenshell_ifcgeom_settings_last_error", "string", ["number"], [settings]);
}

export function settings_native(M: EmscriptenModule, settings: number): number {
  return M.ccall("ifcopenshell_ifcgeom_settings_native", "number", ["number"], [settings]);
}

export function settings_native_const(M: EmscriptenModule, settings: number): number {
  return M.ccall("ifcopenshell_ifcgeom_settings_native_const", "number", ["number"], [settings]);
}

export function string_list_destroy(M: EmscriptenModule, list: number): void {
  return M.ccall("ifcopenshell_ifcgeom_string_list_destroy", null, ["number"], [list]);
}

export function string_list_count(M: EmscriptenModule, list: number): number {
  return M.ccall("ifcopenshell_ifcgeom_string_list_count", "number", ["number"], [list]);
}

export function string_list_reset(M: EmscriptenModule, list: number): void {
  return M.ccall("ifcopenshell_ifcgeom_string_list_reset", null, ["number"], [list]);
}

export function string_list_get(M: EmscriptenModule, list: number, index: number): string {
  return M.ccall("ifcopenshell_ifcgeom_string_list_get", "string", ["number", "number"], [list, index]);
}

export function string_list_next(M: EmscriptenModule, list: number): string {
  return M.ccall("ifcopenshell_ifcgeom_string_list_next", "string", ["number"], [list]);
}

export function tree_create(M: EmscriptenModule): number {
  return M.ccall("ifcopenshell_ifcgeom_tree_create", "number", [], []);
}

export function tree_destroy(M: EmscriptenModule, tree: number): void {
  return M.ccall("ifcopenshell_ifcgeom_tree_destroy", null, ["number"], [tree]);
}

export function tree_add_file(M: EmscriptenModule, tree: number, file: number, settings: number): number {
  return M.ccall("ifcopenshell_ifcgeom_tree_add_file", "number", ["number", "number", "number"], [tree, file, settings]);
}

export function tree_select_by_id(M: EmscriptenModule, tree: number, file: number, id: number, completely_within: number, extend: number): number {
  return M.ccall("ifcopenshell_ifcgeom_tree_select_by_id", "number", ["number", "number", "number", "number", "number"], [tree, file, id, completely_within, extend]);
}

export function tree_select_box(M: EmscriptenModule, tree: number, min_xyz: number, max_xyz: number, completely_within: number): number {
  return M.ccall("ifcopenshell_ifcgeom_tree_select_box", "number", ["number", "number", "number", "number"], [tree, min_xyz, max_xyz, completely_within]);
}

export function tree_select_point(M: EmscriptenModule, tree: number, xyz: number, extend: number): number {
  return M.ccall("ifcopenshell_ifcgeom_tree_select_point", "number", ["number", "number", "number"], [tree, xyz, extend]);
}

export function tree_clash_intersection_many(M: EmscriptenModule, tree: number, file: number, set_a_ids: number, set_a_count: number, set_b_ids: number, set_b_count: number, tolerance: number, check_all: number): number {
  return M.ccall("ifcopenshell_ifcgeom_tree_clash_intersection_many", "number", ["number", "number", "number", "number", "number", "number", "number", "number"], [tree, file, set_a_ids, set_a_count, set_b_ids, set_b_count, tolerance, check_all]);
}

export function tree_clash_collision_many(M: EmscriptenModule, tree: number, file: number, set_a_ids: number, set_a_count: number, set_b_ids: number, set_b_count: number, allow_touching: number): number {
  return M.ccall("ifcopenshell_ifcgeom_tree_clash_collision_many", "number", ["number", "number", "number", "number", "number", "number", "number"], [tree, file, set_a_ids, set_a_count, set_b_ids, set_b_count, allow_touching]);
}

export function tree_clash_clearance_many(M: EmscriptenModule, tree: number, file: number, set_a_ids: number, set_a_count: number, set_b_ids: number, set_b_count: number, clearance: number, check_all: number): number {
  return M.ccall("ifcopenshell_ifcgeom_tree_clash_clearance_many", "number", ["number", "number", "number", "number", "number", "number", "number", "number"], [tree, file, set_a_ids, set_a_count, set_b_ids, set_b_count, clearance, check_all]);
}

export function tree_last_error(M: EmscriptenModule, tree: number): string {
  return M.ccall("ifcopenshell_ifcgeom_tree_last_error", "string", ["number"], [tree]);
}

export function id_list_destroy(M: EmscriptenModule, list: number): void {
  return M.ccall("ifcopenshell_ifcgeom_id_list_destroy", null, ["number"], [list]);
}

export function id_list_count(M: EmscriptenModule, list: number): number {
  return M.ccall("ifcopenshell_ifcgeom_id_list_count", "number", ["number"], [list]);
}

export function id_list_reset(M: EmscriptenModule, list: number): void {
  return M.ccall("ifcopenshell_ifcgeom_id_list_reset", null, ["number"], [list]);
}

export function id_list_get(M: EmscriptenModule, list: number, index: number, out_value: number): number {
  return M.ccall("ifcopenshell_ifcgeom_id_list_get", "number", ["number", "number", "number"], [list, index, out_value]);
}

export function id_list_next(M: EmscriptenModule, list: number, out_value: number): number {
  return M.ccall("ifcopenshell_ifcgeom_id_list_next", "number", ["number", "number"], [list, out_value]);
}

export function clash_list_destroy(M: EmscriptenModule, list: number): void {
  return M.ccall("ifcopenshell_ifcgeom_clash_list_destroy", null, ["number"], [list]);
}

export function clash_list_count(M: EmscriptenModule, list: number): number {
  return M.ccall("ifcopenshell_ifcgeom_clash_list_count", "number", ["number"], [list]);
}

export function clash_list_reset(M: EmscriptenModule, list: number): void {
  return M.ccall("ifcopenshell_ifcgeom_clash_list_reset", null, ["number"], [list]);
}

export function clash_list_get(M: EmscriptenModule, list: number, index: number): number {
  return M.ccall("ifcopenshell_ifcgeom_clash_list_get", "number", ["number", "number"], [list, index]);
}

export function clash_list_next(M: EmscriptenModule, list: number): number {
  return M.ccall("ifcopenshell_ifcgeom_clash_list_next", "number", ["number"], [list]);
}

export function iterator_create(M: EmscriptenModule, file: number, settings: number, geometry_library: string, num_threads: number): number {
  return M.ccall("ifcopenshell_ifcgeom_iterator_create", "number", ["number", "number", "string", "number"], [file, settings, geometry_library, num_threads]);
}

export function iterator_create_with_type_filter(M: EmscriptenModule, file: number, settings: number, geometry_library: string, values: number, value_count: number, include: number, num_threads: number): number {
  return M.ccall("ifcopenshell_ifcgeom_iterator_create_with_type_filter", "number", ["number", "number", "string", "number", "number", "number", "number"], [file, settings, geometry_library, values, value_count, include, num_threads]);
}

export function iterator_create_with_globalid_filter(M: EmscriptenModule, file: number, settings: number, geometry_library: string, values: number, value_count: number, include: number, num_threads: number): number {
  return M.ccall("ifcopenshell_ifcgeom_iterator_create_with_globalid_filter", "number", ["number", "number", "string", "number", "number", "number", "number"], [file, settings, geometry_library, values, value_count, include, num_threads]);
}

export function iterator_create_with_id_filter(M: EmscriptenModule, file: number, settings: number, geometry_library: string, values: number, value_count: number, include: number, num_threads: number): number {
  return M.ccall("ifcopenshell_ifcgeom_iterator_create_with_id_filter", "number", ["number", "number", "string", "number", "number", "number", "number"], [file, settings, geometry_library, values, value_count, include, num_threads]);
}

export function iterator_destroy(M: EmscriptenModule, iterator: number): void {
  return M.ccall("ifcopenshell_ifcgeom_iterator_destroy", null, ["number"], [iterator]);
}

export function iterator_initialize(M: EmscriptenModule, iterator: number): number {
  return M.ccall("ifcopenshell_ifcgeom_iterator_initialize", "number", ["number"], [iterator]);
}

export function iterator_next(M: EmscriptenModule, iterator: number): number {
  return M.ccall("ifcopenshell_ifcgeom_iterator_next", "number", ["number"], [iterator]);
}

export function iterator_progress(M: EmscriptenModule, iterator: number): number {
  return M.ccall("ifcopenshell_ifcgeom_iterator_progress", "number", ["number"], [iterator]);
}

export function iterator_had_error(M: EmscriptenModule, iterator: number): number {
  return M.ccall("ifcopenshell_ifcgeom_iterator_had_error", "number", ["number"], [iterator]);
}

export function iterator_unit_name(M: EmscriptenModule, iterator: number): string {
  return M.ccall("ifcopenshell_ifcgeom_iterator_unit_name", "string", ["number"], [iterator]);
}

export function iterator_unit_magnitude(M: EmscriptenModule, iterator: number): number {
  return M.ccall("ifcopenshell_ifcgeom_iterator_unit_magnitude", "number", ["number"], [iterator]);
}

export function iterator_compute_bounds(M: EmscriptenModule, iterator: number, with_geometry: number): void {
  return M.ccall("ifcopenshell_ifcgeom_iterator_compute_bounds", null, ["number", "number"], [iterator, with_geometry]);
}

export function iterator_bounds_min(M: EmscriptenModule, iterator: number, out_xyz: number): number {
  return M.ccall("ifcopenshell_ifcgeom_iterator_bounds_min", "number", ["number", "number"], [iterator, out_xyz]);
}

export function iterator_bounds_max(M: EmscriptenModule, iterator: number, out_xyz: number): number {
  return M.ccall("ifcopenshell_ifcgeom_iterator_bounds_max", "number", ["number", "number"], [iterator, out_xyz]);
}

export function iterator_current_id(M: EmscriptenModule, iterator: number, out_value: number): number {
  return M.ccall("ifcopenshell_ifcgeom_iterator_current_id", "number", ["number", "number"], [iterator, out_value]);
}

export function iterator_current_parent_id(M: EmscriptenModule, iterator: number, out_value: number): number {
  return M.ccall("ifcopenshell_ifcgeom_iterator_current_parent_id", "number", ["number", "number"], [iterator, out_value]);
}

export function iterator_current_type(M: EmscriptenModule, iterator: number): string {
  return M.ccall("ifcopenshell_ifcgeom_iterator_current_type", "string", ["number"], [iterator]);
}

export function iterator_current_guid(M: EmscriptenModule, iterator: number): string {
  return M.ccall("ifcopenshell_ifcgeom_iterator_current_guid", "string", ["number"], [iterator]);
}

export function iterator_current_transform(M: EmscriptenModule, iterator: number, out_matrix_16: number): number {
  return M.ccall("ifcopenshell_ifcgeom_iterator_current_transform", "number", ["number", "number"], [iterator, out_matrix_16]);
}

export function iterator_current_kind(M: EmscriptenModule, iterator: number): number {
  return M.ccall("ifcopenshell_ifcgeom_iterator_current_kind", "number", ["number"], [iterator]);
}

export function iterator_get_mesh(M: EmscriptenModule, iterator: number): number {
  return M.ccall("ifcopenshell_ifcgeom_iterator_get_mesh", "number", ["number"], [iterator]);
}

export function iterator_get_serialized(M: EmscriptenModule, iterator: number): number {
  return M.ccall("ifcopenshell_ifcgeom_iterator_get_serialized", "number", ["number"], [iterator]);
}

export function create_mesh_for_id(M: EmscriptenModule, file: number, settings: number, geometry_library: string, id: number): number {
  return M.ccall("ifcopenshell_ifcgeom_create_mesh_for_id", "number", ["number", "number", "string", "number"], [file, settings, geometry_library, id]);
}

export function create_shape_for_id(M: EmscriptenModule, file: number, settings: number, geometry_library: string, id: number): number {
  return M.ccall("ifcopenshell_ifcgeom_create_shape_for_id", "number", ["number", "number", "string", "number"], [file, settings, geometry_library, id]);
}

export function iterator_log(M: EmscriptenModule, iterator: number): string {
  return M.ccall("ifcopenshell_ifcgeom_iterator_log", "string", ["number"], [iterator]);
}

export function iterator_last_error(M: EmscriptenModule, iterator: number): string {
  return M.ccall("ifcopenshell_ifcgeom_iterator_last_error", "string", ["number"], [iterator]);
}

export function mesh_destroy(M: EmscriptenModule, mesh: number): void {
  return M.ccall("ifcopenshell_ifcgeom_mesh_destroy", null, ["number"], [mesh]);
}

export function mesh_id(M: EmscriptenModule, mesh: number): number {
  return M.ccall("ifcopenshell_ifcgeom_mesh_id", "number", ["number"], [mesh]);
}

export function mesh_parent_id(M: EmscriptenModule, mesh: number): number {
  return M.ccall("ifcopenshell_ifcgeom_mesh_parent_id", "number", ["number"], [mesh]);
}

export function mesh_name(M: EmscriptenModule, mesh: number): string {
  return M.ccall("ifcopenshell_ifcgeom_mesh_name", "string", ["number"], [mesh]);
}

export function mesh_type(M: EmscriptenModule, mesh: number): string {
  return M.ccall("ifcopenshell_ifcgeom_mesh_type", "string", ["number"], [mesh]);
}

export function mesh_guid(M: EmscriptenModule, mesh: number): string {
  return M.ccall("ifcopenshell_ifcgeom_mesh_guid", "string", ["number"], [mesh]);
}

export function mesh_context(M: EmscriptenModule, mesh: number): string {
  return M.ccall("ifcopenshell_ifcgeom_mesh_context", "string", ["number"], [mesh]);
}

export function mesh_unique_id(M: EmscriptenModule, mesh: number): string {
  return M.ccall("ifcopenshell_ifcgeom_mesh_unique_id", "string", ["number"], [mesh]);
}

export function mesh_verts_count(M: EmscriptenModule, mesh: number): number {
  return M.ccall("ifcopenshell_ifcgeom_mesh_verts_count", "number", ["number"], [mesh]);
}

export function mesh_verts_data(M: EmscriptenModule, mesh: number): number {
  return M.ccall("ifcopenshell_ifcgeom_mesh_verts_data", "number", ["number"], [mesh]);
}

export function mesh_faces_count(M: EmscriptenModule, mesh: number): number {
  return M.ccall("ifcopenshell_ifcgeom_mesh_faces_count", "number", ["number"], [mesh]);
}

export function mesh_faces_data(M: EmscriptenModule, mesh: number): number {
  return M.ccall("ifcopenshell_ifcgeom_mesh_faces_data", "number", ["number"], [mesh]);
}

export function mesh_edges_count(M: EmscriptenModule, mesh: number): number {
  return M.ccall("ifcopenshell_ifcgeom_mesh_edges_count", "number", ["number"], [mesh]);
}

export function mesh_edges_data(M: EmscriptenModule, mesh: number): number {
  return M.ccall("ifcopenshell_ifcgeom_mesh_edges_data", "number", ["number"], [mesh]);
}

export function mesh_normals_count(M: EmscriptenModule, mesh: number): number {
  return M.ccall("ifcopenshell_ifcgeom_mesh_normals_count", "number", ["number"], [mesh]);
}

export function mesh_normals_data(M: EmscriptenModule, mesh: number): number {
  return M.ccall("ifcopenshell_ifcgeom_mesh_normals_data", "number", ["number"], [mesh]);
}

export function mesh_uvs_count(M: EmscriptenModule, mesh: number): number {
  return M.ccall("ifcopenshell_ifcgeom_mesh_uvs_count", "number", ["number"], [mesh]);
}

export function mesh_uvs_data(M: EmscriptenModule, mesh: number): number {
  return M.ccall("ifcopenshell_ifcgeom_mesh_uvs_data", "number", ["number"], [mesh]);
}

export function mesh_material_ids_count(M: EmscriptenModule, mesh: number): number {
  return M.ccall("ifcopenshell_ifcgeom_mesh_material_ids_count", "number", ["number"], [mesh]);
}

export function mesh_material_ids_data(M: EmscriptenModule, mesh: number): number {
  return M.ccall("ifcopenshell_ifcgeom_mesh_material_ids_data", "number", ["number"], [mesh]);
}

export function mesh_item_ids_count(M: EmscriptenModule, mesh: number): number {
  return M.ccall("ifcopenshell_ifcgeom_mesh_item_ids_count", "number", ["number"], [mesh]);
}

export function mesh_item_ids_data(M: EmscriptenModule, mesh: number): number {
  return M.ccall("ifcopenshell_ifcgeom_mesh_item_ids_data", "number", ["number"], [mesh]);
}

export function mesh_edges_item_ids_count(M: EmscriptenModule, mesh: number): number {
  return M.ccall("ifcopenshell_ifcgeom_mesh_edges_item_ids_count", "number", ["number"], [mesh]);
}

export function mesh_edges_item_ids_data(M: EmscriptenModule, mesh: number): number {
  return M.ccall("ifcopenshell_ifcgeom_mesh_edges_item_ids_data", "number", ["number"], [mesh]);
}

export function mesh_colors_count(M: EmscriptenModule, mesh: number): number {
  return M.ccall("ifcopenshell_ifcgeom_mesh_colors_count", "number", ["number"], [mesh]);
}

export function mesh_colors_data(M: EmscriptenModule, mesh: number): number {
  return M.ccall("ifcopenshell_ifcgeom_mesh_colors_data", "number", ["number"], [mesh]);
}

export function mesh_transform_count(M: EmscriptenModule, mesh: number): number {
  return M.ccall("ifcopenshell_ifcgeom_mesh_transform_count", "number", ["number"], [mesh]);
}

export function mesh_transform_data(M: EmscriptenModule, mesh: number): number {
  return M.ccall("ifcopenshell_ifcgeom_mesh_transform_data", "number", ["number"], [mesh]);
}

export function serialized_destroy(M: EmscriptenModule, serialized: number): void {
  return M.ccall("ifcopenshell_ifcgeom_serialized_destroy", null, ["number"], [serialized]);
}

export function serialized_id(M: EmscriptenModule, serialized: number): number {
  return M.ccall("ifcopenshell_ifcgeom_serialized_id", "number", ["number"], [serialized]);
}

export function serialized_parent_id(M: EmscriptenModule, serialized: number): number {
  return M.ccall("ifcopenshell_ifcgeom_serialized_parent_id", "number", ["number"], [serialized]);
}

export function serialized_name(M: EmscriptenModule, serialized: number): string {
  return M.ccall("ifcopenshell_ifcgeom_serialized_name", "string", ["number"], [serialized]);
}

export function serialized_type(M: EmscriptenModule, serialized: number): string {
  return M.ccall("ifcopenshell_ifcgeom_serialized_type", "string", ["number"], [serialized]);
}

export function serialized_guid(M: EmscriptenModule, serialized: number): string {
  return M.ccall("ifcopenshell_ifcgeom_serialized_guid", "string", ["number"], [serialized]);
}

export function serialized_context(M: EmscriptenModule, serialized: number): string {
  return M.ccall("ifcopenshell_ifcgeom_serialized_context", "string", ["number"], [serialized]);
}

export function serialized_unique_id(M: EmscriptenModule, serialized: number): string {
  return M.ccall("ifcopenshell_ifcgeom_serialized_unique_id", "string", ["number"], [serialized]);
}

export function serialized_brep_data(M: EmscriptenModule, serialized: number): string {
  return M.ccall("ifcopenshell_ifcgeom_serialized_brep_data", "string", ["number"], [serialized]);
}

export function serialized_surface_styles_count(M: EmscriptenModule, serialized: number): number {
  return M.ccall("ifcopenshell_ifcgeom_serialized_surface_styles_count", "number", ["number"], [serialized]);
}

export function serialized_surface_styles_data(M: EmscriptenModule, serialized: number): number {
  return M.ccall("ifcopenshell_ifcgeom_serialized_surface_styles_data", "number", ["number"], [serialized]);
}

export function serialized_surface_style_ids_count(M: EmscriptenModule, serialized: number): number {
  return M.ccall("ifcopenshell_ifcgeom_serialized_surface_style_ids_count", "number", ["number"], [serialized]);
}

export function serialized_surface_style_ids_data(M: EmscriptenModule, serialized: number): number {
  return M.ccall("ifcopenshell_ifcgeom_serialized_surface_style_ids_data", "number", ["number"], [serialized]);
}

export function serialized_transform_count(M: EmscriptenModule, serialized: number): number {
  return M.ccall("ifcopenshell_ifcgeom_serialized_transform_count", "number", ["number"], [serialized]);
}

export function serialized_transform_data(M: EmscriptenModule, serialized: number): number {
  return M.ccall("ifcopenshell_ifcgeom_serialized_transform_data", "number", ["number"], [serialized]);
}

export function created_shape_destroy(M: EmscriptenModule, shape: number): void {
  return M.ccall("ifcopenshell_ifcgeom_created_shape_destroy", null, ["number"], [shape]);
}

export function created_shape_kind(M: EmscriptenModule, shape: number): number {
  return M.ccall("ifcopenshell_ifcgeom_created_shape_kind", "number", ["number"], [shape]);
}

export function created_shape_mesh(M: EmscriptenModule, shape: number): number {
  return M.ccall("ifcopenshell_ifcgeom_created_shape_mesh", "number", ["number"], [shape]);
}

export function created_shape_serialized(M: EmscriptenModule, shape: number): number {
  return M.ccall("ifcopenshell_ifcgeom_created_shape_serialized", "number", ["number"], [shape]);
}

export function created_shape_transform(M: EmscriptenModule, shape: number, out_matrix_16: number): number {
  return M.ccall("ifcopenshell_ifcgeom_created_shape_transform", "number", ["number", "number"], [shape, out_matrix_16]);
}

export function map_shape_repr_for_id(M: EmscriptenModule, file: number, settings: number, id: number): string {
  return M.ccall("ifcopenshell_ifcgeom_map_shape_repr_for_id", "string", ["number", "number", "number"], [file, settings, id]);
}

export function last_error(M: EmscriptenModule): string {
  return M.ccall("ifcopenshell_ifcgeom_last_error", "string", [], []);
}
