// Auto-generated by codegen/generate-bindings.ts — DO NOT EDIT

import type { EmscriptenModule } from "../wasm/types.js";

export type Ptr = number;

export function load_template_from_memory(M: EmscriptenModule, schema_name: string | null, data: number, length: number): number {
  return M.ccall("ifcopenshell_psetqto_load_template_from_memory", "number", ["string", "number", "number"], [schema_name, data, length]);
}

export function load_template_from_file(M: EmscriptenModule, schema_name: string | null, path: string | null): number {
  return M.ccall("ifcopenshell_psetqto_load_template_from_file", "number", ["string", "string"], [schema_name, path]);
}

export function unload_template(M: EmscriptenModule, schema_name: string | null): number {
  return M.ccall("ifcopenshell_psetqto_unload_template", "number", ["string"], [schema_name]);
}

export function is_template_loaded(M: EmscriptenModule, schema_name: string | null): number {
  return M.ccall("ifcopenshell_psetqto_is_template_loaded", "number", ["string"], [schema_name]);
}

export function get_applicable(M: EmscriptenModule, schema_name: string | null, ifc_class: string | null, predefined_type: string | null, pset_only: number, qto_only: number): number {
  return M.ccall("ifcopenshell_psetqto_get_applicable", "number", ["string", "string", "string", "number", "number"], [schema_name, ifc_class, predefined_type, pset_only, qto_only]);
}

export function get_applicable_names(M: EmscriptenModule, schema_name: string | null, ifc_class: string | null, predefined_type: string | null, pset_only: number, qto_only: number): number {
  return M.ccall("ifcopenshell_psetqto_get_applicable_names", "number", ["string", "string", "string", "number", "number"], [schema_name, ifc_class, predefined_type, pset_only, qto_only]);
}

export function get_by_name(M: EmscriptenModule, schema_name: string | null, name: string | null): number {
  return M.ccall("ifcopenshell_psetqto_get_by_name", "number", ["string", "string"], [schema_name, name]);
}

export function is_templated(M: EmscriptenModule, schema_name: string | null, name: string | null): number {
  return M.ccall("ifcopenshell_psetqto_is_templated", "number", ["string", "string"], [schema_name, name]);
}

export function all_templates(M: EmscriptenModule, schema_name: string | null): number {
  return M.ccall("ifcopenshell_psetqto_all_templates", "number", ["string"], [schema_name]);
}

export function template_list_count(M: EmscriptenModule, handle: number): number {
  return M.ccall("ifcopenshell_psetqto_template_list_count", "number", ["number"], [handle]);
}

export function template_list_get(M: EmscriptenModule, handle: number, index: number): number {
  return M.ccall("ifcopenshell_psetqto_template_list_get", "number", ["number", "number"], [handle, index]);
}

export function template_list_close(M: EmscriptenModule, handle: number): void {
  return M.ccall("ifcopenshell_psetqto_template_list_close", null, ["number"], [handle]);
}

export function template_name_borrowed(M: EmscriptenModule, entity: number): number {
  return M.ccall("ifcopenshell_psetqto_template_name_borrowed", "number", ["number"], [entity]);
}

export function template_name_copy(M: EmscriptenModule, entity: number): number {
  return M.ccall("ifcopenshell_psetqto_template_name_copy", "number", ["number"], [entity]);
}

export function template_description_borrowed(M: EmscriptenModule, entity: number): number {
  return M.ccall("ifcopenshell_psetqto_template_description_borrowed", "number", ["number"], [entity]);
}

export function template_description_copy(M: EmscriptenModule, entity: number): number {
  return M.ccall("ifcopenshell_psetqto_template_description_copy", "number", ["number"], [entity]);
}

export function template_type_borrowed(M: EmscriptenModule, entity: number): number {
  return M.ccall("ifcopenshell_psetqto_template_type_borrowed", "number", ["number"], [entity]);
}

export function template_type_copy(M: EmscriptenModule, entity: number): number {
  return M.ccall("ifcopenshell_psetqto_template_type_copy", "number", ["number"], [entity]);
}

export function template_applicable_entity_borrowed(M: EmscriptenModule, entity: number): number {
  return M.ccall("ifcopenshell_psetqto_template_applicable_entity_borrowed", "number", ["number"], [entity]);
}

export function template_applicable_entity_copy(M: EmscriptenModule, entity: number): number {
  return M.ccall("ifcopenshell_psetqto_template_applicable_entity_copy", "number", ["number"], [entity]);
}

export function template_properties(M: EmscriptenModule, entity: number): number {
  return M.ccall("ifcopenshell_psetqto_template_properties", "number", ["number"], [entity]);
}

export function property_name_borrowed(M: EmscriptenModule, entity: number): number {
  return M.ccall("ifcopenshell_psetqto_property_name_borrowed", "number", ["number"], [entity]);
}

export function property_name_copy(M: EmscriptenModule, entity: number): number {
  return M.ccall("ifcopenshell_psetqto_property_name_copy", "number", ["number"], [entity]);
}

export function property_description_borrowed(M: EmscriptenModule, entity: number): number {
  return M.ccall("ifcopenshell_psetqto_property_description_borrowed", "number", ["number"], [entity]);
}

export function property_description_copy(M: EmscriptenModule, entity: number): number {
  return M.ccall("ifcopenshell_psetqto_property_description_copy", "number", ["number"], [entity]);
}

export function property_template_type_borrowed(M: EmscriptenModule, entity: number): number {
  return M.ccall("ifcopenshell_psetqto_property_template_type_borrowed", "number", ["number"], [entity]);
}

export function property_template_type_copy(M: EmscriptenModule, entity: number): number {
  return M.ccall("ifcopenshell_psetqto_property_template_type_copy", "number", ["number"], [entity]);
}

export function property_primary_measure_type_borrowed(M: EmscriptenModule, entity: number): number {
  return M.ccall("ifcopenshell_psetqto_property_primary_measure_type_borrowed", "number", ["number"], [entity]);
}

export function property_primary_measure_type_copy(M: EmscriptenModule, entity: number): number {
  return M.ccall("ifcopenshell_psetqto_property_primary_measure_type_copy", "number", ["number"], [entity]);
}

export function property_list_count(M: EmscriptenModule, handle: number): number {
  return M.ccall("ifcopenshell_psetqto_property_list_count", "number", ["number"], [handle]);
}

export function property_list_get(M: EmscriptenModule, handle: number, index: number): number {
  return M.ccall("ifcopenshell_psetqto_property_list_get", "number", ["number", "number"], [handle, index]);
}

export function property_list_close(M: EmscriptenModule, handle: number): void {
  return M.ccall("ifcopenshell_psetqto_property_list_close", null, ["number"], [handle]);
}

export function string_list_count(M: EmscriptenModule, handle: number): number {
  return M.ccall("ifcopenshell_psetqto_string_list_count", "number", ["number"], [handle]);
}

export function string_list_get(M: EmscriptenModule, handle: number, index: number): number {
  return M.ccall("ifcopenshell_psetqto_string_list_get", "number", ["number", "number"], [handle, index]);
}

export function string_list_close(M: EmscriptenModule, handle: number): void {
  return M.ccall("ifcopenshell_psetqto_string_list_close", null, ["number"], [handle]);
}

export function deinit(M: EmscriptenModule): void {
  return M.ccall("ifcopenshell_psetqto_deinit", null, [], []);
}
