// Auto-generated by codegen/generate-bindings.ts — DO NOT EDIT

import type { EmscriptenModule } from "../wasm/types.js";

export type Ptr = number;

export function element_get_type(M: EmscriptenModule, entity: number): number {
  return M.ccall("ifcopenshell_ifcutil_element_get_type", "number", ["number"], [entity]);
}

export function element_get_types(M: EmscriptenModule, entity: number): number {
  return M.ccall("ifcopenshell_ifcutil_element_get_types", "number", ["number"], [entity]);
}

export function element_get_predefined_type_copy(M: EmscriptenModule, entity: number): number {
  return M.ccall("ifcopenshell_ifcutil_element_get_predefined_type_copy", "number", ["number"], [entity]);
}

export function element_is_userdefined_type(M: EmscriptenModule, entity: number): number {
  return M.ccall("ifcopenshell_ifcutil_element_is_userdefined_type", "number", ["number"], [entity]);
}

export function element_get_aggregate(M: EmscriptenModule, entity: number): number {
  return M.ccall("ifcopenshell_ifcutil_element_get_aggregate", "number", ["number"], [entity]);
}

export function element_get_nest(M: EmscriptenModule, entity: number): number {
  return M.ccall("ifcopenshell_ifcutil_element_get_nest", "number", ["number"], [entity]);
}

export function element_get_filled_void(M: EmscriptenModule, entity: number): number {
  return M.ccall("ifcopenshell_ifcutil_element_get_filled_void", "number", ["number"], [entity]);
}

export function element_get_voided_element(M: EmscriptenModule, entity: number): number {
  return M.ccall("ifcopenshell_ifcutil_element_get_voided_element", "number", ["number"], [entity]);
}

export function element_get_container(M: EmscriptenModule, entity: number, should_get_direct: number, ifc_class: string | null): number {
  return M.ccall("ifcopenshell_ifcutil_element_get_container", "number", ["number", "number", "string"], [entity, should_get_direct, ifc_class]);
}

export function element_get_parent(M: EmscriptenModule, entity: number): number {
  return M.ccall("ifcopenshell_ifcutil_element_get_parent", "number", ["number"], [entity]);
}

export function element_get_material(M: EmscriptenModule, entity: number, should_skip_usage: number, should_inherit: number): number {
  return M.ccall("ifcopenshell_ifcutil_element_get_material", "number", ["number", "number", "number"], [entity, should_skip_usage, should_inherit]);
}

export function element_get_pset_entities(M: EmscriptenModule, entity: number, psets_only: number, qtos_only: number, should_inherit: number): number {
  return M.ccall("ifcopenshell_ifcutil_element_get_pset_entities", "number", ["number", "number", "number", "number"], [entity, psets_only, qtos_only, should_inherit]);
}

export function element_get_pset_entity(M: EmscriptenModule, entity: number, pset_name: string | null, psets_only: number, qtos_only: number, should_inherit: number): number {
  return M.ccall("ifcopenshell_ifcutil_element_get_pset_entity", "number", ["number", "string", "number", "number", "number"], [entity, pset_name, psets_only, qtos_only, should_inherit]);
}

export function element_get_property_entities(M: EmscriptenModule, definition: number): number {
  return M.ccall("ifcopenshell_ifcutil_element_get_property_entities", "number", ["number"], [definition]);
}

export function element_get_property_entity(M: EmscriptenModule, definition: number, property_name: string | null): number {
  return M.ccall("ifcopenshell_ifcutil_element_get_property_entity", "number", ["number", "string"], [definition, property_name]);
}

export function element_get_property_value(M: EmscriptenModule, property_entity: number): number {
  return M.ccall("ifcopenshell_ifcutil_element_get_property_value", "number", ["number"], [property_entity]);
}

export function element_get_pset(M: EmscriptenModule, entity: number, pset_name: string | null, psets_only: number, qtos_only: number, should_inherit: number): number {
  return M.ccall("ifcopenshell_ifcutil_element_get_pset", "number", ["number", "string", "number", "number", "number"], [entity, pset_name, psets_only, qtos_only, should_inherit]);
}

export function element_get_psets(M: EmscriptenModule, entity: number, psets_only: number, qtos_only: number, should_inherit: number): number {
  return M.ccall("ifcopenshell_ifcutil_element_get_psets", "number", ["number", "number", "number", "number"], [entity, psets_only, qtos_only, should_inherit]);
}

export function pset_name_copy(M: EmscriptenModule, handle: number): number {
  return M.ccall("ifcopenshell_ifcutil_pset_name_copy", "number", ["number"], [handle]);
}

export function pset_definition(M: EmscriptenModule, handle: number): number {
  return M.ccall("ifcopenshell_ifcutil_pset_definition", "number", ["number"], [handle]);
}

export function pset_property_count(M: EmscriptenModule, handle: number): number {
  return M.ccall("ifcopenshell_ifcutil_pset_property_count", "number", ["number"], [handle]);
}

export function pset_property_name_copy(M: EmscriptenModule, handle: number, index: number): number {
  return M.ccall("ifcopenshell_ifcutil_pset_property_name_copy", "number", ["number", "number"], [handle, index]);
}

export function pset_property_entity(M: EmscriptenModule, handle: number, index: number): number {
  return M.ccall("ifcopenshell_ifcutil_pset_property_entity", "number", ["number", "number"], [handle, index]);
}

export function pset_property_value_kind(M: EmscriptenModule, handle: number, index: number): number {
  return M.ccall("ifcopenshell_ifcutil_pset_property_value_kind", "number", ["number", "number"], [handle, index]);
}

export function pset_property_value_int(M: EmscriptenModule, handle: number, index: number): number {
  return M.ccall("ifcopenshell_ifcutil_pset_property_value_int", "number", ["number", "number"], [handle, index]);
}

export function pset_property_value_double(M: EmscriptenModule, handle: number, index: number): number {
  return M.ccall("ifcopenshell_ifcutil_pset_property_value_double", "number", ["number", "number"], [handle, index]);
}

export function pset_property_value_string_copy(M: EmscriptenModule, handle: number, index: number): number {
  return M.ccall("ifcopenshell_ifcutil_pset_property_value_string_copy", "number", ["number", "number"], [handle, index]);
}

export function pset_property_value_list_count(M: EmscriptenModule, handle: number, index: number): number {
  return M.ccall("ifcopenshell_ifcutil_pset_property_value_list_count", "number", ["number", "number"], [handle, index]);
}

export function pset_property_value_list_item_kind(M: EmscriptenModule, handle: number, prop_index: number, list_index: number): number {
  return M.ccall("ifcopenshell_ifcutil_pset_property_value_list_item_kind", "number", ["number", "number", "number"], [handle, prop_index, list_index]);
}

export function pset_property_value_list_item_int(M: EmscriptenModule, handle: number, prop_index: number, list_index: number): number {
  return M.ccall("ifcopenshell_ifcutil_pset_property_value_list_item_int", "number", ["number", "number", "number"], [handle, prop_index, list_index]);
}

export function pset_property_value_list_item_double(M: EmscriptenModule, handle: number, prop_index: number, list_index: number): number {
  return M.ccall("ifcopenshell_ifcutil_pset_property_value_list_item_double", "number", ["number", "number", "number"], [handle, prop_index, list_index]);
}

export function pset_property_value_list_item_string_copy(M: EmscriptenModule, handle: number, prop_index: number, list_index: number): number {
  return M.ccall("ifcopenshell_ifcutil_pset_property_value_list_item_string_copy", "number", ["number", "number", "number"], [handle, prop_index, list_index]);
}

export function pset_destroy(M: EmscriptenModule, handle: number): void {
  return M.ccall("ifcopenshell_ifcutil_pset_destroy", null, ["number"], [handle]);
}

export function pset_list_count(M: EmscriptenModule, handle: number): number {
  return M.ccall("ifcopenshell_ifcutil_pset_list_count", "number", ["number"], [handle]);
}

export function pset_list_get(M: EmscriptenModule, handle: number, index: number): number {
  return M.ccall("ifcopenshell_ifcutil_pset_list_get", "number", ["number", "number"], [handle, index]);
}

export function pset_list_destroy(M: EmscriptenModule, handle: number): void {
  return M.ccall("ifcopenshell_ifcutil_pset_list_destroy", null, ["number"], [handle]);
}

export function property_value_kind(M: EmscriptenModule, handle: number): number {
  return M.ccall("ifcopenshell_ifcutil_property_value_kind", "number", ["number"], [handle]);
}

export function property_value_int(M: EmscriptenModule, handle: number): number {
  return M.ccall("ifcopenshell_ifcutil_property_value_int", "number", ["number"], [handle]);
}

export function property_value_double(M: EmscriptenModule, handle: number): number {
  return M.ccall("ifcopenshell_ifcutil_property_value_double", "number", ["number"], [handle]);
}

export function property_value_string_copy(M: EmscriptenModule, handle: number): number {
  return M.ccall("ifcopenshell_ifcutil_property_value_string_copy", "number", ["number"], [handle]);
}

export function property_value_list_count(M: EmscriptenModule, handle: number): number {
  return M.ccall("ifcopenshell_ifcutil_property_value_list_count", "number", ["number"], [handle]);
}

export function property_value_destroy(M: EmscriptenModule, handle: number): void {
  return M.ccall("ifcopenshell_ifcutil_property_value_destroy", null, ["number"], [handle]);
}

export function entity_list_count(M: EmscriptenModule, handle: number): number {
  return M.ccall("ifcopenshell_ifcutil_entity_list_count", "number", ["number"], [handle]);
}

export function entity_list_get(M: EmscriptenModule, handle: number, index: number): number {
  return M.ccall("ifcopenshell_ifcutil_entity_list_get", "number", ["number", "number"], [handle, index]);
}

export function entity_list_destroy(M: EmscriptenModule, handle: number): void {
  return M.ccall("ifcopenshell_ifcutil_entity_list_destroy", null, ["number"], [handle]);
}

export function classification_get_classification(M: EmscriptenModule, reference: number): number {
  return M.ccall("ifcopenshell_ifcutil_classification_get_classification", "number", ["number"], [reference]);
}

export function classification_get_inherited_references(M: EmscriptenModule, reference: number): number {
  return M.ccall("ifcopenshell_ifcutil_classification_get_inherited_references", "number", ["number"], [reference]);
}

export function classification_get_references(M: EmscriptenModule, entity: number, should_inherit: number): number {
  return M.ccall("ifcopenshell_ifcutil_classification_get_references", "number", ["number", "number"], [entity, should_inherit]);
}

export function unit_get_project_unit(M: EmscriptenModule, file: number, unit_type: string | null): number {
  return M.ccall("ifcopenshell_ifcutil_unit_get_project_unit", "number", ["number", "string"], [file, unit_type]);
}

export function unit_get_property_unit(M: EmscriptenModule, property_entity: number, file: number): number {
  return M.ccall("ifcopenshell_ifcutil_unit_get_property_unit", "number", ["number", "number"], [property_entity, file]);
}

export function unit_get_property_table_unit(M: EmscriptenModule, property_entity: number, file: number): number {
  return M.ccall("ifcopenshell_ifcutil_unit_get_property_table_unit", "number", ["number", "number"], [property_entity, file]);
}

export function property_table_unit_defining(M: EmscriptenModule, handle: number): number {
  return M.ccall("ifcopenshell_ifcutil_property_table_unit_defining", "number", ["number"], [handle]);
}

export function property_table_unit_defined(M: EmscriptenModule, handle: number): number {
  return M.ccall("ifcopenshell_ifcutil_property_table_unit_defined", "number", ["number"], [handle]);
}

export function property_table_unit_destroy(M: EmscriptenModule, handle: number): void {
  return M.ccall("ifcopenshell_ifcutil_property_table_unit_destroy", null, ["number"], [handle]);
}

export function unit_convert(M: EmscriptenModule, value: number, from_prefix: string | null, from_unit: string | null, to_prefix: string | null, to_unit: string | null): number {
  return M.ccall("ifcopenshell_ifcutil_unit_convert", "number", ["number", "string", "string", "string", "string"], [value, from_prefix, from_unit, to_prefix, to_unit]);
}

export function unit_calculate_unit_scale(M: EmscriptenModule, file: number, unit_type: string | null): number {
  return M.ccall("ifcopenshell_ifcutil_unit_calculate_unit_scale", "number", ["number", "string"], [file, unit_type]);
}

export function unit_si_type_name_copy(M: EmscriptenModule, unit_type: string | null): number {
  return M.ccall("ifcopenshell_ifcutil_unit_si_type_name_copy", "number", ["string"], [unit_type]);
}

export function free_string(M: EmscriptenModule, ptr: number): void {
  return M.ccall("ifcopenshell_ifcutil_free_string", null, ["number"], [ptr]);
}
