// Auto-generated by codegen/generate-bindings.ts — DO NOT EDIT

import type { EmscriptenModule } from "../wasm/types.js";

export type Ptr = number;

export function settings_create(M: EmscriptenModule): number {
  return M.ccall("ifcopenshell_ifcserializers_settings_create", "number", [], []);
}

export function settings_destroy(M: EmscriptenModule, settings: number): void {
  return M.ccall("ifcopenshell_ifcserializers_settings_destroy", null, ["number"], [settings]);
}

export function settings_set_bool(M: EmscriptenModule, settings: number, name: string, value: number): number {
  return M.ccall("ifcopenshell_ifcserializers_settings_set_bool", "number", ["number", "string", "number"], [settings, name, value]);
}

export function settings_set_int(M: EmscriptenModule, settings: number, name: string, value: number): number {
  return M.ccall("ifcopenshell_ifcserializers_settings_set_int", "number", ["number", "string", "number"], [settings, name, value]);
}

export function settings_set_double(M: EmscriptenModule, settings: number, name: string, value: number): number {
  return M.ccall("ifcopenshell_ifcserializers_settings_set_double", "number", ["number", "string", "number"], [settings, name, value]);
}

export function settings_set_string(M: EmscriptenModule, settings: number, name: string, value: string): number {
  return M.ccall("ifcopenshell_ifcserializers_settings_set_string", "number", ["number", "string", "string"], [settings, name, value]);
}

export function settings_get_bool(M: EmscriptenModule, settings: number, name: string, out_value: number): number {
  return M.ccall("ifcopenshell_ifcserializers_settings_get_bool", "number", ["number", "string", "number"], [settings, name, out_value]);
}

export function settings_get_int(M: EmscriptenModule, settings: number, name: string, out_value: number): number {
  return M.ccall("ifcopenshell_ifcserializers_settings_get_int", "number", ["number", "string", "number"], [settings, name, out_value]);
}

export function settings_get_double(M: EmscriptenModule, settings: number, name: string, out_value: number): number {
  return M.ccall("ifcopenshell_ifcserializers_settings_get_double", "number", ["number", "string", "number"], [settings, name, out_value]);
}

export function settings_get_string(M: EmscriptenModule, settings: number, name: string): string {
  return M.ccall("ifcopenshell_ifcserializers_settings_get_string", "string", ["number", "string"], [settings, name]);
}

export function settings_get_type(M: EmscriptenModule, settings: number, name: string): string {
  return M.ccall("ifcopenshell_ifcserializers_settings_get_type", "string", ["number", "string"], [settings, name]);
}

export function settings_setting_names(M: EmscriptenModule, settings: number): number {
  return M.ccall("ifcopenshell_ifcserializers_settings_setting_names", "number", ["number"], [settings]);
}

export function settings_last_error(M: EmscriptenModule, settings: number): string {
  return M.ccall("ifcopenshell_ifcserializers_settings_last_error", "string", ["number"], [settings]);
}

export function string_list_destroy(M: EmscriptenModule, list: number): void {
  return M.ccall("ifcopenshell_ifcserializers_string_list_destroy", null, ["number"], [list]);
}

export function string_list_count(M: EmscriptenModule, list: number): number {
  return M.ccall("ifcopenshell_ifcserializers_string_list_count", "number", ["number"], [list]);
}

export function string_list_reset(M: EmscriptenModule, list: number): void {
  return M.ccall("ifcopenshell_ifcserializers_string_list_reset", null, ["number"], [list]);
}

export function string_list_get(M: EmscriptenModule, list: number, index: number): string {
  return M.ccall("ifcopenshell_ifcserializers_string_list_get", "string", ["number", "number"], [list, index]);
}

export function string_list_next(M: EmscriptenModule, list: number): string {
  return M.ccall("ifcopenshell_ifcserializers_string_list_next", "string", ["number"], [list]);
}

export function serializer_obj_create_file(M: EmscriptenModule, geometry_settings: number, serializer_settings: number, obj_filename: string, mtl_filename: string): number {
  return M.ccall("ifcopenshell_ifcserializers_serializer_obj_create_file", "number", ["number", "number", "string", "string"], [geometry_settings, serializer_settings, obj_filename, mtl_filename]);
}

export function serializer_obj_create_buffer(M: EmscriptenModule, geometry_settings: number, serializer_settings: number): number {
  return M.ccall("ifcopenshell_ifcserializers_serializer_obj_create_buffer", "number", ["number", "number"], [geometry_settings, serializer_settings]);
}

export function serializer_svg_create_file(M: EmscriptenModule, geometry_settings: number, serializer_settings: number, svg_filename: string): number {
  return M.ccall("ifcopenshell_ifcserializers_serializer_svg_create_file", "number", ["number", "number", "string"], [geometry_settings, serializer_settings, svg_filename]);
}

export function serializer_svg_create_buffer(M: EmscriptenModule, geometry_settings: number, serializer_settings: number): number {
  return M.ccall("ifcopenshell_ifcserializers_serializer_svg_create_buffer", "number", ["number", "number"], [geometry_settings, serializer_settings]);
}

export function serializer_ttl_create_file(M: EmscriptenModule, geometry_settings: number, serializer_settings: number, ttl_filename: string): number {
  return M.ccall("ifcopenshell_ifcserializers_serializer_ttl_create_file", "number", ["number", "number", "string"], [geometry_settings, serializer_settings, ttl_filename]);
}

export function serializer_ttl_create_buffer(M: EmscriptenModule, geometry_settings: number, serializer_settings: number): number {
  return M.ccall("ifcopenshell_ifcserializers_serializer_ttl_create_buffer", "number", ["number", "number"], [geometry_settings, serializer_settings]);
}

export function serializer_destroy(M: EmscriptenModule, serializer: number): void {
  return M.ccall("ifcopenshell_ifcserializers_serializer_destroy", null, ["number"], [serializer]);
}

export function serializer_ready(M: EmscriptenModule, serializer: number): number {
  return M.ccall("ifcopenshell_ifcserializers_serializer_ready", "number", ["number"], [serializer]);
}

export function serializer_run(M: EmscriptenModule, serializer: number, file: number, geometry_library: string, num_threads: number): number {
  return M.ccall("ifcopenshell_ifcserializers_serializer_run", "number", ["number", "number", "string", "number"], [serializer, file, geometry_library, num_threads]);
}

export function serializer_buffer_primary(M: EmscriptenModule, serializer: number): string {
  return M.ccall("ifcopenshell_ifcserializers_serializer_buffer_primary", "string", ["number"], [serializer]);
}

export function serializer_buffer_secondary(M: EmscriptenModule, serializer: number): string {
  return M.ccall("ifcopenshell_ifcserializers_serializer_buffer_secondary", "string", ["number"], [serializer]);
}

export function serializer_last_error(M: EmscriptenModule, serializer: number): string {
  return M.ccall("ifcopenshell_ifcserializers_serializer_last_error", "string", ["number"], [serializer]);
}

export function export_obj(M: EmscriptenModule, file: number, geometry_settings: number, serializer_settings: number, obj_filename: string, mtl_filename: string, geometry_library: string, num_threads: number): number {
  return M.ccall("ifcopenshell_ifcserializers_export_obj", "number", ["number", "number", "number", "string", "string", "string", "number"], [file, geometry_settings, serializer_settings, obj_filename, mtl_filename, geometry_library, num_threads]);
}

export function export_svg(M: EmscriptenModule, file: number, geometry_settings: number, serializer_settings: number, svg_filename: string, geometry_library: string, num_threads: number): number {
  return M.ccall("ifcopenshell_ifcserializers_export_svg", "number", ["number", "number", "number", "string", "string", "number"], [file, geometry_settings, serializer_settings, svg_filename, geometry_library, num_threads]);
}

export function export_step(M: EmscriptenModule, file: number, geometry_settings: number, serializer_settings: number, step_filename: string, geometry_library: string, num_threads: number): number {
  return M.ccall("ifcopenshell_ifcserializers_export_step", "number", ["number", "number", "number", "string", "string", "number"], [file, geometry_settings, serializer_settings, step_filename, geometry_library, num_threads]);
}

export function export_iges(M: EmscriptenModule, file: number, geometry_settings: number, serializer_settings: number, iges_filename: string, geometry_library: string, num_threads: number): number {
  return M.ccall("ifcopenshell_ifcserializers_export_iges", "number", ["number", "number", "number", "string", "string", "number"], [file, geometry_settings, serializer_settings, iges_filename, geometry_library, num_threads]);
}

export function export_ttl(M: EmscriptenModule, file: number, geometry_settings: number, serializer_settings: number, ttl_filename: string, geometry_library: string, num_threads: number): number {
  return M.ccall("ifcopenshell_ifcserializers_export_ttl", "number", ["number", "number", "number", "string", "string", "number"], [file, geometry_settings, serializer_settings, ttl_filename, geometry_library, num_threads]);
}

export function export_gltf(M: EmscriptenModule, file: number, geometry_settings: number, serializer_settings: number, gltf_filename: string, geometry_library: string, num_threads: number): number {
  return M.ccall("ifcopenshell_ifcserializers_export_gltf", "number", ["number", "number", "number", "string", "string", "number"], [file, geometry_settings, serializer_settings, gltf_filename, geometry_library, num_threads]);
}

export function export_xml(M: EmscriptenModule, file: number, xml_filename: string): number {
  return M.ccall("ifcopenshell_ifcserializers_export_xml", "number", ["number", "string"], [file, xml_filename]);
}

export function export_json(M: EmscriptenModule, file: number, json_filename: string): number {
  return M.ccall("ifcopenshell_ifcserializers_export_json", "number", ["number", "string"], [file, json_filename]);
}

export function has_gltf(M: EmscriptenModule): number {
  return M.ccall("ifcopenshell_ifcserializers_has_gltf", "number", [], []);
}

export function has_json(M: EmscriptenModule): number {
  return M.ccall("ifcopenshell_ifcserializers_has_json", "number", [], []);
}

export function has_svg(M: EmscriptenModule): number {
  return M.ccall("ifcopenshell_ifcserializers_has_svg", "number", [], []);
}

export function has_ttl(M: EmscriptenModule): number {
  return M.ccall("ifcopenshell_ifcserializers_has_ttl", "number", [], []);
}

export function has_step(M: EmscriptenModule): number {
  return M.ccall("ifcopenshell_ifcserializers_has_step", "number", [], []);
}

export function has_iges(M: EmscriptenModule): number {
  return M.ccall("ifcopenshell_ifcserializers_has_iges", "number", [], []);
}

export function last_error(M: EmscriptenModule): string {
  return M.ccall("ifcopenshell_ifcserializers_last_error", "string", [], []);
}
