export const enum PropertyValueKind {
  NONE = 0,
  INT = 1,
  BOOL = 2,
  DOUBLE = 3,
  STRING = 4,
  LIST = 5,
  TABLE = 6,
  UNSUPPORTED = 7,
}

export const UnitType = {
  LENGTHUNIT: "LENGTHUNIT",
  AREAUNIT: "AREAUNIT",
  VOLUMEUNIT: "VOLUMEUNIT",
  MASSUNIT: "MASSUNIT",
  TIMEUNIT: "TIMEUNIT",
  THERMODYNAMICTEMPERATUREUNIT: "THERMODYNAMICTEMPERATUREUNIT",
  ELECTRICCURRENTUNIT: "ELECTRICCURRENTUNIT",
  LUMINOUSINTENSITYUNIT: "LUMINOUSINTENSITYUNIT",
  AMOUNTOFSUBSTANCEUNIT: "AMOUNTOFSUBSTANCEUNIT",
  PLANEANGLEUNIT: "PLANEANGLEUNIT",
  SOLIDANGLEUNIT: "SOLIDANGLEUNIT",
  FREQUENCYUNIT: "FREQUENCYUNIT",
  FORCEUNIT: "FORCEUNIT",
  PRESSUREUNIT: "PRESSUREUNIT",
  ENERGYUNIT: "ENERGYUNIT",
  POWERUNIT: "POWERUNIT",
} as const;

export type UnitType = (typeof UnitType)[keyof typeof UnitType];
