import { describe, it, expect, beforeAll, afterAll } from "vitest";
import { createRequire } from "node:module";
import { readFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

import { setModule } from "../src/api.js";
import { IfcFile } from "../src/parse/IfcFile.js";
import { GeomSettings } from "../src/geom/Settings.js";
import {
  SerializerSettings,
  hasFormat,
  exportToFile,
  exportToBuffer,
  BufferSerializer,
  FileSerializer,
  lastError,
} from "../src/serializers/Serializer.js";
import type { SerializerFormat } from "../src/serializers/Serializer.js";
import type { EmscriptenModule } from "../src/wasm/types.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const WASM_DIR = join(__dirname, "../../../zig-out");
const TEST_IFC = join(__dirname, "data/basic_shape_SweptSolid.ifc");

let M: EmscriptenModule;
let IFC_CONTENT: string;

beforeAll(async () => {
  const require = createRequire(import.meta.url);
  const mod = require(join(WASM_DIR, "ifcopenshell.js"));
  const createModule = mod.default || mod;
  M = await createModule({
    locateFile: (file: string) => join(WASM_DIR, file),
  });
  setModule(M);
  IFC_CONTENT = readFileSync(TEST_IFC, "utf-8");
});

describe("SerializerSettings", () => {
  let settings: SerializerSettings;

  beforeAll(() => {
    settings = new SerializerSettings();
  });

  afterAll(() => {
    settings.destroy();
  });

  it("creates settings with valid pointer", () => {
    expect(settings.ptr).toBeGreaterThan(0);
  });

  it("settingNames returns available setting names", () => {
    const names = settings.settingNames();
    expect(names.length).toBeGreaterThan(0);
    expect(names).toContain("use-element-guids");
  });

  it("setBool sets a boolean setting", () => {
    const ok = settings.setBool("use-element-guids", true);
    expect(ok).toBe(true);
  });

  it("setBool rejects unknown setting name", () => {
    const ok = settings.setBool("nonexistent-setting", true);
    expect(ok).toBe(false);
  });

  it("setInt sets an integer setting", () => {
    const ok = settings.setInt("digits", 8);
    expect(ok).toBe(true);
  });

  it("setString sets a string setting", () => {
    const ok = settings.setString("base-uri", "http://example.com/");
    expect(ok).toBe(true);
  });
});

describe("hasFormat", () => {
  it("reports OBJ as always available", () => {
    expect(hasFormat("obj")).toBe(true);
  });

  it("reports XML as always available", () => {
    expect(hasFormat("xml")).toBe(true);
  });

  it("reports GLTF availability", () => {
    const available = hasFormat("gltf");
    expect(typeof available).toBe("boolean");
  });

  it("reports JSON availability", () => {
    const available = hasFormat("json");
    expect(typeof available).toBe("boolean");
  });

  it("reports SVG availability", () => {
    const available = hasFormat("svg");
    expect(typeof available).toBe("boolean");
  });
});

describe("exportToFile", () => {
  let file: IfcFile;
  let geomSettings: GeomSettings;
  let serSettings: SerializerSettings;

  beforeAll(() => {
    file = IfcFile.openFromMemory(IFC_CONTENT)!;
    geomSettings = new GeomSettings();
    serSettings = new SerializerSettings();
  });

  afterAll(() => {
    serSettings.destroy();
    geomSettings.destroy();
    file.close();
  });

  it("exports to OBJ format", () => {
    const ok = exportToFile(
      file.ptr,
      geomSettings.ptr,
      serSettings.ptr,
      "obj",
      "/tmp/export.obj",
    );
    expect(ok).toBe(true);
    const content = M.FS.readFile("/tmp/export.obj", { encoding: "utf8" }) as string;
    expect(content.length).toBeGreaterThan(0);
    expect(content).toContain("# File generated by IfcOpenShell");
    expect(content).toContain("v ");
    expect(content).toContain("f ");
    M.FS.unlink("/tmp/export.obj");
    M.FS.unlink("/tmp/export.mtl");
  });

  it("exports to XML format", () => {
    const ok = exportToFile(
      file.ptr,
      geomSettings.ptr,
      serSettings.ptr,
      "xml",
      "/tmp/export.xml",
    );
    expect(ok).toBe(true);
    const content = M.FS.readFile("/tmp/export.xml", { encoding: "utf8" }) as string;
    expect(content.length).toBeGreaterThan(0);
    expect(content).toContain("<?xml");
    expect(content).toContain("<ifc");
    M.FS.unlink("/tmp/export.xml");
  });

  it("exports to JSON format", () => {
    if (!hasFormat("json")) return;
    const ok = exportToFile(
      file.ptr,
      geomSettings.ptr,
      serSettings.ptr,
      "json",
      "/tmp/export.json",
    );
    expect(ok).toBe(true);
    const content = M.FS.readFile("/tmp/export.json", { encoding: "utf8" }) as string;
    expect(content.length).toBeGreaterThan(0);
    const parsed = JSON.parse(content);
    expect(parsed).toBeTruthy();
    M.FS.unlink("/tmp/export.json");
  });

  it("exports to GLTF format", () => {
    if (!hasFormat("gltf")) return;
    const ok = exportToFile(
      file.ptr,
      geomSettings.ptr,
      serSettings.ptr,
      "gltf",
      "/tmp/export.gltf",
    );
    expect(ok).toBe(true);
    M.FS.unlink("/tmp/export.gltf");
  });
});

describe("OBJ export content", () => {
  it("contains geometry matching the IFC model", () => {
    const file = IfcFile.openFromMemory(IFC_CONTENT)!;
    const gs = new GeomSettings();
    const ss = new SerializerSettings();

    const ok = exportToFile(file.ptr, gs.ptr, ss.ptr, "obj", "/tmp/content.obj");
    expect(ok).toBe(true);

    const obj = M.FS.readFile("/tmp/content.obj", { encoding: "utf8" }) as string;
    const vertexLines = obj.split("\n").filter((l: string) => l.startsWith("v "));
    const faceLines = obj.split("\n").filter((l: string) => l.startsWith("f "));
    expect(vertexLines.length).toBeGreaterThan(0);
    expect(faceLines.length).toBeGreaterThan(0);

    M.FS.unlink("/tmp/content.obj");
    M.FS.unlink("/tmp/content.mtl");
    ss.destroy();
    gs.destroy();
    file.close();
  });
});

describe("XML export content", () => {
  it("contains entity data from the IFC model", () => {
    const file = IfcFile.openFromMemory(IFC_CONTENT)!;
    const gs = new GeomSettings();
    const ss = new SerializerSettings();

    const ok = exportToFile(file.ptr, gs.ptr, ss.ptr, "xml", "/tmp/content.xml");
    expect(ok).toBe(true);

    const xml = M.FS.readFile("/tmp/content.xml", { encoding: "utf8" }) as string;
    expect(xml).toContain("IfcProject");
    expect(xml).toContain("proxy with swept solid");

    M.FS.unlink("/tmp/content.xml");
    ss.destroy();
    gs.destroy();
    file.close();
  });
});

describe("lastError", () => {
  it("returns empty string when no error", () => {
    const err = lastError();
    expect(typeof err).toBe("string");
  });
});

describe("settings with export", () => {
  it("use-element-guids affects OBJ group names", () => {
    const file = IfcFile.openFromMemory(IFC_CONTENT)!;
    const gs = new GeomSettings();

    const ssDefault = new SerializerSettings();
    exportToFile(file.ptr, gs.ptr, ssDefault.ptr, "obj", "/tmp/default.obj");
    const defaultObj = M.FS.readFile("/tmp/default.obj", { encoding: "utf8" }) as string;
    ssDefault.destroy();

    const ssGuids = new SerializerSettings();
    ssGuids.setBool("use-element-guids", true);
    exportToFile(file.ptr, gs.ptr, ssGuids.ptr, "obj", "/tmp/guids.obj");
    const guidsObj = M.FS.readFile("/tmp/guids.obj", { encoding: "utf8" }) as string;
    ssGuids.destroy();

    // Both should have valid OBJ content
    expect(defaultObj).toContain("v ");
    expect(guidsObj).toContain("v ");

    // Group names should differ
    const defaultGroups = defaultObj.split("\n").filter((l: string) => l.startsWith("g "));
    const guidGroups = guidsObj.split("\n").filter((l: string) => l.startsWith("g "));
    expect(defaultGroups.length).toBe(guidGroups.length);
    expect(defaultGroups[0]).not.toBe(guidGroups[0]);

    M.FS.unlink("/tmp/default.obj");
    M.FS.unlink("/tmp/default.mtl");
    M.FS.unlink("/tmp/guids.obj");
    M.FS.unlink("/tmp/guids.mtl");
    gs.destroy();
    file.close();
  });
});

describe("SerializerSettings getters", () => {
  it("getBool returns a boolean value after setting", () => {
    const ss = new SerializerSettings();
    ss.setBool("use-element-guids", true);
    expect(ss.getBool("use-element-guids")).toBe(true);
    ss.setBool("use-element-guids", false);
    expect(ss.getBool("use-element-guids")).toBe(false);
    ss.destroy();
  });

  it("getInt returns an int value after setting", () => {
    const ss = new SerializerSettings();
    ss.setInt("digits", 10);
    expect(ss.getInt("digits")).toBe(10);
    ss.destroy();
  });

  it("getType returns the type of a setting", () => {
    const ss = new SerializerSettings();
    const type = ss.getType("use-element-guids");
    expect(type).toBeTruthy();
    ss.destroy();
  });

  it("lastError returns a string", () => {
    const ss = new SerializerSettings();
    expect(typeof ss.lastError).toBe("string");
    ss.destroy();
  });
});

describe("Buffer-based export", () => {
  it("exportToBuffer returns OBJ content as strings", () => {
    const file = IfcFile.openFromMemory(IFC_CONTENT);
    const gs = new GeomSettings();
    const ss = new SerializerSettings();
    const result = exportToBuffer(file.ptr, gs.ptr, ss.ptr, "obj");
    expect(result).not.toBeNull();
    expect(result!.primary).toContain("v ");
    expect(result!.primary).toContain("f ");
    ss.destroy();
    gs.destroy();
    file.close();
  });

  it("BufferSerializer lifecycle works for OBJ", () => {
    const file = IfcFile.openFromMemory(IFC_CONTENT);
    const gs = new GeomSettings();
    const ss = new SerializerSettings();
    const ser = BufferSerializer.create(gs.ptr, ss.ptr, "obj");
    expect(ser.ready).toBe(true);
    const ok = ser.run(file.ptr);
    expect(ok).toBe(true);
    const objContent = ser.primaryBuffer;
    expect(objContent).toContain("v ");
    expect(typeof ser.lastError).toBe("string");
    ser.destroy();
    ss.destroy();
    gs.destroy();
    file.close();
  });
});

describe("FileSerializer", () => {
  it("lifecycle works for OBJ file serializer", () => {
    const file = IfcFile.openFromMemory(IFC_CONTENT);
    const gs = new GeomSettings();
    const ss = new SerializerSettings();
    const ser = FileSerializer.create(gs.ptr, ss.ptr, "obj", "/tmp/fs.obj");

    expect(ser.ready).toBe(true);
    const ok = ser.run(file.ptr);
    expect(ok).toBe(true);
    expect(typeof ser.lastError).toBe("string");

    const objContent = M.FS.readFile("/tmp/fs.obj", { encoding: "utf8" }) as string;
    expect(objContent).toContain("v ");

    M.FS.unlink("/tmp/fs.obj");
    M.FS.unlink("/tmp/fs.mtl");
    ser.destroy();
    ss.destroy();
    gs.destroy();
    file.close();
  });
});
