# SPDX-License-Identifier: LGPL-3.0-or-later
# This file was generated with the assistance of an AI coding tool.
"""``ifcopenshell.geom`` - Pythonic geometry API over the autogenerated
``ifcopenshell_ifcgeom_*`` C ABI.

Mirrors the public surface of upstream :mod:`ifcopenshell.geom` so existing
tests, examples, and downstream consumers can switch to the new backend
without source changes.
"""

from __future__ import annotations

from .main import has_occ  # noqa: F401  - established before re-export


if has_occ:
    try:
        from . import occ_utils as utils  # type: ignore[import-not-found]  # noqa: F401
    except Exception:  # pragma: no cover - OCC bridge wired in y6g
        pass


from .main import *  # noqa: F401,F403,E402
