# SPDX-License-Identifier: LGPL-3.0-or-later
# This file was generated with the assistance of an AI coding tool.
"""ctypes bindings for the autogenerated ``ifcopenshell_ifcgeom_*`` C ABI.

All function signatures are bound lazily on first use via :func:`bind`.
The accompanying ``main.py`` builds the high-level Pythonic ``geom`` API
on top of these primitives. No SWIG/legacy ``ifcopenshell_wrapper``
imports - this module is the single integration point against the new
autogenerated C library.
"""

from __future__ import annotations

import ctypes
from ctypes import (
    POINTER,
    Structure,
    byref,
    c_bool,
    c_char_p,
    c_double,
    c_int32,
    c_size_t,
    c_void_p,
)

import ifcopenshell


# ---------------------------------------------------------------------------
# Shared C value-type structs.
#
# We re-use the struct definitions from :mod:`ifcopenshell_wrapper` so the
# argtypes for shared symbols (``ifcopenshell_string_destroy`` etc.) remain
# compatible across both modules. Re-defining the same C struct with a
# different Python class would silently corrupt argtype validation for
# the legacy wrapper since ``ctypes`` checks pointer types by Python class
# identity, not C layout.
# ---------------------------------------------------------------------------

from ifcopenshell.ifcopenshell_wrapper import (  # noqa: E402
    _HandleStruct,
    ifcopenshell_string_list_t,
    ifcopenshell_string_t,
)


class ifcopenshell_int32_list_t(Structure):
    _fields_ = [("items", POINTER(c_int32)), ("size", c_size_t)]


class ifcopenshell_int32_list_list_t(Structure):
    _fields_ = [("items", POINTER(ifcopenshell_int32_list_t)), ("size", c_size_t)]


class ifcopenshell_int32_list_list_list_t(Structure):
    _fields_ = [("items", POINTER(ifcopenshell_int32_list_list_t)), ("size", c_size_t)]


class ifcopenshell_double_list_t(Structure):
    _fields_ = [("items", POINTER(c_double)), ("size", c_size_t)]


HandleP = POINTER(_HandleStruct)
HandlePP = POINTER(HandleP)


def _handle_list_type(name: str):
    return type(
        name,
        (Structure,),
        {"_fields_": [("items", POINTER(HandleP)), ("size", c_size_t)]},
    )


ifcopenshell_ifcgeom_taxonomy_style_list_t = _handle_list_type(
    "ifcopenshell_ifcgeom_taxonomy_style_list_t"
)
ifcopenshell_ifcgeom_element_list_t = _handle_list_type(
    "ifcopenshell_ifcgeom_element_list_t"
)
ifcopenshell_ifc_instance_list_t = _handle_list_type(
    "ifcopenshell_ifc_instance_list_t"
)


# ---------------------------------------------------------------------------
# Lazy signature binding.
# ---------------------------------------------------------------------------

_bound = False


def bind():
    global _bound
    lib = ifcopenshell._get_lib()
    if _bound:
        return lib

    Sp = POINTER(ifcopenshell_string_t)
    SLp = POINTER(ifcopenshell_string_list_t)
    Ip = POINTER(ifcopenshell_int32_list_t)
    Ipp = POINTER(ifcopenshell_int32_list_list_t)
    Dp = POINTER(ifcopenshell_double_list_t)
    StyleListP = POINTER(ifcopenshell_ifcgeom_taxonomy_style_list_t)
    ElementListP = POINTER(ifcopenshell_ifcgeom_element_list_t)

    Ippp = POINTER(ifcopenshell_int32_list_list_list_t)

    sigs = {
        "ifcopenshell_string_destroy": (None, [Sp]),
        "ifcopenshell_string_list_destroy": (None, [SLp]),
        "ifcopenshell_int32_list_destroy": (None, [Ip]),
        "ifcopenshell_int32_list_list_destroy": (None, [Ipp]),
        "ifcopenshell_int32_list_list_list_destroy": (None, [Ippp]),
        "ifcopenshell_double_list_destroy": (None, [Dp]),
        "ifcopenshell_ifcgeom_settings_destroy": (None, [HandleP]),
        "ifcopenshell_ifcgeom_serializer_settings_destroy": (None, [HandleP]),
        "ifcopenshell_ifcgeom_element_destroy": (None, [HandleP]),
        "ifcopenshell_ifcgeom_brep_element_destroy": (None, [HandleP]),
        "ifcopenshell_ifcgeom_triangulation_element_destroy": (None, [HandleP]),
        "ifcopenshell_ifcgeom_serialized_element_destroy": (None, [HandleP]),
        "ifcopenshell_ifcgeom_triangulation_destroy": (None, [HandleP]),
        "ifcopenshell_ifcgeom_brep_representation_destroy": (None, [HandleP]),
        "ifcopenshell_ifcgeom_serialization_destroy": (None, [HandleP]),
        "ifcopenshell_ifcgeom_iterator_destroy": (None, [HandleP]),
        "ifcopenshell_ifcgeom_tree_destroy": (None, [HandleP]),
        "ifcopenshell_ifcgeom_geometry_serializer_destroy": (None, [HandleP]),
        "ifcopenshell_ifcgeom_taxonomy_style_destroy": (None, [HandleP]),
        "ifcopenshell_ifcgeom_taxonomy_colour_destroy": (None, [HandleP]),
        "ifcopenshell_ifcgeom_taxonomy_item_destroy": (None, [HandleP]),
        "ifcopenshell_ifcgeom_function_item_evaluator_destroy": (None, [HandleP]),
        "ifcopenshell_ifcgeom_transformation_destroy": (None, [HandleP]),
        "ifcopenshell_ifcgeom_taxonomy_style_list_destroy": (None, [StyleListP]),
        "ifcopenshell_ifcgeom_element_list_destroy": (None, [ElementListP]),
        # ----- element accessors --------------------------------------
        "ifcopenshell_ifcgeom_element_context": (c_bool, [HandleP, Sp]),
        "ifcopenshell_ifcgeom_element_guid": (c_bool, [HandleP, Sp]),
        "ifcopenshell_ifcgeom_element_id": (c_bool, [HandleP, POINTER(c_int32)]),
        "ifcopenshell_ifcgeom_element_name": (c_bool, [HandleP, Sp]),
        "ifcopenshell_ifcgeom_element_parent_id": (c_bool, [HandleP, POINTER(c_int32)]),
        "ifcopenshell_ifcgeom_element_parents": (c_bool, [HandleP, ElementListP]),
        "ifcopenshell_ifcgeom_element_product": (c_bool, [HandleP, POINTER(HandleP)]),
        "ifcopenshell_ifcgeom_element_transformation": (c_bool, [HandleP, POINTER(HandleP)]),
        "ifcopenshell_ifcgeom_element_type": (c_bool, [HandleP, Sp]),
        "ifcopenshell_ifcgeom_element_unique_id": (c_bool, [HandleP, Sp]),
        "ifcopenshell_ifcgeom_element_transformation_buffer": (
            c_bool, [HandleP, POINTER(POINTER(c_double))],
        ),
        "ifcopenshell_ifcgeom_element_transformation_buffer_size": (
            c_bool, [HandleP, POINTER(c_size_t)],
        ),
        # ----- typed element variants ---------------------------------
        "ifcopenshell_ifcgeom_brep_element_geometry": (
            c_bool, [HandleP, POINTER(HandleP)],
        ),
        "ifcopenshell_ifcgeom_brep_element_calculate_projected_surface_area": (
            c_bool, [HandleP, c_double, c_double, c_double, POINTER(c_bool)],
        ),
        "ifcopenshell_ifcgeom_brep_element_calc_volume": (
            c_bool, [HandleP, POINTER(c_double)],
        ),
        "ifcopenshell_ifcgeom_brep_element_calc_surface_area": (
            c_bool, [HandleP, POINTER(c_double)],
        ),
        "ifcopenshell_ifcgeom_triangulation_element_geometry": (
            c_bool, [HandleP, POINTER(HandleP)],
        ),
        "ifcopenshell_ifcgeom_serialized_element_geometry": (
            c_bool, [HandleP, POINTER(HandleP)],
        ),
        # ----- triangulation accessors --------------------------------
        "ifcopenshell_ifcgeom_triangulation_verts": (c_bool, [HandleP, Dp]),
        "ifcopenshell_ifcgeom_triangulation_faces": (c_bool, [HandleP, Ip]),
        "ifcopenshell_ifcgeom_triangulation_normals": (c_bool, [HandleP, Dp]),
        "ifcopenshell_ifcgeom_triangulation_edges": (c_bool, [HandleP, Ip]),
        "ifcopenshell_ifcgeom_triangulation_edges_item_ids": (c_bool, [HandleP, Ip]),
        "ifcopenshell_ifcgeom_triangulation_uvs": (c_bool, [HandleP, Dp]),
        "ifcopenshell_ifcgeom_triangulation_material_ids": (c_bool, [HandleP, Ip]),
        "ifcopenshell_ifcgeom_triangulation_item_ids": (c_bool, [HandleP, Ip]),
        "ifcopenshell_ifcgeom_triangulation_materials": (c_bool, [HandleP, StyleListP]),
        "ifcopenshell_ifcgeom_triangulation_polyhedral_faces_with_holes": (
            c_bool, [HandleP, Ippp],
        ),
        "ifcopenshell_ifcgeom_triangulation_polyhedral_faces_without_holes": (
            c_bool, [HandleP, Ipp],
        ),
        "ifcopenshell_ifcgeom_triangulation_verts_buffer_size": (
            c_bool, [HandleP, POINTER(c_size_t)],
        ),
        "ifcopenshell_ifcgeom_triangulation_faces_buffer_size": (
            c_bool, [HandleP, POINTER(c_size_t)],
        ),
        "ifcopenshell_ifcgeom_triangulation_normals_buffer_size": (
            c_bool, [HandleP, POINTER(c_size_t)],
        ),
        "ifcopenshell_ifcgeom_triangulation_edges_buffer_size": (
            c_bool, [HandleP, POINTER(c_size_t)],
        ),
        "ifcopenshell_ifcgeom_triangulation_material_ids_buffer_size": (
            c_bool, [HandleP, POINTER(c_size_t)],
        ),
        "ifcopenshell_ifcgeom_triangulation_item_ids_buffer_size": (
            c_bool, [HandleP, POINTER(c_size_t)],
        ),
        "ifcopenshell_ifcgeom_triangulation_uvs_buffer_size": (
            c_bool, [HandleP, POINTER(c_size_t)],
        ),
        "ifcopenshell_ifcgeom_triangulation_edges_item_ids_buffer_size": (
            c_bool, [HandleP, POINTER(c_size_t)],
        ),
        "ifcopenshell_ifcgeom_triangulation_material_count": (
            c_bool, [HandleP, POINTER(c_size_t)],
        ),
        "ifcopenshell_ifcgeom_triangulation_material_at": (
            c_bool, [HandleP, c_size_t, POINTER(HandleP)],
        ),
        "ifcopenshell_ifcgeom_triangulation_verts_buffer": (
            c_bool, [HandleP, POINTER(POINTER(c_double))],
        ),
        "ifcopenshell_ifcgeom_triangulation_faces_buffer": (
            c_bool, [HandleP, POINTER(POINTER(c_int32))],
        ),
        "ifcopenshell_ifcgeom_triangulation_normals_buffer": (
            c_bool, [HandleP, POINTER(POINTER(c_double))],
        ),
        "ifcopenshell_ifcgeom_triangulation_edges_buffer": (
            c_bool, [HandleP, POINTER(POINTER(c_int32))],
        ),
        "ifcopenshell_ifcgeom_triangulation_material_ids_buffer": (
            c_bool, [HandleP, POINTER(POINTER(c_int32))],
        ),
        "ifcopenshell_ifcgeom_triangulation_item_ids_buffer": (
            c_bool, [HandleP, POINTER(POINTER(c_int32))],
        ),
        "ifcopenshell_ifcgeom_triangulation_edges_item_ids_buffer": (
            c_bool, [HandleP, POINTER(POINTER(c_int32))],
        ),
        "ifcopenshell_ifcgeom_triangulation_uvs_buffer": (
            c_bool, [HandleP, POINTER(POINTER(c_double))],
        ),
        "ifcopenshell_ifcgeom_triangulation_colors_buffer_size": (
            c_bool, [HandleP, POINTER(c_size_t)],
        ),
        "ifcopenshell_ifcgeom_triangulation_colors_buffer": (c_bool, [HandleP, Dp]),
        # ----- brep representation ------------------------------------
        "ifcopenshell_ifcgeom_brep_representation_entity": (c_bool, [HandleP, Sp]),
        "ifcopenshell_ifcgeom_brep_representation_id": (c_bool, [HandleP, Sp]),
        "ifcopenshell_ifcgeom_brep_representation_size": (
            c_bool, [HandleP, POINTER(c_int32)],
        ),
        "ifcopenshell_ifcgeom_brep_representation_item_id": (
            c_bool, [HandleP, c_int32, POINTER(c_int32)],
        ),
        "ifcopenshell_ifcgeom_brep_representation_settings": (
            c_bool, [HandleP, POINTER(HandleP)],
        ),
        "ifcopenshell_ifcgeom_brep_representation_calculate_volume": (
            c_bool, [HandleP, POINTER(c_double)],
        ),
        "ifcopenshell_ifcgeom_brep_representation_calculate_surface_area": (
            c_bool, [HandleP, POINTER(c_double)],
        ),
        # ----- serialization (BRep STEP-string) -----------------------
        "ifcopenshell_ifcgeom_serialization_brep_data": (c_bool, [HandleP, Sp]),
        "ifcopenshell_ifcgeom_serialization_surface_style_ids": (c_bool, [HandleP, Ip]),
        "ifcopenshell_ifcgeom_serialization_surface_styles": (c_bool, [HandleP, Dp]),
        # ----- transformation -----------------------------------------
        "ifcopenshell_ifcgeom_transformation_matrix": (c_bool, [HandleP, Dp]),
        # ----- taxonomy style/colour ----------------------------------
        "ifcopenshell_ifcgeom_taxonomy_style_name": (c_bool, [HandleP, Sp]),
        "ifcopenshell_ifcgeom_taxonomy_style_has_specularity": (
            c_bool, [HandleP, POINTER(c_bool)],
        ),
        "ifcopenshell_ifcgeom_taxonomy_style_has_transparency": (
            c_bool, [HandleP, POINTER(c_bool)],
        ),
        "ifcopenshell_ifcgeom_taxonomy_style_specularity": (
            c_bool, [HandleP, POINTER(c_double)],
        ),
        "ifcopenshell_ifcgeom_taxonomy_style_transparency": (
            c_bool, [HandleP, POINTER(c_double)],
        ),
        "ifcopenshell_ifcgeom_taxonomy_style_use_surface_color": (
            c_bool, [HandleP, POINTER(c_bool)],
        ),
        "ifcopenshell_ifcgeom_taxonomy_style_diffuse": (
            c_bool, [HandleP, POINTER(HandleP)],
        ),
        "ifcopenshell_ifcgeom_taxonomy_style_specular": (
            c_bool, [HandleP, POINTER(HandleP)],
        ),
        "ifcopenshell_ifcgeom_taxonomy_style_surface": (
            c_bool, [HandleP, POINTER(HandleP)],
        ),
        "ifcopenshell_ifcgeom_taxonomy_style_instance_id": (
            c_bool, [HandleP, POINTER(c_size_t)],
        ),
        "ifcopenshell_ifcgeom_taxonomy_colour_get_data": (c_bool, [HandleP, Dp]),
        # NOTE: ``ifcopenshell_ifc_instance_*`` functions are bound globally
        # by ``ifcopenshell.__init__`` against ``c_void_p`` signatures.
        # Re-binding them here would silently mutate the shared ``ctypes``
        # argtypes and corrupt every other caller in the package.
        "ifcopenshell_ifcgeom_create_settings": (c_bool, [HandlePP]),
        "ifcopenshell_ifcgeom_create_serializer_settings": (c_bool, [HandlePP]),
        # ``create_shape`` / ``map_shape`` take raw instance handles
        # (``ifcopenshell_ifc_instance_t*``); the entity_instance side stores
        # those as plain ``int``/``c_void_p`` values, so we declare them as
        # ``c_void_p`` to stay compatible with the legacy signatures.
        "ifcopenshell_ifcgeom_create_shape": (
            c_bool,
            [HandleP, c_void_p, c_void_p, c_char_p, HandlePP],
        ),
        "ifcopenshell_ifcgeom_map_shape": (
            c_bool, [HandleP, c_void_p, HandlePP],
        ),
        "ifcopenshell_ifcgeom_create_function_item_evaluator": (
            c_bool, [HandleP, HandleP, HandlePP],
        ),
        "ifcopenshell_ifcgeom_convert_loop_to_function_item": (
            c_bool, [HandleP, HandlePP],
        ),
        "ifcopenshell_ifcgeom_helmert_curve_point": (
            c_bool, [c_double, c_double, c_double, c_double, Dp],
        ),
        "ifcopenshell_ifcgeom_function_item_evaluator_evaluate_at": (
            c_bool, [HandleP, c_double, Dp],
        ),
        "ifcopenshell_taxonomy_function_item_start": (
            c_bool, [HandleP, POINTER(c_double)],
        ),
        "ifcopenshell_taxonomy_function_item_end": (
            c_bool, [HandleP, POINTER(c_double)],
        ),
        "ifcopenshell_ifcgeom_settings_get_type": (c_bool, [HandleP, c_char_p, Sp]),
        "ifcopenshell_ifcgeom_settings_setting_names": (c_bool, [HandleP, SLp]),
        "ifcopenshell_ifcgeom_settings_get_bool": (
            c_bool, [HandleP, c_char_p, POINTER(c_bool)],
        ),
        "ifcopenshell_ifcgeom_settings_set_bool": (
            c_bool, [HandleP, c_char_p, c_bool],
        ),
        "ifcopenshell_ifcgeom_settings_get_int": (
            c_bool, [HandleP, c_char_p, POINTER(c_int32)],
        ),
        "ifcopenshell_ifcgeom_settings_set_int": (
            c_bool, [HandleP, c_char_p, c_int32],
        ),
        "ifcopenshell_ifcgeom_settings_get_double": (
            c_bool, [HandleP, c_char_p, POINTER(c_double)],
        ),
        "ifcopenshell_ifcgeom_settings_set_double": (
            c_bool, [HandleP, c_char_p, c_double],
        ),
        "ifcopenshell_ifcgeom_settings_get_string": (
            c_bool, [HandleP, c_char_p, Sp],
        ),
        "ifcopenshell_ifcgeom_settings_set_string": (
            c_bool, [HandleP, c_char_p, c_char_p],
        ),
        "ifcopenshell_ifcgeom_settings_get_int_set": (c_bool, [HandleP, c_char_p, Ip]),
        "ifcopenshell_ifcgeom_settings_set_int_set": (c_bool, [HandleP, c_char_p, Ip]),
        "ifcopenshell_ifcgeom_settings_get_string_set": (
            c_bool, [HandleP, c_char_p, SLp],
        ),
        "ifcopenshell_ifcgeom_settings_set_string_set": (
            c_bool, [HandleP, c_char_p, SLp],
        ),
        "ifcopenshell_ifcgeom_settings_get_double_list": (
            c_bool, [HandleP, c_char_p, Dp],
        ),
        "ifcopenshell_ifcgeom_settings_set_double_list": (
            c_bool, [HandleP, c_char_p, Dp],
        ),
        "ifcopenshell_ifcgeom_serializer_settings_get_type": (
            c_bool, [HandleP, c_char_p, Sp],
        ),
        "ifcopenshell_ifcgeom_serializer_settings_setting_names": (
            c_bool, [HandleP, SLp],
        ),
        "ifcopenshell_ifcgeom_serializer_settings_get_bool": (
            c_bool, [HandleP, c_char_p, POINTER(c_bool)],
        ),
        "ifcopenshell_ifcgeom_serializer_settings_set_bool": (
            c_bool, [HandleP, c_char_p, c_bool],
        ),
        "ifcopenshell_ifcgeom_serializer_settings_get_int": (
            c_bool, [HandleP, c_char_p, POINTER(c_int32)],
        ),
        "ifcopenshell_ifcgeom_serializer_settings_set_int": (
            c_bool, [HandleP, c_char_p, c_int32],
        ),
        "ifcopenshell_ifcgeom_serializer_settings_get_double": (
            c_bool, [HandleP, c_char_p, POINTER(c_double)],
        ),
        "ifcopenshell_ifcgeom_serializer_settings_set_double": (
            c_bool, [HandleP, c_char_p, c_double],
        ),
        "ifcopenshell_ifcgeom_serializer_settings_get_string": (
            c_bool, [HandleP, c_char_p, Sp],
        ),
        "ifcopenshell_ifcgeom_serializer_settings_set_string": (
            c_bool, [HandleP, c_char_p, c_char_p],
        ),
        "ifcopenshell_ifcgeom_serializer_settings_get_int_set": (
            c_bool, [HandleP, c_char_p, Ip],
        ),
        "ifcopenshell_ifcgeom_serializer_settings_set_int_set": (
            c_bool, [HandleP, c_char_p, Ip],
        ),
        # ----- iterator -----------------------------------------------
        "ifcopenshell_ifcgeom_iterator_destroy": (None, [HandleP]),
        "ifcopenshell_ifcgeom_create_iterator": (
            c_bool,
            [c_char_p, HandleP, c_void_p, c_int32, HandlePP],
        ),
        "ifcopenshell_ifcgeom_create_iterator_with_include_exclude": (
            c_bool,
            [
                c_char_p, HandleP, c_void_p,
                POINTER(ifcopenshell_string_list_t), c_bool, c_int32, HandlePP,
            ],
        ),
        "ifcopenshell_ifcgeom_create_iterator_with_include_exclude_globalid": (
            c_bool,
            [
                c_char_p, HandleP, c_void_p,
                POINTER(ifcopenshell_string_list_t), c_bool, c_int32, HandlePP,
            ],
        ),
        "ifcopenshell_ifcgeom_create_iterator_with_include_exclude_id": (
            c_bool,
            [
                c_char_p, HandleP, c_void_p,
                POINTER(ifcopenshell_int32_list_t), c_bool, c_int32, HandlePP,
            ],
        ),
        "ifcopenshell_ifcgeom_iterator_initialize": (
            c_bool, [HandleP, POINTER(c_bool)],
        ),
        "ifcopenshell_ifcgeom_iterator_next": (
            c_bool, [HandleP, POINTER(c_bool)],
        ),
        "ifcopenshell_ifcgeom_iterator_get": (
            c_bool, [HandleP, HandlePP],
        ),
        "ifcopenshell_ifcgeom_iterator_get_native": (
            c_bool, [HandleP, HandlePP],
        ),
        "ifcopenshell_ifcgeom_iterator_get_object": (
            c_bool, [HandleP, c_int32, HandlePP],
        ),
        "ifcopenshell_ifcgeom_iterator_get_as_triangulation_element": (
            c_bool, [HandleP, HandlePP],
        ),
        "ifcopenshell_ifcgeom_iterator_get_as_brep_element": (
            c_bool, [HandleP, HandlePP],
        ),
        "ifcopenshell_ifcgeom_iterator_get_as_serialized_element": (
            c_bool, [HandleP, HandlePP],
        ),
        "ifcopenshell_ifcgeom_iterator_progress": (
            c_bool, [HandleP, POINTER(c_int32)],
        ),
        "ifcopenshell_ifcgeom_iterator_compute_bounds": (
            c_bool, [HandleP, c_bool],
        ),
        "ifcopenshell_ifcgeom_iterator_unit_magnitude": (
            c_bool, [HandleP, POINTER(c_double)],
        ),
        "ifcopenshell_ifcgeom_iterator_unit_name": (
            c_bool, [HandleP, Sp],
        ),
        "ifcopenshell_ifcgeom_iterator_get_log": (
            c_bool, [HandleP, Sp],
        ),
        "ifcopenshell_ifcgeom_iterator_had_error_processing_elements": (
            c_bool, [HandleP, POINTER(c_bool)],
        ),
        # ----- ifcparse instance list (used as tree return type) ------
        "ifcopenshell_ifcparse_instance_list_create_from_handles": (
            c_bool,
            [POINTER(ifcopenshell_ifc_instance_list_t), HandlePP],
        ),
        "ifcopenshell_ifcparse_instance_list_destroy": (None, [HandleP]),
        "ifcopenshell_ifcparse_instance_list_size": (
            c_bool, [HandleP, POINTER(c_size_t)],
        ),
        "ifcopenshell_ifcparse_instance_list_get": (
            c_bool, [HandleP, c_size_t, HandlePP],
        ),
        # ----- tree ---------------------------------------------------
        "ifcopenshell_ifcgeom_tree_destroy": (None, [HandleP]),
        "ifcopenshell_ifcgeom_create_tree": (c_bool, [HandlePP]),
        "ifcopenshell_ifcgeom_create_tree_from_file": (
            c_bool, [c_void_p, HandlePP],
        ),
        "ifcopenshell_ifcgeom_create_tree_from_file_with_settings": (
            c_bool, [c_void_p, HandleP, HandlePP],
        ),
        "ifcopenshell_ifcgeom_create_tree_from_iterator": (
            c_bool, [HandleP, HandlePP],
        ),
        "ifcopenshell_ifcgeom_tree_add_file": (
            c_bool, [HandleP, c_void_p, HandleP],
        ),
        "ifcopenshell_ifcgeom_tree_add_iterator": (
            c_bool, [HandleP, HandleP],
        ),
        "ifcopenshell_ifcgeom_tree_enable_face_styles": (
            c_bool, [HandleP, POINTER(c_bool)],
        ),
        "ifcopenshell_ifcgeom_tree_set_enable_face_styles": (
            c_bool, [HandleP, c_bool],
        ),
        "ifcopenshell_ifcgeom_tree_select_element": (
            c_bool, [HandleP, c_void_p, c_bool, c_double, HandlePP],
        ),
        "ifcopenshell_ifcgeom_tree_select_point": (
            c_bool, [HandleP, c_double, c_double, c_double, c_double, HandlePP],
        ),
        "ifcopenshell_ifcgeom_tree_select_box_element": (
            c_bool, [HandleP, c_void_p, c_bool, c_double, HandlePP],
        ),
        "ifcopenshell_ifcgeom_tree_select_box_point": (
            c_bool, [HandleP, c_double, c_double, c_double, c_double, HandlePP],
        ),
        "ifcopenshell_ifcgeom_tree_select_box_bounds": (
            c_bool,
            [
                HandleP, c_double, c_double, c_double,
                c_double, c_double, c_double, c_bool, HandlePP,
            ],
        ),
        "ifcopenshell_ifcgeom_tree_select_ray": (
            c_bool,
            [
                HandleP, c_double, c_double, c_double,
                c_double, c_double, c_double, c_double, HandlePP,
            ],
        ),
        "ifcopenshell_ifcgeom_tree_clash_intersection_many": (
            c_bool,
            [HandleP, HandleP, HandleP, c_double, c_bool, HandlePP],
        ),
        "ifcopenshell_ifcgeom_tree_clash_collision_many": (
            c_bool,
            [HandleP, HandleP, HandleP, c_bool, HandlePP],
        ),
        "ifcopenshell_ifcgeom_tree_clash_clearance_many": (
            c_bool,
            [HandleP, HandleP, HandleP, c_double, c_bool, HandlePP],
        ),
        "ifcopenshell_ifcgeom_tree_clash_count": (
            c_bool, [HandleP, HandleP, POINTER(c_size_t)],
        ),
        "ifcopenshell_ifcgeom_tree_clash_at": (
            c_bool, [HandleP, HandleP, c_size_t, HandlePP],
        ),
        "ifcopenshell_ifcgeom_tree_clash_list_destroy": (None, [HandleP]),
        "ifcopenshell_ifcgeom_tree_clash_destroy": (None, [HandleP]),
        "ifcopenshell_ifcgeom_tree_clash_a": (c_bool, [HandleP, HandlePP]),
        "ifcopenshell_ifcgeom_tree_clash_b": (c_bool, [HandleP, HandlePP]),
        "ifcopenshell_ifcgeom_tree_clash_type": (
            c_bool, [HandleP, POINTER(c_int32)],
        ),
        "ifcopenshell_ifcgeom_tree_clash_distance": (
            c_bool, [HandleP, POINTER(c_double)],
        ),
        "ifcopenshell_ifcgeom_tree_clash_p1": (c_bool, [HandleP, Dp]),
        "ifcopenshell_ifcgeom_tree_clash_p2": (c_bool, [HandleP, Dp]),
        "ifcopenshell_ifcgeom_tree_ray_intersection_list_destroy": (None, [HandleP]),
        "ifcopenshell_ifcgeom_tree_ray_intersection_destroy": (None, [HandleP]),
        "ifcopenshell_ifcgeom_tree_ray_intersection_count": (
            c_bool, [HandleP, HandleP, POINTER(c_size_t)],
        ),
        "ifcopenshell_ifcgeom_tree_ray_intersection_at": (
            c_bool, [HandleP, HandleP, c_size_t, HandlePP],
        ),
        "ifcopenshell_ifcgeom_tree_ray_intersection_instance": (
            c_bool, [HandleP, HandlePP],
        ),
        "ifcopenshell_ifcgeom_tree_ray_intersection_distance": (
            c_bool, [HandleP, POINTER(c_double)],
        ),
        "ifcopenshell_ifcgeom_tree_ray_intersection_dot_product": (
            c_bool, [HandleP, POINTER(c_double)],
        ),
        "ifcopenshell_ifcgeom_tree_ray_intersection_position": (
            c_bool, [HandleP, Dp],
        ),
        "ifcopenshell_ifcgeom_tree_ray_intersection_normal": (
            c_bool, [HandleP, Dp],
        ),
        "ifcopenshell_ifcgeom_tree_ray_intersection_ray_distance": (
            c_bool, [HandleP, POINTER(c_double)],
        ),
        "ifcopenshell_ifcgeom_tree_ray_intersection_style_index": (
            c_bool, [HandleP, POINTER(c_int32)],
        ),
        # ----- buffer (used as serializer output sink) ----------------
        "ifcopenshell_ifcgeom_buffer_destroy": (None, [HandleP]),
        "ifcopenshell_ifcgeom_create_buffer": (c_bool, [HandlePP]),
        "ifcopenshell_ifcgeom_create_buffer_from_filename": (
            c_bool, [c_char_p, HandlePP],
        ),
        "ifcopenshell_ifcgeom_buffer_get_value": (
            c_bool, [HandleP, POINTER(ifcopenshell_string_t)],
        ),
        "ifcopenshell_ifcgeom_buffer_is_ready": (
            c_bool, [HandleP, POINTER(c_bool)],
        ),
        # ----- serializer constructors --------------------------------
        "ifcopenshell_ifcgeom_create_obj_serializer": (
            c_bool, [HandleP, HandleP, HandleP, HandleP, HandlePP],
        ),
        "ifcopenshell_ifcgeom_create_ttl_serializer": (
            c_bool, [HandleP, HandleP, HandleP, HandlePP],
        ),
        "ifcopenshell_ifcgeom_create_svg_serializer": (
            c_bool, [HandleP, HandleP, HandleP, HandlePP],
        ),
        "ifcopenshell_ifcgeom_create_gltf_serializer": (
            c_bool, [c_char_p, HandleP, HandleP, HandlePP],
        ),
        "ifcopenshell_ifcgeom_create_iges_serializer": (
            c_bool, [c_char_p, HandleP, HandleP, HandlePP],
        ),
        "ifcopenshell_ifcgeom_create_step_serializer": (
            c_bool, [c_char_p, HandleP, HandleP, HandlePP],
        ),
        "ifcopenshell_ifcgeom_create_collada_serializer": (
            c_bool, [c_char_p, HandleP, HandleP, HandlePP],
        ),
        "ifcopenshell_ifcgeom_create_hdf_serializer": (
            c_bool, [c_char_p, HandleP, HandleP, HandlePP],
        ),
        "ifcopenshell_ifcgeom_create_json_serializer": (
            c_bool, [c_void_p, c_char_p, HandlePP],
        ),
        "ifcopenshell_ifcgeom_create_xml_serializer": (
            c_bool, [c_void_p, c_char_p, HandlePP],
        ),
        "ifcopenshell_ifcgeom_create_rocksdb_serializer": (
            c_bool, [c_void_p, c_char_p, HandlePP],
        ),
        "ifcopenshell_ifcgeom_create_rocksdb_serializer_streaming": (
            c_bool, [c_char_p, c_char_p, c_bool, HandlePP],
        ),
        "ifcopenshell_ifcgeom_serializer_destroy": (None, [HandleP]),
        # ----- geometry_serializer methods ---------------------------
        "ifcopenshell_ifcgeom_geometry_serializer_geometry_settings": (
            c_bool, [HandleP, HandlePP],
        ),
        "ifcopenshell_ifcgeom_geometry_serializer_settings": (
            c_bool, [HandleP, HandlePP],
        ),
        "ifcopenshell_ifcgeom_geometry_serializer_write_triangulation_element": (
            c_bool, [HandleP, HandleP],
        ),
        "ifcopenshell_ifcgeom_geometry_serializer_write_brep_element": (
            c_bool, [HandleP, HandleP],
        ),
        "ifcopenshell_ifcgeom_geometry_serializer_finalize": (
            c_bool, [HandleP],
        ),
        "ifcopenshell_ifcgeom_geometry_serializer_is_tesselated": (
            c_bool, [HandleP, POINTER(c_bool)],
        ),
        "ifcopenshell_ifcgeom_geometry_serializer_read": (
            c_bool, [HandleP, c_void_p, c_char_p, c_char_p, c_int32, HandlePP],
        ),
        "ifcopenshell_ifcgeom_geometry_serializer_ready": (
            c_bool, [HandleP, POINTER(c_bool)],
        ),
        "ifcopenshell_ifcgeom_geometry_serializer_set_file": (
            c_bool, [HandleP, c_void_p],
        ),
        "ifcopenshell_ifcgeom_geometry_serializer_set_unit_name_and_magnitude": (
            c_bool, [HandleP, c_char_p, c_double],
        ),
        "ifcopenshell_ifcgeom_geometry_serializer_write_header": (
            c_bool, [HandleP],
        ),
        # ----- serializer (base) methods (xml/json/rocksdb) ----------
        "ifcopenshell_ifcgeom_serializer_finalize": (c_bool, [HandleP]),
        "ifcopenshell_ifcgeom_serializer_ready": (c_bool, [HandleP, POINTER(c_bool)]),
        "ifcopenshell_ifcgeom_serializer_set_file": (c_bool, [HandleP, c_void_p]),
        "ifcopenshell_ifcgeom_serializer_write_header": (c_bool, [HandleP]),
        # ----- schema-aware shape (de)serialise ----------------------
        "ifcopenshell_ifcgeom_serialise": (
            c_bool, [c_char_p, c_char_p, c_bool, HandlePP],
        ),
        "ifcopenshell_ifcgeom_tesselate": (
            c_bool, [c_char_p, c_char_p, c_double, HandlePP],
        ),
    }

    for name, (restype, argtypes) in sigs.items():
        try:
            fn = getattr(lib, name)
        except AttributeError:  # pragma: no cover
            raise RuntimeError(f"ifcgeom symbol missing from libifcopenshell_capi: {name}")
        fn.restype = restype
        fn.argtypes = argtypes

    _bound = True
    return lib


class _OwnedHandle:
    __slots__ = ("_h",)
    _destroy_fn_name: str | None = None

    def __init__(self, h):
        if h is None:
            self._h = HandleP()
        elif isinstance(h, HandleP):
            self._h = h
        elif isinstance(h, c_void_p):
            self._h = ctypes.cast(h, HandleP) if h.value else HandleP()
        elif isinstance(h, int):
            self._h = ctypes.cast(c_void_p(h), HandleP) if h else HandleP()
        else:
            self._h = h

    def __del__(self):
        try:
            if self._destroy_fn_name and self._h:
                fn = getattr(bind(), self._destroy_fn_name, None)
                if fn is not None:
                    fn(self._h)
        except Exception:  # pragma: no cover
            pass

    @property
    def _ptr(self) -> c_void_p:
        if not self._h:
            return c_void_p()
        return c_void_p(self._h.contents.ptr)


def take_string(s: ifcopenshell_string_t) -> str:
    try:
        if s.data and s.size:
            return ctypes.string_at(s.data, s.size).decode("utf-8")
        return ""
    finally:
        bind().ifcopenshell_string_destroy(byref(s))


def take_string_list(lst: ifcopenshell_string_list_t) -> tuple[str, ...]:
    try:
        out = []
        for i in range(lst.size):
            item = lst.items[i]
            if item.data and item.size:
                out.append(ctypes.string_at(item.data, item.size).decode("utf-8"))
            else:
                out.append("")
        return tuple(out)
    finally:
        bind().ifcopenshell_string_list_destroy(byref(lst))


def take_int_list(lst: ifcopenshell_int32_list_t) -> list[int]:
    try:
        return [int(lst.items[i]) for i in range(lst.size)]
    finally:
        bind().ifcopenshell_int32_list_destroy(byref(lst))


def take_double_list(lst: ifcopenshell_double_list_t) -> list[float]:
    try:
        return [float(lst.items[i]) for i in range(lst.size)]
    finally:
        bind().ifcopenshell_double_list_destroy(byref(lst))


def to_string_list(values) -> ifcopenshell_string_list_t:
    arr = list(values)
    items = (ifcopenshell_string_t * len(arr))()
    keep = []
    for i, s in enumerate(arr):
        if not isinstance(s, (bytes, bytearray)):
            s = str(s).encode("utf-8")
        b = ctypes.create_string_buffer(s)
        keep.append(b)
        items[i].data = ctypes.cast(b, c_char_p)
        items[i].size = len(s)
        items[i].owned = False
    out = ifcopenshell_string_list_t()
    out.items = items
    out.size = len(arr)
    out._keep = (items, keep)  # type: ignore[attr-defined]
    return out


def to_int_list(values) -> ifcopenshell_int32_list_t:
    arr = list(values)
    items = (c_int32 * len(arr))(*[int(x) for x in arr])
    out = ifcopenshell_int32_list_t()
    out.items = items
    out.size = len(arr)
    out._keep = items  # type: ignore[attr-defined]
    return out


def to_double_list(values) -> ifcopenshell_double_list_t:
    arr = list(values)
    items = (c_double * len(arr))(*[float(x) for x in arr])
    out = ifcopenshell_double_list_t()
    out.items = items
    out.size = len(arr)
    out._keep = items  # type: ignore[attr-defined]
    return out
