# SPDX-License-Identifier: LGPL-3.0-or-later
# This file was generated with the assistance of an AI coding tool.
"""ctypes bindings for the autogenerated ``ifcopenshell_ifcgeom_*`` C ABI.

All function signatures are bound lazily on first use via :func:`bind`.
The accompanying ``main.py`` builds the high-level Pythonic ``geom`` API
on top of these primitives. No SWIG/legacy ``ifcopenshell_wrapper``
imports - this module is the single integration point against the new
autogenerated C library.
"""

from __future__ import annotations

import ctypes
from ctypes import (
    POINTER,
    c_void_p,
)

import ifcopenshell
from ifcopenshell import _generated_capi


# ---------------------------------------------------------------------------
# Shared C value-type structs.
#
# We re-use the struct definitions from :mod:`ifcopenshell_wrapper` so the
# argtypes for shared symbols (``ifcopenshell_string_destroy`` etc.) remain
# compatible across both modules. Re-defining the same C struct with a
# different Python class would silently corrupt argtype validation for
# the legacy wrapper since ``ctypes`` checks pointer types by Python class
# identity, not C layout.
# ---------------------------------------------------------------------------

from ifcopenshell.ifcopenshell_wrapper import (  # noqa: E402
    _HandleStruct,
    ifcopenshell_string_list_t,
    ifcopenshell_string_t,
)


ifcopenshell_int32_list_t = _generated_capi.ifcopenshell_int32_list_t
ifcopenshell_int32_list_list_t = _generated_capi.ifcopenshell_int32_list_list_t
ifcopenshell_int32_list_list_list_t = _generated_capi.ifcopenshell_int32_list_list_list_t
ifcopenshell_double_list_t = _generated_capi.ifcopenshell_double_list_t


HandleP = POINTER(_HandleStruct)
HandlePP = POINTER(HandleP)


ifcopenshell_ifcgeom_taxonomy_style_list_t = _generated_capi.ifcopenshell_ifcgeom_taxonomy_style_list_t
ifcopenshell_ifcgeom_element_list_t = _generated_capi.ifcopenshell_ifcgeom_element_list_t
ifcopenshell_ifc_instance_list_t = _generated_capi.ifcopenshell_ifc_instance_list_t


# ---------------------------------------------------------------------------
# Lazy signature binding.
# ---------------------------------------------------------------------------

_bound = False
_GEOM_BIND_NAMES = tuple(
    name
    for name in _generated_capi.FUNCTION_SIGNATURES
    if name.startswith("ifcopenshell_ifcgeom_")
    or name
    in {
        "ifcopenshell_double_list_destroy",
        "ifcopenshell_ifcparse_instance_list_create_from_handles",
        "ifcopenshell_int32_list_destroy",
        "ifcopenshell_int32_list_list_destroy",
        "ifcopenshell_int32_list_list_list_destroy",
        "ifcopenshell_string_destroy",
        "ifcopenshell_string_list_destroy",
    }
)


def bind():
    global _bound
    lib = ifcopenshell._get_lib()
    if _bound:
        return lib

    _generated_capi.bind(lib, names=_GEOM_BIND_NAMES)

    _bound = True
    return lib


class _OwnedHandle:
    __slots__ = ("_h",)
    _destroy_fn_name: str | None = None

    def __init__(self, h):
        if h is None:
            self._h = HandleP()
        elif isinstance(h, HandleP):
            self._h = h
        elif isinstance(h, c_void_p):
            self._h = ctypes.cast(h, HandleP) if h.value else HandleP()
        elif isinstance(h, int):
            self._h = ctypes.cast(c_void_p(h), HandleP) if h else HandleP()
        else:
            self._h = h

    def __del__(self):
        try:
            if self._destroy_fn_name and self._h:
                fn = getattr(bind(), self._destroy_fn_name, None)
                if fn is not None:
                    fn(self._h)
        except Exception:  # pragma: no cover
            pass

    @property
    def _ptr(self) -> c_void_p:
        if not self._h:
            return c_void_p()
        return c_void_p(self._h.contents.ptr)


def take_int_list(lst: ifcopenshell_int32_list_t) -> list[int]:
    return list(_generated_capi.take_int32_list(bind(), lst))


def take_double_list(lst: ifcopenshell_double_list_t) -> list[float]:
    return list(_generated_capi.take_double_list(bind(), lst))


def to_string_list(values) -> ifcopenshell_string_list_t:
    return _generated_capi.make_string_list(values)


def to_int_list(values) -> ifcopenshell_int32_list_t:
    return _generated_capi.make_int32_list(values)


def to_double_list(values) -> ifcopenshell_double_list_t:
    return _generated_capi.make_double_list(values)
