# SPDX-License-Identifier: LGPL-3.0-or-later
# This file was generated with the assistance of an AI coding tool.
"""Native C extension bindings for the autogenerated ``ifcopenshell_ifcgeom_*`` C ABI.

All function calls go through the ``_ifcopenshell_capi`` C extension module.
The accompanying ``main.py`` builds the high-level Pythonic ``geom`` API
on top of these primitives. No SWIG/legacy ``ifcopenshell_wrapper``
imports - this module is the single integration point against the new
autogenerated C library.
"""

from __future__ import annotations

from ifcopenshell import _ifcopenshell_capi as _capi


class _OwnedHandle:
    __slots__ = ("_h",)
    _destroy_fn_name: str | None = None

    def __init__(self, h):
        self._h = h

    def __del__(self):
        try:
            if self._destroy_fn_name and self._h is not None:
                fn = getattr(_capi, self._destroy_fn_name, None)
                if fn is not None:
                    fn(self._h)
        except Exception:  # pragma: no cover
            pass


def take_int_list(lst) -> list[int]:
    return list(lst)


def take_double_list(lst) -> list[float]:
    return list(lst)


def to_string_list(values) -> list[str]:
    return [str(v) for v in values]


def to_int_list(values) -> list[int]:
    return [int(v) for v in values]


def to_double_list(values) -> list[float]:
    return [float(v) for v in values]
