# SPDX-License-Identifier: LGPL-3.0-or-later
# This file was generated with the assistance of an AI coding tool.
"""Public surface of :mod:`ifcopenshell.geom`.

Pythonic wrappers around the autogenerated ``ifcopenshell_geom_*`` C ABI.
Mirrors the upstream SWIG-backed module (parity goal) without depending on
the legacy ``ifcopenshell_wrapper`` extension.
"""

from __future__ import annotations

import os
from collections.abc import Iterable
from typing import Any, Literal, Optional, Union

import ifcopenshell
from ifcopenshell import _ifcopenshell_capi as _capi

from ._capi import (
    _OwnedHandle,
    take_double_list,
    take_int_list,
    to_double_list,
    to_int_list,
    to_string_list,
)

try:
    import numpy as np  # type: ignore
except ImportError:  # pragma: no cover - numpy is a hard dep
    np = None  # type: ignore


# ---------------------------------------------------------------------------
# Public type literals (kept in lockstep with upstream main.py).
# ---------------------------------------------------------------------------


SETTING = Literal[
    "angle-unit", "apply-default-materials", "apply-offset", "boolean-attempt-2d",
    "building-local-placement", "cache-shapes", "cgal-original-edges",
    "cgal-smooth-angle-degrees", "circle-segments", "compute-curvature",
    "context-identifiers", "context-ids", "context-types", "convert-back-units",
    "debug", "defer-processing-first-element", "dimensionality",
    "disable-boolean-result", "disable-opening-subtractions", "edge-arrows",
    "element-hierarchy", "enable-layerset-slicing", "force-space-transparency",
    "function-step-param", "function-step-type", "generate-uvs", "iterator-output",
    "keep-bounding-boxes", "layerset-first", "length-unit", "make-volume",
    "max-offset-deviation", "max-offset", "mesher-angular-deflection",
    "mesher-linear-deflection", "model-offset", "model-rotation",
    "no-clean-triangulation", "no-normals", "no-parallel-mapping",
    "no-wire-intersection-check", "no-wire-intersection-tolerance",
    "permissive-shape-reuse", "precision-factor", "precision", "reorient-shells",
    "site-local-placement", "surface-colour", "triangulation-type", "unify-shapes",
    "use-material-names", "use-python-opencascade", "use-world-coords", "validate",
    "weld-vertices",
]
SERIALIZER_SETTING = Literal[
    "base-uri", "use-element-names", "use-element-guids", "use-element-step-ids",
    "use-element-types", "y-up", "ecef", "digits", "wkt-use-section",
    "separate-z-up-node",
    "bounds", "scale", "center",
    "section-ref", "elevation-ref", "elevation-ref-guid",
    "auto-section", "auto-elevation",
    "draw-storey-heights", "profile-threshold", "storey-height-line-length",
    "svg-xmlns", "svg-poly", "svg-prefilter",
    "svg-unify-inputs", "svg-segment-projection", "svg-subtract-before",
    "svg-write-poly", "svg-project", "svg-without-storeys",
    "svg-no-css", "svg-mirror-y", "svg-mirror-x",
    "door-arcs", "section-height", "section-height-from-storeys",
    "print-space-names", "print-space-areas", "space-name-transform",
]
GEOMETRY_LIBRARY = Literal[
    "cgal", "cgal-simple", "manifold", "opencascade", "hybrid-cgal-simple-opencascade"
]


# Iterator-output enum values (must match
# ``ifcopenshell::geometry::settings::IteratorOutputOptions`` in
# ``src/ifcgeom/ConversionSettings.h``: TRIANGULATED=0, NATIVE=1, SERIALIZED=2).
TRIANGULATED = 0
NATIVE = 1
SERIALIZED = 2

ShapeType = Union["BRepRepresentation", "Triangulation", "Serialization"]
ShapeElementType = Union["BRepElement", "TriangulationElement", "SerializedElement"]


# ---------------------------------------------------------------------------
# Settings
# ---------------------------------------------------------------------------


class missing_setting:
    def __repr__(self) -> str:
        return "-"


class settings_mixin:
    """Pythonic interface mixin shared by :class:`settings` and
    :class:`serializer_settings`."""

    _settings_kind: str = "settings"
    _h: Any

    @staticmethod
    def name(k: str) -> str:
        return k.lower().replace("_", "-")

    @staticmethod
    def rname(k: str) -> str:
        return k.upper().replace("-", "_")

    def _fn(self, suffix: str):
        return getattr(_capi, f"{self._settings_kind}_{suffix}")

    def get_type(self, name: str) -> str:
        result = self._fn("get_type")(self._h, self.name(name))
        if result is None:
            raise RuntimeError(f"Unknown setting: {name}")
        return result

    def setting_names(self) -> tuple[str, ...]:
        names = self._fn("setting_names")(self._h)
        if names is None:
            raise RuntimeError("Failed to enumerate setting names")
        names = tuple(names)
        if isinstance(self, settings) and "use-python-opencascade" not in names:
            names = names + ("use-python-opencascade",)
        return names

    def _get_typed(self, name: str) -> Any:
        ty = self.get_type(name)
        nm = self.name(name)
        h = self._h
        if ty == "bool":
            return bool(self._fn("get_bool")(h, nm))
        if ty == "int":
            return int(self._fn("get_int")(h, nm))
        if ty == "double":
            return float(self._fn("get_double")(h, nm))
        if ty == "std::string":
            return self._fn("get_string")(h, nm) or ""
        if ty.startswith("std::set<int"):
            return list(self._fn("get_int_set")(h, nm))
        if ty == "std::set<std::string>":
            result = self._fn("get_string_set")(h, nm)
            return list(result) if result is not None else []
        if ty == "std::vector<double>":
            return list(self._fn("get_double_list")(h, nm))
        try:
            return int(self._fn("get_int")(h, nm))
        except Exception:
            pass
        try:
            result = self._fn("get_string")(h, nm)
            if result is not None:
                return result
        except Exception:
            pass
        raise RuntimeError(f"Unsupported setting type for {name!r}: {ty}")

    def _set_typed(self, name: str, value: Any) -> None:
        try:
            ty = self.get_type(name)
        except RuntimeError:
            raise RuntimeError(f"Unknown setting: {name}")
        nm = self.name(name)
        h = self._h
        if ty == "bool":
            self._fn("set_bool")(h, nm, bool(value))
            return
        if ty == "int":
            self._fn("set_int")(h, nm, int(value))
            return
        if ty == "double":
            self._fn("set_double")(h, nm, float(value))
            return
        if ty == "std::string":
            self._fn("set_string")(h, nm, str(value))
            return
        if ty.startswith("std::set<int"):
            self._fn("set_int_set")(h, nm, to_int_list(value))
            return
        if ty == "std::set<std::string>":
            self._fn("set_string_set")(h, nm, to_string_list(value))
            return
        if ty == "std::vector<double>":
            self._fn("set_double_list")(h, nm, to_double_list(value))
            return
        try:
            self._fn("set_int")(h, nm, int(value))
            return
        except Exception:
            pass
        raise RuntimeError(f"Unsupported setting type for {name!r}: {ty}")

    def set(self, k: str, v: Any) -> None:
        k = self.name(k)
        if isinstance(self, settings) and k == "use-python-opencascade":
            if not has_occ:
                raise AttributeError("Python OpenCASCADE is not installed")
            if v:
                self._set_typed("iterator-output", SERIALIZED)
                self._set_typed("use-world-coords", True)
                self.use_python_opencascade = True
            else:
                self.use_python_opencascade = False
            return
        self._set_typed(k, v)

    def get(self, k: str) -> Any:
        k = self.name(k)
        if isinstance(self, settings) and k == "use-python-opencascade":
            return getattr(self, "use_python_opencascade", False)
        return self._get_typed(k)

    def __repr__(self) -> str:
        def safe_get(x):
            try:
                return self.get(x)
            except RuntimeError:
                return missing_setting()

        fmt_pair = lambda x: "%s = %r" % (self.rname(x), safe_get(x))
        return "%s(%s)" % (type(self).__name__, ", ".join(map(fmt_pair, self.setting_names())))

    def __getattr__(self, k: str) -> str:
        if k.startswith("_") or k == "use_python_opencascade":
            raise AttributeError(k)
        try:
            names = type(self).__dict__.get("__cached_setting_rnames__")
            if names is None:
                names = set(map(self.rname, self.setting_names()))
                type(self).__cached_setting_rnames__ = names  # type: ignore[attr-defined]
        except Exception:
            raise AttributeError(k)
        if k in names:
            return k
        raise AttributeError(f"'{type(self).__name__}' object has no attribute '{k}'")

    def build_parser(self, parser) -> None:
        type_factories = {
            "bool": bool, "int": int, "double": float, "std::string": str,
            "std::set<int>": lambda s: list(map(int, s.split(";"))),
            "std::set<std::string>": lambda s: s.split(";"),
            "std::vector<double>": lambda s: list(map(float, s.split(";"))),
            "IteratorOutputOptions": int, "FunctionStepMethod": int,
            "OutputDimensionalityTypes": int, "TriangulationMethod": int,
        }
        for nm in self.setting_names():
            ty = "bool" if nm == "use-python-opencascade" else self.get_type(nm)
            if ty == "bool":
                group = parser.add_mutually_exclusive_group()
                group.add_argument(f"--{nm}", dest=nm.replace("-", "_"), action="store_true")
                group.add_argument(f"--no-{nm}", dest=nm.replace("-", "_"), action="store_false")
                parser.set_defaults(**{nm.replace("-", "_"): None})
            else:
                parser.add_argument(
                    f"--{nm}", dest=nm.replace("-", "_"), type=type_factories.get(ty, str)
                )

    def apply_namespace(self, namespace) -> None:
        names = set(self.setting_names())
        for k, v in namespace._get_kwargs():
            if k.replace("_", "-") in names and v is not None:
                self.set(k.replace("_", "-"), v)


class settings(settings_mixin, _OwnedHandle):
    """Geometry settings - wraps ``ifcopenshell_geom_settings_t``."""

    _settings_kind = "settings"
    _destroy_fn_name = "settings_destroy"
    use_python_opencascade = False

    def __init__(self, **kwargs: Any):
        out = _capi.create_settings()
        _OwnedHandle.__init__(self, out)
        for k, v in kwargs.items():
            self.set(getattr(self, k), v)


class serializer_settings(settings_mixin, _OwnedHandle):
    """Serializer settings - wraps ``ifcopenshell_geom_serializer_settings_t``."""

    _settings_kind = "serializer_settings"
    _destroy_fn_name = "serializer_settings_destroy"

    def __init__(self, **kwargs: Any):
        out = _capi.create_serializer_settings()
        _OwnedHandle.__init__(self, out)
        for k, v in kwargs.items():
            self.set(getattr(self, k), v)


# ---------------------------------------------------------------------------
# Element + geometry data wrappers (y6b)
# ---------------------------------------------------------------------------


def _string_attr(handle, fn_name: str) -> str:
    fn = getattr(_capi, fn_name)
    return fn(handle) or ""


def _int_attr(handle, fn_name: str) -> int:
    fn = getattr(_capi, fn_name)
    return int(fn(handle))


def _take_handle_list(lst, wrap_cls):
    """Move-construct Python wrappers from a handle list."""
    return [wrap_cls(handle) if handle else wrap_cls(None) for handle in lst]


def _numeric_buffer(data, dtype):
    """Expose a native numeric buffer without another Python-side copy."""
    if np is not None:
        if data is None:
            return np.empty(0, dtype=dtype)
        return np.frombuffer(data, dtype=dtype)
    if not data:
        return []
    return list(data)


class Transformation(_OwnedHandle):
    """Wraps ``ifcopenshell_geom_transformation_t``."""

    _destroy_fn_name = "transformation_destroy"

    def matrix(self):
        """Return the row-major 4x4 transformation matrix as a flat list/numpy."""
        data = _capi.transformation_matrix(self._h)
        if np is not None:
            arr = np.asarray(data, dtype=np.float64)
            return arr.reshape(4, 4) if arr.size == 16 else arr
        return data

    @property
    def data(self):
        return self.matrix()

    def __iter__(self):
        m = self.matrix()
        if np is not None and hasattr(m, "ravel"):
            return iter(m.ravel().tolist())
        return iter(m)


class PlacementTransformation:
    """SWIG-compatible transformation result for placement create_shape()."""

    def __init__(self, matrix):
        self.matrix = tuple(float(v) for v in matrix.T.flatten())

    @property
    def data(self):
        return self.matrix

    def __iter__(self):
        return iter(self.matrix)


class TaxonomyColour(_OwnedHandle):
    """RGBA colour (3 or 4 doubles)."""

    _destroy_fn_name = "taxonomy_colour_destroy"

    def get_data(self) -> list[float]:
        return list(_capi.taxonomy_colour_get_data(self._h))

    def __iter__(self):
        return iter(self.get_data())

    def __getitem__(self, i):
        return self.get_data()[i]


class TaxonomyStyle(_OwnedHandle):
    """A material/style entry (``ifcopenshell_geom_taxonomy_style_t``)."""

    _destroy_fn_name = "taxonomy_style_destroy"

    def name(self) -> str:
        return _string_attr(self._h, "taxonomy_style_name")

    def has_specularity(self) -> bool:
        return bool(_capi.taxonomy_style_has_specularity(self._h))

    def has_transparency(self) -> bool:
        return bool(_capi.taxonomy_style_has_transparency(self._h))

    def specularity(self) -> float:
        return float(_capi.taxonomy_style_specularity(self._h))

    def transparency(self) -> float:
        return float(_capi.taxonomy_style_transparency(self._h))

    def use_surface_color(self) -> bool:
        return bool(_capi.taxonomy_style_use_surface_color(self._h))

    def _colour(self, fn_name: str) -> Optional[TaxonomyColour]:
        fn = getattr(_capi, fn_name)
        out = fn(self._h)
        if not out:
            return None
        return TaxonomyColour(out)

    def diffuse(self):
        return self._colour("taxonomy_style_diffuse")

    def specular(self):
        return self._colour("taxonomy_style_specular")

    def surface(self):
        return self._colour("taxonomy_style_surface")

    def instance_id(self) -> int:
        return int(_capi.taxonomy_style_instance_id(self._h))

    @property
    def diffuse_colour(self):
        c = self.diffuse()
        return list(c) if c is not None else []

    def __repr__(self) -> str:
        return f"TaxonomyStyle({self.name()!r})"


# Backwards-compatibility alias used by upstream Python tests.
SurfaceStyle = TaxonomyStyle


def _as_tuple(arr):
    """Return a Python tuple, matching SWIG's std::vector<T> exposure.

    Accepts numpy arrays, lists, or anything iterable; ``tolist`` is preferred
    on numpy arrays so individual elements come out as native Python scalars
    (matching upstream behaviour where a ``std::vector<int>`` becomes a tuple
    of Python ints, not numpy.int32).
    """
    if arr is None:
        return ()
    if hasattr(arr, "tolist"):
        return tuple(arr.tolist())
    return tuple(arr)


class Triangulation(_OwnedHandle):
    """Triangulated geometry data (``ifcopenshell_geom_triangulation_t``)."""

    _destroy_fn_name = "triangulation_destroy"

    @property
    def id(self) -> str:
        owner = getattr(self, "_element_owner", None)
        return owner.unique_id if owner is not None else ""

    # ---- bulk numeric arrays --------------------------------------------
    #
    # The non-``_buffer`` properties mirror SWIG's behaviour: a
    # ``std::vector<T>`` is exposed as a Python tuple. The ``_buffer``
    # aliases return numpy arrays (buffer-protocol compliant), which is what
    # ``ifcopenshell.util.shape`` consumes via ``np.frombuffer``.

    @property
    def verts_buffer(self):
        return _numeric_buffer(
            _capi.triangulation_verts_buffer(self._h),
            np.float64 if np is not None else None,
        )

    @property
    def verts(self):
        return _as_tuple(self.verts_buffer)

    @property
    def faces_buffer(self):
        return _numeric_buffer(
            _capi.triangulation_faces_buffer(self._h),
            np.int32 if np is not None else None,
        )

    @property
    def faces(self):
        faces = _as_tuple(self.faces_buffer)
        if faces:
            return faces
        return self.polyhedral_faces_without_holes() or self.polyhedral_faces_with_holes()

    @property
    def normals_buffer(self):
        return _numeric_buffer(
            _capi.triangulation_normals_buffer(self._h),
            np.float64 if np is not None else None,
        )

    @property
    def normals(self):
        return _as_tuple(self.normals_buffer)

    @property
    def edges_buffer(self):
        return _numeric_buffer(
            _capi.triangulation_edges_buffer(self._h),
            np.int32 if np is not None else None,
        )

    @property
    def edges(self):
        return _as_tuple(self.edges_buffer)

    @property
    def material_ids_buffer(self):
        return _numeric_buffer(
            _capi.triangulation_material_ids_buffer(self._h),
            np.int32 if np is not None else None,
        )

    @property
    def material_ids(self):
        return _as_tuple(self.material_ids_buffer)

    @property
    def item_ids_buffer(self):
        return _numeric_buffer(
            _capi.triangulation_item_ids_buffer(self._h),
            np.int32 if np is not None else None,
        )

    @property
    def uvs_buffer(self):
        return _numeric_buffer(
            _capi.triangulation_uvs_buffer(self._h),
            np.float64 if np is not None else None,
        )

    @property
    def edges_item_ids_buffer(self):
        return _numeric_buffer(
            _capi.triangulation_edges_item_ids_buffer(self._h),
            np.int32 if np is not None else None,
        )

    @property
    def edges_item_ids(self):
        return _as_tuple(self.edges_item_ids_buffer)

    @property
    def item_ids(self):
        return _as_tuple(self.item_ids_buffer)

    @property
    def uvs(self):
        return _as_tuple(self.uvs_buffer)

    @property
    def colors(self):
        return _numeric_buffer(
            _capi.triangulation_colors_buffer(self._h),
            np.float64 if np is not None else None,
        )

    # ---- materials ---------------------------------------------------

    def material_count(self) -> int:
        return int(_capi.triangulation_material_count(self._h))

    @property
    def materials(self) -> list[TaxonomyStyle]:
        n = self.material_count()
        out = []
        for i in range(n):
            h = _capi.triangulation_material_at(self._h, i)
            if not h:
                out.append(None)  # type: ignore[arg-type]
            else:
                out.append(TaxonomyStyle(h))
        return out

    # ---- polyhedral face accessors ----------------------------------

    def polyhedral_faces_without_holes(self) -> list[list[list[int]]]:
        data = _capi.triangulation_polyhedral_faces_without_holes(self._h)
        if not data:
            return []
        return [list(row) for row in data]

    def polyhedral_faces_with_holes(self) -> list[list[list[int]]]:
        data = _capi.triangulation_polyhedral_faces_with_holes(self._h)
        if not data:
            return []
        return [
            [list(inner) for inner in outer]
            for outer in data
        ]


class BRepRepresentation(_OwnedHandle):
    """``ifcopenshell_geom_brep_representation_t``."""

    _destroy_fn_name = "brep_representation_destroy"

    @property
    def entity(self) -> str:
        return _string_attr(self._h, "brep_representation_entity")

    @property
    def id(self) -> str:
        return _string_attr(self._h, "brep_representation_id")

    @property
    def size(self) -> int:
        return _int_attr(self._h, "brep_representation_size")

    def item_id(self, i: int) -> int:
        return int(_capi.brep_representation_item_id(self._h, i))

    @property
    def settings(self):
        out = _capi.brep_representation_settings(self._h)
        if not out:
            return None
        s = settings.__new__(settings)
        _OwnedHandle.__init__(s, out)
        s._destroy_fn_name = None  # type: ignore[attr-defined]
        return s

    def calculate_volume(self) -> float:
        return float(_capi.brep_representation_calculate_volume(self._h))

    def calculate_surface_area(self) -> float:
        return float(_capi.brep_representation_calculate_surface_area(self._h))


class Serialization(_OwnedHandle):
    """``ifcopenshell_geom_serialization_t`` - serialised BRep payload."""

    _destroy_fn_name = "serialization_destroy"

    @property
    def brep_data(self) -> str:
        return _string_attr(self._h, "serialization_brep_data")

    @property
    def surface_style_ids(self) -> list[int]:
        return take_int_list(_capi.serialization_surface_style_ids(self._h))

    @property
    def surface_styles(self) -> list[float]:
        return take_double_list(_capi.serialization_surface_styles(self._h))


class Element(_OwnedHandle):
    """Base wrapper over ``ifcopenshell_geom_element_t``.

    Subclasses (:class:`BRepElement`, :class:`TriangulationElement`,
    :class:`SerializedElement`) add a typed ``geometry`` accessor.
    """

    _destroy_fn_name = "element_destroy"

    # ---- common attributes ------------------------------------------
    @property
    def context(self) -> str:
        return _string_attr(self._h, "element_context")

    @property
    def guid(self) -> str:
        return _string_attr(self._h, "element_guid")

    @property
    def id(self) -> int:
        return _int_attr(self._h, "element_id")

    @property
    def name(self) -> str:
        return _string_attr(self._h, "element_name")

    @property
    def parent_id(self) -> int:
        return _int_attr(self._h, "element_parent_id")

    @property
    def type(self) -> str:
        return _string_attr(self._h, "element_type")

    @property
    def unique_id(self) -> str:
        return _string_attr(self._h, "element_unique_id")

    @property
    def parents(self) -> list[Element]:
        out = _capi.element_parents(self._h)
        if not out:
            return []
        return _take_handle_list(out, Element)

    @property
    def transformation(self) -> Transformation:
        out = _capi.element_transformation(self._h)
        if not out:
            return Transformation(None)
        return Transformation(out)

    @property
    def transformation_buffer(self):
        """Direct access to the row-major transformation matrix as numpy array."""
        result = _numeric_buffer(
            _capi.element_transformation_buffer(self._h),
            np.float64 if np is not None else None,
        )
        if np is not None and result.size == 16:
            return result.reshape(4, 4)
        return result

    @property
    def product(self):
        """Return the underlying ``IfcProduct`` entity_instance."""
        out = _capi.element_product(self._h)
        if not out:
            return None
        return _wrap_product_instance(out)


class BRepElement(Element):
    """Element holding a BRep representation (``...brep_element_t``)."""

    _destroy_fn_name = "brep_element_destroy"

    @property
    def geometry(self) -> BRepRepresentation:
        out = _capi.brep_element_geometry(self._h)
        if not out:
            return BRepRepresentation(None)
        return BRepRepresentation(out)

    def calc_volume(self) -> float:
        return float(_capi.brep_element_calc_volume(self._h))

    def calc_surface_area(self) -> float:
        return float(_capi.brep_element_calc_surface_area(self._h))

    def calculate_projected_surface_area(
        self, along_x: float = 1.0, along_y: float = 0.0, along_z: float = 0.0
    ) -> bool:
        return bool(
            _capi.brep_element_calculate_projected_surface_area(
                self._h, float(along_x), float(along_y), float(along_z)
            )
        )


class TriangulationElement(Element):
    """Element holding triangulated mesh data (``...triangulation_element_t``)."""

    _destroy_fn_name = "triangulation_element_destroy"

    @property
    def geometry(self) -> Triangulation:
        out = _capi.triangulation_element_geometry(self._h)
        if not out:
            return Triangulation(None)
        geometry = Triangulation(out)
        geometry._element_owner = self
        return geometry


class SerializedElement(Element):
    """Element holding a STEP-serialised BRep payload (``...serialized_element_t``)."""

    _destroy_fn_name = "serialized_element_destroy"

    @property
    def geometry(self) -> Serialization:
        out = _capi.serialized_element_geometry(self._h)
        if not out:
            return Serialization(None)
        return Serialization(out)


def _wrap_product_instance(h):
    """Adopt an ``ifcopenshell_instance_t`` native handle and return an
    :class:`ifcopenshell.entity_instance` rooted in the owning file."""
    if h is None:
        return None
    from ifcopenshell import _borrow_file_ptr, _instance_file_ptr
    from ifcopenshell.entity_instance import entity_instance

    file_ptr = _instance_file_ptr(h)
    f = _borrow_file_ptr(file_ptr) if file_ptr else None
    return entity_instance(f, h)


# ---------------------------------------------------------------------------
# OCC detection (parity with upstream geom/__init__.py).
# ---------------------------------------------------------------------------


def _detect_occ() -> bool:
    try:
        import OCC.Core.BRepTools  # noqa: F401  # pyright: ignore[reportMissingImports]
        return True
    except ImportError:
        pass
    try:
        import OCC.BRepTools  # noqa: F401  # pyright: ignore[reportMissingImports]
        return True
    except ImportError:
        pass
    return False


has_occ = _detect_occ()


def wrap_shape_creation(settings, shape):
    if has_occ and getattr(settings, "use_python_opencascade", False):
        from . import occ_utils as utils  # type: ignore[import-not-found]

        return utils.create_shape_from_serialization(shape)
    return shape


# ---------------------------------------------------------------------------
# Stubs for stages y6c..y6f - replaced incrementally.
# ---------------------------------------------------------------------------


def _not_yet(name: str):
    def _stub(*args, **kwargs):
        raise NotImplementedError(
            f"ifcopenshell.geom.{name} is not yet wired against the autogen C ABI"
        )

    _stub.__name__ = name
    return _stub


create_shape = None  # type: ignore[assignment]  # populated below
map_shape = None  # type: ignore[assignment]


def _instance_handle(inst):
    """Return a generated C-API handle for an entity_instance."""
    if inst is None:
        return None
    h = getattr(inst, "_handle", None)
    if h is None:
        h = getattr(getattr(inst, "wrapped_data", None), "_handle", None)
    if h is None:
        raise TypeError(f"create_shape: expected entity_instance, got {type(inst).__name__}")
    return h


def _result_geometry_type(settings_obj):
    """Resolve which element-geometry kind ``create_shape`` will return,
    based on the ``iterator-output`` setting on ``settings_obj``."""
    try:
        v = settings_obj.get("iterator-output")
    except Exception:
        v = NATIVE
    if v == TRIANGULATED:
        return TriangulationElement
    if v == SERIALIZED:
        return SerializedElement
    return BRepElement


def create_shape(
    settings_obj,
    inst,
    repr=None,  # noqa: A002 - mirrors upstream signature
    geometry_library: GEOMETRY_LIBRARY = "opencascade",
):
    """Compute geometry for ``inst`` (and optionally ``repr``).

    Returns either a fully-typed :class:`Element` subclass (when ``inst`` is
    an ``IfcProduct``) or just the geometry payload (``Triangulation`` /
    ``BRepRepresentation`` / ``Serialization``) when ``inst`` is a raw
    representation, item, or profile - matching the upstream SWIG
    behaviour.
    """
    if not isinstance(settings_obj, settings):
        raise TypeError("create_shape: settings argument must be ifcopenshell.geom.settings")

    try:
        is_placement = bool(inst.is_a("IfcObjectPlacement") or inst.is_a("IfcPlacement"))
    except Exception:
        is_placement = False
    if is_placement:
        from ifcopenshell.util.placement import get_local_placement
        from ifcopenshell.util.unit import calculate_unit_scale

        matrix = get_local_placement(inst).copy()
        if not settings_obj.get("convert-back-units"):
            file_obj = getattr(inst, "_file", None)
            if file_obj is not None:
                matrix[0:3, 3] *= calculate_unit_scale(file_obj)
        return PlacementTransformation(matrix)

    inst_h = _instance_handle(inst)
    repr_h = _instance_handle(repr) if repr is not None else None
    out = _capi.create_shape(
        settings_obj._h,
        inst_h,
        repr_h,
        geometry_library or "opencascade",
    )

    cls = _result_geometry_type(settings_obj)
    elem = cls.__new__(cls)
    _OwnedHandle.__init__(elem, out)

    is_product = False
    try:
        is_product = bool(inst.is_a("IfcProduct"))
    except Exception:
        is_product = False
    if is_product:
        return wrap_shape_creation(settings_obj, elem)
    geom = elem.geometry
    geom._element_owner = elem
    return wrap_shape_creation(settings_obj, geom)


def map_shape(settings_obj, inst):
    """Map ``inst`` to a taxonomy item (``ifcopenshell_geom_taxonomy_item_t``)."""
    if not isinstance(settings_obj, settings):
        raise TypeError("map_shape: settings argument must be ifcopenshell.geom.settings")
    inst_h = _instance_handle(inst)
    out = _capi.map_shape(settings_obj._h, inst_h)
    return TaxonomyItem(out)


class TaxonomyItem(_OwnedHandle):
    """Opaque wrapper over ``ifcopenshell_geom_taxonomy_item_t``."""

    _destroy_fn_name = "taxonomy_item_destroy"
iterate = None  # type: ignore[assignment]  # populated below
consume_iterator = None  # type: ignore[assignment]
make_shape_function = None  # type: ignore[assignment]  # populated below
serialise = None  # type: ignore[assignment]
tesselate = None  # type: ignore[assignment]


def _file_native_ptr(file_or_filename):
    """Resolve ``file_or_filename`` to a native file handle and
    return ``(handle, owning_file)``.

    The owning file is returned so callers can keep it alive for the
    lifetime of the iterator (the C iterator borrows from the file).
    """
    import ifcopenshell as _io

    if isinstance(file_or_filename, str):
        f = _io.open(file_or_filename)
    else:
        f = file_or_filename
    handle = getattr(f, "_handle", None)
    if handle is None:
        handle = getattr(getattr(f, "wrapped_data", None), "_handle", None)
    if handle is None:
        raise TypeError(
            f"iterate: expected ifcopenshell.file or path, got {type(file_or_filename).__name__}"
        )
    return handle, f


class iterator:
    """Iterator over geometric representations in an IFC file.

    Wraps the native ``ifcopenshell_geom_iterator_t`` and mirrors the
    upstream ``ifcopenshell.geom.iterator`` API so consumers can call
    :meth:`initialize`, :meth:`next`, :meth:`get`, :meth:`progress`, and
    iterate the instance directly.
    """

    def __init__(
        self,
        settings_obj: settings,
        file_or_filename,
        num_threads: int = 1,
        include=None,
        exclude=None,
        geometry_library: GEOMETRY_LIBRARY = "opencascade",
    ):
        if not isinstance(settings_obj, settings):
            raise TypeError("iterator: settings argument must be ifcopenshell.geom.settings")
        if include is not None and exclude is not None:
            raise ValueError("include and exclude cannot be specified simultaneously")

        self.settings = settings_obj
        file_ptr, self.file = _file_native_ptr(file_or_filename)

        gl = geometry_library or "opencascade"

        if include is None and exclude is None:
            out = _capi.create_iterator(
                gl, settings_obj._h, file_ptr, int(num_threads),
            )
        else:
            spec = include if exclude is None else exclude
            include_flag = include is not None
            spec_list = list(spec)
            entity_types = {type(x).__name__ for x in spec_list}
            if entity_types == {"entity_instance"}:
                if not all(x.is_a("IfcProduct") for x in spec_list):
                    raise ValueError(
                        "include/exclude must be aggregates of IfcProduct entity_instance values"
                    )
                ids = [x.id() for x in spec_list]
                out = _capi.create_iterator_with_include_exclude_id(
                    gl, settings_obj._h, file_ptr,
                    ids, bool(include_flag), int(num_threads),
                )
            else:
                str_list = [str(x) for x in spec_list]
                out = _capi.create_iterator_with_include_exclude(
                    gl, settings_obj._h, file_ptr,
                    str_list, bool(include_flag), int(num_threads),
                )

        self._h = out

    def __del__(self):
        try:
            if getattr(self, "_h", None):
                _capi.iterator_destroy(self._h)
                self._h = None
        except Exception:
            pass

    def initialize(self) -> bool:
        return bool(_capi.iterator_initialize(self._h))

    def next(self) -> bool:
        return bool(_capi.iterator_next(self._h))

    def progress(self) -> int:
        return int(_capi.iterator_progress(self._h))

    def compute_bounds(self, with_geometry: bool = False) -> None:
        _capi.iterator_compute_bounds(self._h, bool(with_geometry))

    def unit_magnitude(self) -> float:
        return float(_capi.iterator_unit_magnitude(self._h))

    def unit_name(self) -> str:
        return _capi.iterator_unit_name(self._h) or ""

    def get_log(self) -> str:
        return _capi.iterator_get_log(self._h) or ""

    def had_error_processing_elements(self) -> bool:
        return bool(_capi.iterator_had_error_processing_elements(self._h))

    def get(self):
        """Return the current element as the appropriate :class:`Element`
        subclass, mirroring the iterator-output configuration."""
        cls = _result_geometry_type(self.settings)
        if cls is TriangulationElement:
            out = _capi.iterator_get_as_triangulation_element(self._h)
        elif cls is SerializedElement:
            out = _capi.iterator_get_as_serialized_element(self._h)
        else:
            out = _capi.iterator_get_as_brep_element(self._h)
        if not out:
            raise RuntimeError(_last_error("Failed to read iterator element"))
        elem = cls.__new__(cls)
        _OwnedHandle.__init__(elem, out)
        elem._destroy_fn_name = None
        return wrap_shape_creation(self.settings, elem)

    def get_native(self):
        """Return the current element as a :class:`BRepElement` regardless
        of the iterator-output setting."""
        out = _capi.iterator_get_native(self._h)
        if not out:
            return None
        elem = BRepElement.__new__(BRepElement)
        _OwnedHandle.__init__(elem, out)
        elem._destroy_fn_name = None
        return elem

    def __iter__(self):
        if self.initialize():
            while True:
                yield self.get()
                if not self.next():
                    break


def consume_iterator(it: iterator, with_progress: bool = False):
    """Drive ``it`` to completion, yielding each element (optionally with
    its progress percentage)."""
    if it.initialize():
        while True:
            if with_progress:
                yield it.progress(), it.get()
            else:
                yield it.get()
            if not it.next():
                break


def iterate(
    settings_obj: settings,
    file_or_filename,
    num_threads: int = 1,
    include=None,
    exclude=None,
    *,
    with_progress: bool = False,
    cache=None,
    serializer_settings=None,
    geometry_library: GEOMETRY_LIBRARY = "opencascade",
):
    """Yield geometry from ``file_or_filename`` element by element.

    The ``cache`` and ``serializer_settings`` parameters are accepted for
    signature parity with upstream but are not yet wired against the
    autogen ABI; passing a non-None ``cache`` raises
    :class:`NotImplementedError`.
    """
    if cache is not None:
        if serializer_settings is None:
            raise ValueError(
                "iterate(): serializer_settings must be provided when cache is set"
            )
        hdf5_cache = serializers.hdf5(cache, settings_obj, serializer_settings)
    else:
        hdf5_cache = None
    it = iterator(
        settings_obj, file_or_filename, num_threads, include, exclude, geometry_library
    )
    if hdf5_cache is not None:
        it._cache_anchor = hdf5_cache  # type: ignore[attr-defined]
    yield from consume_iterator(it, with_progress=with_progress)



# ---------------------------------------------------------------------------
# Tree (spatial query / clash detection / ray intersection).
# ---------------------------------------------------------------------------


# Mirrors ``ifcopenshell::geometry::clash::ClashType`` enum order.
CLASH_TYPE_ITEMS = ("protrusion", "pierce", "collision", "clearance")


def _last_error(prefix: str) -> str:
    err = _capi.last_error_message()
    msg = err if err else "Unknown error"
    return f"{prefix}: {msg}"


def _instance_list_from(items):
    """Build a native ``ifcopenshell_parse_instance_list_t`` from a
    Python iterable of :class:`entity_instance`. Caller owns the returned
    handle and must destroy it with ``instance_list_destroy``."""
    handles = [_instance_handle(x) for x in items]
    return _capi.instance_list_create_from_handles(handles)


def _instance_list_to_python(list_handle) -> list:
    """Consume an ``ifcopenshell_parse_instance_list_t`` (taking
    ownership) and return the contained instances as Python
    ``entity_instance`` objects."""
    try:
        n = _capi.instance_list_size(list_handle)
        result = []
        for i in range(n):
            inst = _capi.instance_list_get(list_handle, i)
            if inst:
                result.append(_wrap_product_instance(inst))
        return result
    finally:
        _capi.instance_list_destroy(list_handle)


class clash:
    """Lightweight Python view over an
    ``ifcopenshell_geom_tree_clash_t`` handle."""

    __slots__ = ("_h", "a", "b", "clash_type", "distance", "p1", "p2")

    def __init__(self, h):
        self._h = h
        self.a = _wrap_product_instance(_capi.tree_clash_a(h))
        self.b = _wrap_product_instance(_capi.tree_clash_b(h))
        self.clash_type = int(_capi.tree_clash_type(h))
        self.distance = float(_capi.tree_clash_distance(h))
        self.p1 = tuple(take_double_list(_capi.tree_clash_p1(h)))
        self.p2 = tuple(take_double_list(_capi.tree_clash_p2(h)))

    def __del__(self):
        try:
            if self._h:
                _capi.tree_clash_destroy(self._h)
                self._h = None
        except Exception:
            pass


class ray_intersection:
    """View over ``ifcopenshell_geom_tree_ray_intersection_t``."""

    __slots__ = (
        "_h", "instance", "distance", "dot_product",
        "position", "normal", "ray_distance", "style_index",
    )

    def __init__(self, h):
        self._h = h
        self.instance = _wrap_product_instance(_capi.tree_ray_intersection_instance(h))
        self.distance = float(_capi.tree_ray_intersection_distance(h))
        self.dot_product = float(_capi.tree_ray_intersection_dot_product(h))
        self.ray_distance = float(_capi.tree_ray_intersection_ray_distance(h))
        self.style_index = int(_capi.tree_ray_intersection_style_index(h))
        self.position = tuple(take_double_list(_capi.tree_ray_intersection_position(h)))
        self.normal = tuple(take_double_list(_capi.tree_ray_intersection_normal(h)))

    def __del__(self):
        try:
            if self._h:
                _capi.tree_ray_intersection_destroy(self._h)
                self._h = None
        except Exception:
            pass


class tree:
    """Spatial-query helper backed by the native AABB tree.

    Mirrors :class:`ifcopenshell.geom.tree` (upstream SWIG class). Does not
    require the OCC-backed shape API; ``select`` accepts an
    :class:`entity_instance` or a 3-tuple of doubles.
    """

    def __init__(self, file=None, settings_obj: Optional[settings] = None):
        if file is None:
            out = _capi.create_tree()
        else:
            file_ptr, self._file_anchor = _file_native_ptr(file)
            if settings_obj is None:
                out = _capi.create_tree_from_file(file_ptr)
            else:
                out = _capi.create_tree_from_file_with_settings(file_ptr, settings_obj._h)
        self._h = out
        self._iter_anchors: list = []

    def __del__(self):
        try:
            if getattr(self, "_h", None):
                _capi.tree_destroy(self._h)
                self._h = None
        except Exception:
            pass

    # ------------------------------------------------------------------
    # Population.
    # ------------------------------------------------------------------

    def add_file(self, file, settings_obj: settings) -> None:
        if not isinstance(settings_obj, settings):
            raise TypeError("add_file: settings argument must be ifcopenshell.geom.settings")
        file_ptr, anchor = _file_native_ptr(file)
        self._file_anchor = anchor
        _capi.tree_add_file(self._h, file_ptr, settings_obj._h)

    def add_iterator(self, it: iterator) -> None:
        if not isinstance(it, iterator):
            raise TypeError("add_iterator: argument must be ifcopenshell.geom.iterator")
        _capi.tree_add_iterator(self._h, it._h)
        self._iter_anchors.append(it)

    # ------------------------------------------------------------------
    # Settings.
    # ------------------------------------------------------------------

    @property
    def enable_face_styles(self) -> bool:
        return bool(_capi.tree_enable_face_styles(self._h))

    @enable_face_styles.setter
    def enable_face_styles(self, value: bool) -> None:
        _capi.tree_set_enable_face_styles(self._h, bool(value))

    # ------------------------------------------------------------------
    # Selection.
    # ------------------------------------------------------------------

    @staticmethod
    def _unwrap_point(value):
        if hasattr(value, "Get"):  # OCC TopoDS_Vertex etc.
            g = value.Get()
            return float(g[0]), float(g[1]), float(g[2])
        if isinstance(value, (list, tuple)) and len(value) == 3:
            return float(value[0]), float(value[1]), float(value[2])
        return None

    def select(self, value, completely_within: bool = False, extend: float = -1.0e-5):
        """Select instances overlapping ``value``.

        ``value`` may be an :class:`entity_instance` (IfcProduct) or a
        3-tuple ``(x, y, z)``.
        """
        from ifcopenshell.entity_instance import entity_instance

        pt = self._unwrap_point(value)
        if pt is not None:
            out = _capi.tree_select_point(
                self._h, float(pt[0]), float(pt[1]), float(pt[2]),
                float(extend),
            )
        elif isinstance(value, entity_instance):
            out = _capi.tree_select_element(
                self._h, _instance_handle(value),
                bool(completely_within), float(extend),
            )
        else:
            raise TypeError(
                f"tree.select: expected entity_instance or 3-tuple, got {type(value).__name__}"
            )
        if not out:
            raise RuntimeError(_last_error("tree.select failed"))
        return _instance_list_to_python(out)

    def select_box(self, value, completely_within: bool = False, extend: Optional[float] = None):
        from ifcopenshell.entity_instance import entity_instance

        pt = self._unwrap_point(value)
        if pt is not None:
            out = _capi.tree_select_box_point(
                self._h, float(pt[0]), float(pt[1]), float(pt[2]),
                float(-1.0e-5 if extend is None else extend),
            )
        elif isinstance(value, entity_instance):
            out = _capi.tree_select_box_element(
                self._h, _instance_handle(value),
                bool(completely_within),
                float(-1.0e-5 if extend is None else extend),
            )
        elif (isinstance(value, (list, tuple)) and len(value) == 6) or (
            isinstance(value, (list, tuple)) and len(value) == 2
            and len(value[0]) == 3 and len(value[1]) == 3
        ):
            if len(value) == 2:
                lo, hi = value
            else:
                lo, hi = value[:3], value[3:]
            out = _capi.tree_select_box_bounds(
                self._h,
                float(lo[0]), float(lo[1]), float(lo[2]),
                float(hi[0]), float(hi[1]), float(hi[2]),
                bool(completely_within),
            )
        else:
            raise TypeError(
                "tree.select_box: expected entity_instance, 3-tuple or 6-tuple bounds"
            )
        if not out:
            raise RuntimeError(_last_error("tree.select_box failed"))
        return _instance_list_to_python(out)

    def select_ray(self, origin, direction, length: float = 1000.0):
        ox, oy, oz = (float(x) for x in origin)
        dx, dy, dz = (float(x) for x in direction)
        out = _capi.tree_select_ray(
            self._h,
            float(ox), float(oy), float(oz),
            float(dx), float(dy), float(dz),
            float(length),
        )
        if not out:
            raise RuntimeError(_last_error("tree.select_ray failed"))
        return self._collect_ray_intersections(out)

    # ------------------------------------------------------------------
    # Clash detection.
    # ------------------------------------------------------------------

    def _collect_clashes(self, list_handle):
        try:
            n = _capi.tree_clash_count(self._h, list_handle)
            results: list = []
            for i in range(n):
                ch = _capi.tree_clash_at(self._h, list_handle, i)
                if ch:
                    results.append(clash(ch))
            return tuple(results)
        finally:
            _capi.tree_clash_list_destroy(list_handle)

    def _collect_ray_intersections(self, list_handle):
        try:
            n = _capi.tree_ray_intersection_count(self._h, list_handle)
            results: list = []
            for i in range(n):
                rh = _capi.tree_ray_intersection_at(self._h, list_handle, i)
                if rh:
                    results.append(ray_intersection(rh))
            return tuple(results)
        finally:
            _capi.tree_ray_intersection_list_destroy(list_handle)

    def clash_intersection_many(
        self,
        set_a: Iterable,
        set_b: Iterable,
        tolerance: float = 0.002,
        check_all: bool = True,
    ):
        a_list = _instance_list_from(set_a)
        b_list = _instance_list_from(set_b)
        try:
            out = _capi.tree_clash_intersection_many(
                self._h, a_list, b_list,
                float(tolerance), bool(check_all),
            )
            if not out:
                raise RuntimeError(_last_error("clash_intersection_many failed"))
        finally:
            _capi.instance_list_destroy(a_list)
            _capi.instance_list_destroy(b_list)
        return self._collect_clashes(out)

    def clash_collision_many(
        self,
        set_a: Iterable,
        set_b: Iterable,
        allow_touching: bool = False,
    ):
        a_list = _instance_list_from(set_a)
        b_list = _instance_list_from(set_b)
        try:
            out = _capi.tree_clash_collision_many(
                self._h, a_list, b_list, bool(allow_touching),
            )
            if not out:
                raise RuntimeError(_last_error("clash_collision_many failed"))
        finally:
            _capi.instance_list_destroy(a_list)
            _capi.instance_list_destroy(b_list)
        return self._collect_clashes(out)

    def clash_clearance_many(
        self,
        set_a: Iterable,
        set_b: Iterable,
        clearance: float = 0.05,
        check_all: bool = False,
    ):
        a_list = _instance_list_from(set_a)
        b_list = _instance_list_from(set_b)
        try:
            out = _capi.tree_clash_clearance_many(
                self._h, a_list, b_list,
                float(clearance), bool(check_all),
            )
            if not out:
                raise RuntimeError(_last_error("clash_clearance_many failed"))
        finally:
            _capi.instance_list_destroy(a_list)
            _capi.instance_list_destroy(b_list)
        return self._collect_clashes(out)

    @staticmethod
    def get_clash_type(clash_type_i: int) -> str:
        return CLASH_TYPE_ITEMS[clash_type_i]


# ---------------------------------------------------------------------------
# Serializers (Y6F).
# ---------------------------------------------------------------------------


class buffer(_OwnedHandle):
    """In-memory or filename-backed serializer output sink.

    Mirrors upstream ``ifcopenshell_wrapper.buffer`` - the C++ serializers
    accept a ``stream_or_filename`` polymorphic type which Python has to
    construct explicitly via this wrapper.
    """

    _destroy_fn_name = "buffer_destroy"

    def __init__(self, filename: str | None = None):
        if filename is None:
            out = _capi.create_buffer()
        else:
            out = _capi.create_buffer_from_filename(str(filename))
        super().__init__(out)

    def get_value(self) -> str:
        result = _capi.buffer_get_value(self._h)
        if result is None:
            raise RuntimeError(_last_error("buffer.get_value failed"))
        return result

    def is_ready(self) -> bool:
        return bool(_capi.buffer_is_ready(self._h))


def transform_string(value):
    """Convert ``str`` to a :class:`buffer`; pass ``buffer`` through.

    The C++ serializers accept a ``stream_or_filename`` value that in C++
    auto-constructs from a string. Python needs an explicit conversion -
    upstream calls this helper before forwarding to the constructor.
    """
    if isinstance(value, str):
        return buffer(value)
    return value


def _serializer_handle(s):
    """Coerce a :class:`buffer`/handle/None into a native handle."""
    if s is None:
        return None
    if isinstance(s, _OwnedHandle):
        return s._h
    raise TypeError(f"expected buffer/serializer handle, got {type(s).__name__}")


class _SerializerBase(_OwnedHandle):
    """Base for serializers exposing the (non-geometry) base API.

    Concrete subclasses wrap one of the ``ifcopenshell_geom_serializer_t``
    or ``ifcopenshell_geom_geometry_serializer_t`` handle types.
    """

    _writes_geometry = False  # subclasses override

    def __init__(self, h, *, _keep=()):
        super().__init__(h)
        self._keep = _keep  # anchor referenced files/buffers

    def _fn_prefix(self) -> str:
        return (
            "geometry_serializer_"
            if self._writes_geometry
            else "serializer_"
        )

    def _call(self, suffix, *args):
        fn = getattr(_capi, self._fn_prefix() + suffix)
        fn(self._h, *args)

    def writeHeader(self) -> None:
        self._call("write_header")

    write_header = writeHeader

    def finalize(self) -> None:
        self._call("finalize")

    def setFile(self, f) -> None:
        ptr, owner = _file_native_ptr(f)
        self._call("set_file", ptr)
        self._keep = (self._keep, owner)

    set_file = setFile

    def ready(self) -> bool:
        fn = getattr(_capi, self._fn_prefix() + "ready")
        return bool(fn(self._h))


class GeometrySerializer(_SerializerBase):
    """Wraps ``ifcopenshell_geom_geometry_serializer_t``.

    Used for serializers that write per-element geometry (obj, svg, gltf,
    collada, hdf5, ttl, iges, step).
    """

    _destroy_fn_name = "geometry_serializer_destroy"
    _writes_geometry = True

    def write(self, element) -> None:
        if isinstance(element, BRepElement):
            self._call("write_brep_element", element._h)
        elif isinstance(element, TriangulationElement):
            self._call("write_triangulation_element", element._h)
        else:
            raise TypeError(
                f"GeometrySerializer.write: expected BRepElement or "
                f"TriangulationElement, got {type(element).__name__}"
            )

    def isTesselated(self) -> bool:
        fn = getattr(_capi, "geometry_serializer_is_tesselated")
        return bool(fn(self._h))

    is_tesselated = isTesselated

    def setUnitNameAndMagnitude(self, name: str, magnitude: float) -> None:
        self._call(
            "set_unit_name_and_magnitude",
            str(name),
            float(magnitude),
        )

    set_unit_name_and_magnitude = setUnitNameAndMagnitude


class Serializer(_SerializerBase):
    """Wraps ``ifcopenshell_geom_serializer_t`` (xml/json/rocksdb)."""

    _destroy_fn_name = "serializer_destroy"
    _writes_geometry = False


def _make_geometry_serializer(format, output, output_temp, geometry_settings, ser_settings):
    """Create a plugin serializer through an explicit path or stream API."""
    if isinstance(output, str) and isinstance(output_temp, str):
        out = _capi.create_geometry_serializer_by_path(
            format,
            output,
            output_temp,
            _serializer_handle(geometry_settings),
            _serializer_handle(ser_settings),
        )
        keep = (geometry_settings, ser_settings)
    else:
        output = transform_string(output)
        output_temp = transform_string(output_temp)
        out = _capi.create_geometry_serializer_by_stream(
            format,
            _serializer_handle(output),
            _serializer_handle(output_temp),
            _serializer_handle(geometry_settings),
            _serializer_handle(ser_settings),
        )
        keep = (output, output_temp, geometry_settings, ser_settings)
    return GeometrySerializer(out, _keep=keep)


def _make_filename_serializer(format, filename, geometry_settings, ser_settings):
    """Create a filename-backed :class:`GeometrySerializer`."""
    out = _capi.create_geometry_serializer_by_path(
        format,
        str(filename),
        "",
        _serializer_handle(geometry_settings),
        _serializer_handle(ser_settings),
    )
    return GeometrySerializer(out, _keep=(geometry_settings, ser_settings))


def _make_file_serializer(create_fn_name, file_or_filename, output_filename):
    """Create a base :class:`Serializer` (xml/json/rocksdb) bound to a file."""
    ptr, owner = _file_native_ptr(file_or_filename)
    fn = getattr(_capi, create_fn_name)
    out = fn(ptr, str(output_filename))
    return Serializer(out, _keep=(owner,))


class serializers:
    """Factory namespace for all output serializers.

    Mirrors upstream ``ifcopenshell.geom.serializers``. The C++ serializers
    accept a ``stream_or_filename`` value which Python represents as a
    :class:`buffer`; ``str`` arguments to the buffer-backed factories are
    converted automatically via :func:`transform_string`.
    """

    buffer = buffer

    @staticmethod
    def obj(out_filename, mtl_filename, geometry_settings, settings):
        return _make_geometry_serializer("obj", mtl_filename, out_filename, geometry_settings, settings)

    @staticmethod
    def svg(out_filename, geometry_settings, settings):
        return _make_geometry_serializer("svg", out_filename, out_filename, geometry_settings, settings)

    @staticmethod
    def ttl(out_filename, geometry_settings, settings):
        return _make_geometry_serializer("ttl", out_filename, out_filename, geometry_settings, settings)

    @staticmethod
    def gltf(out_filename, geometry_settings, settings):
        return _make_filename_serializer(
            "glb",
            out_filename, geometry_settings, settings,
        )

    @staticmethod
    def iges(out_filename, geometry_settings, settings):
        return _make_filename_serializer(
            "igs",
            out_filename, geometry_settings, settings,
        )

    @staticmethod
    def step(out_filename, geometry_settings, settings):
        return _make_filename_serializer(
            "stp",
            out_filename, geometry_settings, settings,
        )

    @staticmethod
    def collada(out_filename, geometry_settings, settings):
        return _make_filename_serializer(
            "dae",
            out_filename, geometry_settings, settings,
        )

    @staticmethod
    def hdf5(out_filename, geometry_settings, settings):
        return _make_filename_serializer(
            "hdf5",
            out_filename, geometry_settings, settings,
        )

    @staticmethod
    def xml(file_or_filename, out_filename):
        return _make_file_serializer(
            "create_xml_serializer",
            file_or_filename, out_filename,
        )

    @staticmethod
    def json(file_or_filename, out_filename):
        return _make_file_serializer(
            "create_json_serializer",
            file_or_filename, out_filename,
        )

    @staticmethod
    def rocksdb(file_or_filename, rocksdb_filename):
        if not isinstance(file_or_filename, (str, bytes, os.PathLike)):
            raise TypeError("rocksdb serializer requires an input filename")
        return serializers.rocksdb_streaming(file_or_filename, rocksdb_filename)

    @staticmethod
    def rocksdb_streaming(input_filename, rocksdb_filename, stream: bool = True):
        out = _capi.create_rocksdb_serializer_streaming(
            str(input_filename),
            str(rocksdb_filename),
        )
        return Serializer(out)

    @classmethod
    def guess_from_extension(cls, filepath: str):
        ext = filepath.rsplit(".", 1)[-1].lower()
        mapping = {
            "glb": "gltf",
            "gltf": "gltf",
            "hdf": "hdf5",
            "h5": "hdf5",
            "hdf5": "hdf5",
            "obj": "obj",
            "svg": "svg",
            "ttl": "ttl",
            "xml": "xml",
            "dae": "collada",
            "iges": "iges",
            "igs": "iges",
            "stp": "step",
            "step": "step",
            "json": "json",
        }
        name = mapping.get(ext)
        if not name:
            raise ValueError(f"No serializer available for .{ext} file")
        return getattr(cls, name)


def _schema_name_of(inst) -> str:
    """Return the schema name (e.g. ``"IFC4"``) owning ``inst``."""
    f = getattr(inst, "wrapped_data", None)
    if f is not None and hasattr(f, "file"):
        return f.file.schema
    f = getattr(inst, "file", None)
    if f is not None and hasattr(f, "schema"):
        return f.schema
    raise TypeError(
        f"_schema_name_of: cannot resolve schema for {type(inst).__name__}"
    )


def _wrap_serialise_result(h):
    """Promote a returned ``ifcopenshell_instance_t`` to an
    :class:`entity_instance` (or ``None``)."""
    if not h:
        return None
    from ifcopenshell.entity_instance import entity_instance
    return entity_instance(h)


def serialise(schema, string_or_shape, advanced: bool = True):
    """STEP-serialise ``string_or_shape`` against ``schema``.

    Wraps :c:func:`ifcopenshell_geom_serialise`. Accepts an OCC
    ``TopoDS_Shape`` only when OCC is available (matches upstream
    semantics).
    """
    if has_occ:
        try:
            from OCC.Core import TopoDS  # type: ignore[import-not-found]
            if isinstance(string_or_shape, TopoDS.TopoDS_Shape):
                from . import occ_utils as _utils  # type: ignore[import-not-found]
                string_or_shape = _utils.serialize_shape(string_or_shape)
        except ImportError:
            pass
    out = _capi.serialise(
        str(schema),
        str(string_or_shape),
        bool(advanced),
    )
    return _wrap_serialise_result(out)


def tesselate(schema, string_or_shape, deflection: float):
    """Tesselate ``string_or_shape`` against ``schema`` at ``deflection``.

    Wraps :c:func:`ifcopenshell_geom_tesselate`.
    """
    if has_occ:
        try:
            from OCC.Core import TopoDS  # type: ignore[import-not-found]
            if isinstance(string_or_shape, TopoDS.TopoDS_Shape):
                from . import occ_utils as _utils  # type: ignore[import-not-found]
                string_or_shape = _utils.serialize_shape(string_or_shape)
        except ImportError:
            pass
    out = _capi.tesselate(
        str(schema),
        str(string_or_shape),
        float(deflection),
    )
    return _wrap_serialise_result(out)


def make_shape_function(fn):
    """Adapt an underlying ``serialise``/``tesselate``-style function
    so that callers may pass either a string or (when OCC is available)
    a ``TopoDS_Shape``.

    The wrapped function already accepts both forms - this exists for
    upstream API parity (``serialise``/``tesselate`` are exposed as the
    result of ``make_shape_function(...)`` in legacy code).
    """
    return fn


__all__ = [
    "GEOMETRY_LIBRARY",
    "NATIVE",
    "SERIALIZED",
    "SERIALIZER_SETTING",
    "SETTING",
    "TRIANGULATED",
    "BRepElement",
    "BRepRepresentation",
    "Element",
    "GeometrySerializer",
    "Serialization",
    "SerializedElement",
    "Serializer",
    "ShapeElementType",
    "ShapeType",
    "SurfaceStyle",
    "TaxonomyColour",
    "TaxonomyStyle",
    "Transformation",
    "Triangulation",
    "TriangulationElement",
    "buffer",
    "consume_iterator",
    "create_shape",
    "has_occ",
    "iterate",
    "iterator",
    "make_shape_function",
    "map_shape",
    "missing_setting",
    "serialise",
    "serializer_settings",
    "serializers",
    "settings",
    "settings_mixin",
    "tesselate",
    "transform_string",
    "tree",
    "wrap_shape_creation",
]
