# This file was generated with the assistance of an AI coding tool.
#
# Generate the WASM plugin manifest from entries passed via IFCOPENSHELL_WASM_PLUGIN_ENTRIES.
# Plugin artifacts are copied to IFCOPENSHELL_WASM_PLUGINS_DIR by per-target POST_BUILD
# commands; this script only writes the JSON manifest.

if(NOT DEFINED IFCOPENSHELL_WASM_PLUGINS_JSON)
    message(FATAL_ERROR "IFCOPENSHELL_WASM_PLUGINS_JSON is required")
endif()
if(NOT DEFINED IFCOPENSHELL_WASM_PLUGIN_ENTRIES)
    set(IFCOPENSHELL_WASM_PLUGIN_ENTRIES "")
endif()

string(REPLACE "@" ";" plugin_entry_list "${IFCOPENSHELL_WASM_PLUGIN_ENTRIES}")

set(manifest_content "{\n")
set(first_kind TRUE)
foreach(kind IN ITEMS schema kernel tree mapping document geometry_serializer)
    set(kind_entries "")
    foreach(entry IN LISTS plugin_entry_list)
        if(NOT entry MATCHES "^[^|]+\\|[^|]+\\|")
            continue()
        endif()
        string(REPLACE "|" ";" entry_parts "${entry}")
        list(GET entry_parts 0 entry_kind)
        if(NOT entry_kind STREQUAL kind)
            continue()
        endif()
        list(APPEND kind_entries "${entry}")
    endforeach()
    if(NOT kind_entries)
        continue()
    endif()
    if(NOT first_kind)
        string(APPEND manifest_content ",\n")
    endif()
    set(first_kind FALSE)
    string(APPEND manifest_content "  \"${kind}\": {\n")
    set(first_id TRUE)
    foreach(entry IN LISTS kind_entries)
        string(REPLACE "|" ";" entry_parts "${entry}")
        list(GET entry_parts 1 plugin_id)
        list(GET entry_parts 2 output_name)
        if(NOT first_id)
            string(APPEND manifest_content ",\n")
        endif()
        set(first_id FALSE)
        string(APPEND manifest_content "    \"${plugin_id}\": {\"wasm\": \"plugins/${output_name}.wasm\"}")
    endforeach()
    string(APPEND manifest_content "\n  }")
endforeach()
if(NOT first_kind)
    string(APPEND manifest_content "\n")
endif()
string(APPEND manifest_content "}\n")
file(WRITE "${IFCOPENSHELL_WASM_PLUGINS_JSON}" "${manifest_content}")
