# Auto-generated by python_extension_backend.py. Do not edit.
# SPDX-License-Identifier: LGPL-3.0-or-later

from __future__ import annotations

import ifcopenshell
from . import _ifcopenshell_capi as _capi


def file_handle(file):
    return file._handle


def instance_handle(entity):
    return entity._handle if entity is not None else None


def instance_list(entities):
    return [entity._handle for entity in entities]


def wrap_handle(file, handle):
    return ifcopenshell.entity_instance(file, handle) if handle else None


_ERROR_KIND_TO_EXC = {
    _capi.IFCOPENSHELL_ERROR_VALUE: ValueError,
    _capi.IFCOPENSHELL_ERROR_TYPE: TypeError,
    _capi.IFCOPENSHELL_ERROR_NOT_IMPLEMENTED: NotImplementedError,
    _capi.IFCOPENSHELL_ERROR_KEY: KeyError,
}


def raise_last_error(default_msg):
    msg = _capi.last_error_message() or default_msg
    kind = _capi.last_error_kind()
    raise _ERROR_KIND_TO_EXC.get(kind, RuntimeError)(msg)


def call_handle(file, fn_name, *args, nullable=False, message=None):
    fn = getattr(_capi, fn_name)
    handle = fn(*args)
    if handle:
        return ifcopenshell.entity_instance(file, handle)
    if nullable and _capi.last_error_kind() == _capi.IFCOPENSHELL_ERROR_NONE:
        return None
    raise_last_error(message or f"{fn_name} failed")


def call_status(fn_name, *args):
    getattr(_capi, fn_name)(*args)


def call_handle_list(file, fn_name, *args):
    handles = getattr(_capi, fn_name)(*args)
    return [ifcopenshell.entity_instance(file, h) for h in handles]


def owner_context(file):
    import ifcopenshell.api.owner.settings

    return (
        None,
        ifcopenshell.api.owner.settings.get_user(file),
        ifcopenshell.api.owner.settings.get_application(file),
    )
