# SPDX-License-Identifier: LGPL-3.0-or-later
"""SWIG-compatible facade for schema introspection backed by ifcapi C API.

Presents the same object shape as the original
``ifcopenshell.ifcopenshell_wrapper`` SWIG module (attribute, parameter_type,
declaration, entity, type_declaration, select_type, enumeration_type,
named_type, simple_type, aggregation_type, inverse_attribute,
schema_definition).

Internally this module binds to the autogenerated C ABI emitted by
``src/ifcwrap/binding_generator`` (``ifcopenshell_ifc_*`` functions) so that
schema-introspection logic has a single C++ call site (the IfcParse::* layer
reached through the autogen's struct-handle wrappers). Each Python class wraps
a heap-allocated handle struct of the form ``{ void* ptr; bool owned; }`` and
calls the matching ``*_destroy`` function on garbage collection. The
underlying C++ schema objects live for the process lifetime, so destroy here
only frees the small handle wrapper.

For interop with our hand-written ``ifcopenshell_util_*`` C ABI (which still
takes raw ``IfcParse::*`` pointers), the base ``_Handle`` exposes a ``_ptr``
property that returns a ``c_void_p`` pointing at that underlying C++ object
(extracted from the first field of the wrapper struct).

Also provides a couple of stubs (map_shape, function_item_evaluator,
helmert_curve_point, convert_loop_to_function_item) used by alignment
fallbacks that don't have a native geometry backend.
"""

from __future__ import annotations

import ctypes
from ctypes import (
    POINTER,
    Structure,
    byref,
    c_bool,
    c_char_p,
    c_double,
    c_int32,
    c_size_t,
    c_void_p,
)
from typing import Optional

import ifcopenshell


# ---------------------------------------------------------------------------
# C ABI value types (autogen)
# ---------------------------------------------------------------------------


class ifcopenshell_string_t(Structure):
    _fields_ = [("data", c_void_p), ("size", c_size_t), ("owned", c_bool)]


class ifcopenshell_string_list_t(Structure):
    _fields_ = [("items", POINTER(ifcopenshell_string_t)), ("size", c_size_t)]


class ifcopenshell_bool_list_t(Structure):
    _fields_ = [("items", POINTER(c_bool)), ("size", c_size_t)]


class _HandleStruct(Structure):
    """Layout of every ``ifcopenshell_ifc_*_t`` handle in the autogen ABI:
    ``{ void* ptr; bool owned; }``. We only need to read ``ptr`` from Python."""

    _fields_ = [("ptr", c_void_p), ("owned", c_bool)]


_HandleStructP = POINTER(_HandleStruct)


def _make_list_t(name):
    return type(
        name,
        (Structure,),
        {"_fields_": [("items", POINTER(_HandleStructP)), ("size", c_size_t)]},
    )


ifcopenshell_ifc_entity_list_t = _make_list_t("ifcopenshell_ifc_entity_list_t")
ifcopenshell_ifc_attribute_list_t = _make_list_t("ifcopenshell_ifc_attribute_list_t")
ifcopenshell_ifc_inverse_attribute_list_t = _make_list_t(
    "ifcopenshell_ifc_inverse_attribute_list_t"
)
ifcopenshell_ifc_declaration_list_t = _make_list_t("ifcopenshell_ifc_declaration_list_t")


# ---------------------------------------------------------------------------
# ctypes signature binding (lazy, once)
# ---------------------------------------------------------------------------

_bound = False


def _bind():
    global _bound
    lib = ifcopenshell._get_lib()
    if _bound:
        return lib

    H = _HandleStructP
    HH = POINTER(_HandleStructP)
    cstr = c_char_p
    Sp = POINTER(ifcopenshell_string_t)
    SLp = POINTER(ifcopenshell_string_list_t)
    BLp = POINTER(ifcopenshell_bool_list_t)
    Ep = POINTER(ifcopenshell_ifc_entity_list_t)
    Ap = POINTER(ifcopenshell_ifc_attribute_list_t)
    Ip = POINTER(ifcopenshell_ifc_inverse_attribute_list_t)
    Dp = POINTER(ifcopenshell_ifc_declaration_list_t)

    sigs = {
        # destroy
        "ifcopenshell_string_destroy": (None, [Sp]),
        "ifcopenshell_string_list_destroy": (None, [SLp]),
        "ifcopenshell_bool_list_destroy": (None, [BLp]),
        "ifcopenshell_ifc_entity_destroy": (None, [H]),
        "ifcopenshell_ifc_attribute_destroy": (None, [H]),
        "ifcopenshell_ifc_inverse_attribute_destroy": (None, [H]),
        "ifcopenshell_ifc_declaration_destroy": (None, [H]),
        "ifcopenshell_ifc_type_declaration_destroy": (None, [H]),
        "ifcopenshell_ifc_select_type_destroy": (None, [H]),
        "ifcopenshell_ifc_enumeration_destroy": (None, [H]),
        "ifcopenshell_ifc_parameter_type_destroy": (None, [H]),
        "ifcopenshell_ifc_named_type_destroy": (None, [H]),
        "ifcopenshell_ifc_simple_type_destroy": (None, [H]),
        "ifcopenshell_ifc_aggregation_type_destroy": (None, [H]),
        "ifcopenshell_ifc_schema_destroy": (None, [H]),
        "ifcopenshell_ifc_entity_list_destroy": (None, [Ep]),
        "ifcopenshell_ifc_attribute_list_destroy": (None, [Ap]),
        "ifcopenshell_ifc_inverse_attribute_list_destroy": (None, [Ip]),
        "ifcopenshell_ifc_declaration_list_destroy": (None, [Dp]),
        # schema lookup / file -> schema
        "ifcopenshell_ifcparse_clear_schemas": (c_bool, []),
        "ifcopenshell_ifcparse_register_schema": (c_bool, [H]),
        "ifcopenshell_ifcparse_schema_by_name": (c_bool, [cstr, HH]),
        "ifcopenshell_ifcparse_schema_names": (c_bool, [SLp]),
        # schema
        "ifcopenshell_ifc_schema_name": (c_bool, [H, Sp]),
        "ifcopenshell_ifc_schema_declaration_by_name": (c_bool, [H, cstr, HH]),
        "ifcopenshell_ifc_schema_declarations": (c_bool, [H, Dp]),
        # declaration
        "ifcopenshell_ifc_declaration_name": (c_bool, [H, Sp]),
        "ifcopenshell_ifc_declaration_is_a": (c_bool, [H, cstr, POINTER(c_bool)]),
        "ifcopenshell_ifc_declaration_as_entity": (c_bool, [H, HH]),
        "ifcopenshell_ifc_declaration_as_type_declaration": (c_bool, [H, HH]),
        "ifcopenshell_ifc_declaration_as_select_type": (c_bool, [H, HH]),
        "ifcopenshell_ifc_declaration_as_enumeration_type": (c_bool, [H, HH]),
        "ifcopenshell_ifc_declaration_schema": (c_bool, [H, HH]),
        "ifcopenshell_ifc_declaration_index_in_schema": (c_bool, [H, POINTER(c_int32)]),
        # entity
        "ifcopenshell_ifc_entity_is_abstract": (c_bool, [H, POINTER(c_bool)]),
        "ifcopenshell_ifc_entity_supertype": (c_bool, [H, HH]),
        "ifcopenshell_ifc_entity_subtypes": (c_bool, [H, Ep]),
        "ifcopenshell_ifc_entity_attribute_count": (c_bool, [H, POINTER(c_size_t)]),
        "ifcopenshell_ifc_entity_attribute_by_index": (c_bool, [H, c_size_t, HH]),
        "ifcopenshell_ifc_entity_attribute_index": (c_bool, [H, cstr, POINTER(c_size_t)]),
        "ifcopenshell_ifc_entity_attributes": (c_bool, [H, Ap]),
        "ifcopenshell_ifc_entity_derived": (c_bool, [H, BLp]),
        "ifcopenshell_ifc_entity_all_attributes": (c_bool, [H, Ap]),
        "ifcopenshell_ifc_entity_all_inverse_attributes": (c_bool, [H, Ip]),
        # instance -> declaration (used to look up header-section schema)
        "ifcopenshell_ifc_instance_declaration": (c_bool, [H, HH]),
        # logging
        "ifcopenshell_ifcparse_get_log": (c_bool, [Sp]),
        "ifcopenshell_ifcparse_set_log_format_json": (c_bool, []),
        "ifcopenshell_ifcparse_set_log_format_text": (c_bool, []),
        "ifcopenshell_ifcparse_turn_on_detailed_logging": (c_bool, []),
        "ifcopenshell_ifcparse_turn_off_detailed_logging": (c_bool, []),
        # type/select/enum
        "ifcopenshell_ifc_type_declaration_declared_type": (c_bool, [H, HH]),
        "ifcopenshell_ifc_select_type_select_list": (c_bool, [H, Dp]),
        "ifcopenshell_ifc_enumeration_enumeration_items": (c_bool, [H, SLp]),
        # parameter_type / variants
        "ifcopenshell_ifc_parameter_type_as_named_type": (c_bool, [H, HH]),
        "ifcopenshell_ifc_parameter_type_as_simple_type": (c_bool, [H, HH]),
        "ifcopenshell_ifc_parameter_type_as_aggregation_type": (c_bool, [H, HH]),
        "ifcopenshell_ifc_named_type_declared_type": (c_bool, [H, HH]),
        "ifcopenshell_ifc_simple_type_declared_type": (c_bool, [H, POINTER(c_int32)]),
        "ifcopenshell_ifc_aggregation_type_type_of_aggregation": (c_bool, [H, POINTER(c_int32)]),
        "ifcopenshell_ifc_aggregation_type_bound1": (c_bool, [H, POINTER(c_int32)]),
        "ifcopenshell_ifc_aggregation_type_bound2": (c_bool, [H, POINTER(c_int32)]),
        "ifcopenshell_ifc_aggregation_type_type_of_element": (c_bool, [H, HH]),
        # attribute
        "ifcopenshell_ifc_attribute_name": (c_bool, [H, Sp]),
        "ifcopenshell_ifc_attribute_optional": (c_bool, [H, POINTER(c_bool)]),
        "ifcopenshell_ifc_attribute_type_of_attribute": (c_bool, [H, HH]),
        # inverse_attribute
        "ifcopenshell_ifc_inverse_attribute_name": (c_bool, [H, Sp]),
        "ifcopenshell_ifc_inverse_attribute_type_of_aggregation": (c_bool, [H, POINTER(c_int32)]),
        "ifcopenshell_ifc_inverse_attribute_bound1": (c_bool, [H, POINTER(c_int32)]),
        "ifcopenshell_ifc_inverse_attribute_bound2": (c_bool, [H, POINTER(c_int32)]),
        "ifcopenshell_ifc_inverse_attribute_entity_reference": (c_bool, [H, HH]),
        "ifcopenshell_ifc_inverse_attribute_attribute_reference": (c_bool, [H, HH]),
    }
    for name, (restype, argtypes) in sigs.items():
        fn = getattr(lib, name)
        fn.restype = restype
        fn.argtypes = argtypes
    _bound = True
    return lib


# ---------------------------------------------------------------------------
# Constants (parity with the SWIG enums)
# ---------------------------------------------------------------------------

_SIMPLE_NAMES = {
    0: "binary",
    1: "boolean",
    2: "integer",
    3: "logical",
    4: "number",
    5: "real",
    6: "string",
}

_AGG_NAMES = {0: "array", 1: "bag", 2: "list", 3: "set"}
_INV_AGG_NAMES = {0: "bag", 1: "set", 2: ""}


# ---------------------------------------------------------------------------
# Out-pointer helpers
# ---------------------------------------------------------------------------


def _take_string(s: ifcopenshell_string_t) -> str:
    """Decode and free an ``ifcopenshell_string_t`` produced by the C ABI."""
    try:
        if s.data and s.size:
            return ctypes.string_at(s.data, s.size).decode("utf-8")
        return ""
    finally:
        _bind().ifcopenshell_string_destroy(byref(s))


def _take_string_list(lst: ifcopenshell_string_list_t) -> tuple:
    try:
        out = []
        for i in range(lst.size):
            item = lst.items[i]
            if item.data and item.size:
                out.append(ctypes.string_at(item.data, item.size).decode("utf-8"))
            else:
                out.append("")
        return tuple(out)
    finally:
        _bind().ifcopenshell_string_list_destroy(byref(lst))


def _take_bool_list(lst: ifcopenshell_bool_list_t) -> tuple:
    try:
        return tuple(bool(lst.items[i]) for i in range(lst.size))
    finally:
        _bind().ifcopenshell_bool_list_destroy(byref(lst))


def _move_handle_list(lst, destroy_list_fn, wrap):
    """Take ownership of items in ``lst``, returning a tuple of wrapped handles.

    ctypes returns *live* references when subscripting an array, so we must
    capture each item's address as a Python ``int`` before nullifying the
    slot - otherwise the variable still aliases the (now-NULL) array entry
    and segfaults on dereference.
    """
    try:
        moved_addrs = []
        null = _HandleStructP()
        for i in range(lst.size):
            slot = lst.items[i]
            addr = ctypes.addressof(slot.contents) if slot else 0
            moved_addrs.append(addr)
            lst.items[i] = null
        return tuple(
            wrap(ctypes.cast(c_void_p(a), _HandleStructP) if a else _HandleStructP())
            for a in moved_addrs
        )
    finally:
        destroy_list_fn(byref(lst))


# ---------------------------------------------------------------------------
# Handle base
# ---------------------------------------------------------------------------


class _Handle:
    __slots__ = ("_h",)
    _destroy_fn_name: Optional[str] = None

    def __init__(self, h):
        # Accept POINTER(_HandleStruct), c_void_p, int, or None.
        if h is None:
            self._h = _HandleStructP()
        elif isinstance(h, _HandleStructP):
            self._h = h
        elif isinstance(h, c_void_p):
            self._h = ctypes.cast(h, _HandleStructP) if h.value else _HandleStructP()
        elif isinstance(h, int):
            self._h = ctypes.cast(c_void_p(h), _HandleStructP) if h else _HandleStructP()
        else:
            self._h = h

    def __del__(self):
        try:
            h = self._h
        except Exception:
            return
        try:
            if h and self._destroy_fn_name:
                lib = ifcopenshell._get_lib()
                getattr(lib, self._destroy_fn_name)(h)
        except Exception:
            pass

    def __bool__(self) -> bool:
        try:
            return bool(self._h) and bool(self._h.contents.ptr)
        except (ValueError, AttributeError):
            return False

    @property
    def _cppptr(self) -> int:
        try:
            if not self._h:
                return 0
            return self._h.contents.ptr or 0
        except (ValueError, AttributeError):
            return 0

    @property
    def _ptr(self):
        """Return the inner ``IfcParse::*`` C++ pointer as a ``c_void_p``.

        Used by interop with our hand-written ``ifcopenshell_util_*`` C ABI
        (e.g. ``util.attribute.get_primitive_type``) which takes the raw
        C++ pointer directly rather than the autogen handle struct.
        """
        return c_void_p(self._cppptr)

    def __eq__(self, other) -> bool:
        return isinstance(other, _Handle) and self._cppptr == other._cppptr

    def __hash__(self) -> int:
        return self._cppptr or 0


def _opt_handle(out, destroy_fn, ctor):
    """Wrap an out-handle if it has a non-null inner pointer; else free it."""
    if out and out.contents.ptr:
        return ctor(out)
    if out:
        destroy_fn(out)
    return None


# ---------------------------------------------------------------------------
# Polymorphic dispatch helpers
# ---------------------------------------------------------------------------


def _wrap_decl(h):
    """Specialise a declaration handle into entity/type/select/enum if applicable.

    ``h`` is consumed: caller must not destroy it. Returned wrapper either
    takes ownership of ``h`` (as ``declaration``) or, for the polymorphic
    variants, we destroy ``h`` after constructing a typed handle from it.
    """
    if not isinstance(h, _HandleStructP):
        if h is None or (isinstance(h, c_void_p) and not h.value):
            return None
        h = ctypes.cast(c_void_p(int(h)) if not isinstance(h, c_void_p) else h, _HandleStructP)
    if not h or not h.contents.ptr:
        if h:
            ifcopenshell._get_lib().ifcopenshell_ifc_declaration_destroy(h)
        return None
    lib = _bind()
    out = _HandleStructP()
    if lib.ifcopenshell_ifc_declaration_as_entity(h, byref(out)) and out and out.contents.ptr:
        lib.ifcopenshell_ifc_declaration_destroy(h)
        return entity(out)
    if out:
        lib.ifcopenshell_ifc_entity_destroy(out)
    out = _HandleStructP()
    if (
        lib.ifcopenshell_ifc_declaration_as_type_declaration(h, byref(out))
        and out
        and out.contents.ptr
    ):
        lib.ifcopenshell_ifc_declaration_destroy(h)
        return type_declaration(out)
    if out:
        lib.ifcopenshell_ifc_type_declaration_destroy(out)
    out = _HandleStructP()
    if (
        lib.ifcopenshell_ifc_declaration_as_select_type(h, byref(out))
        and out
        and out.contents.ptr
    ):
        lib.ifcopenshell_ifc_declaration_destroy(h)
        return select_type(out)
    if out:
        lib.ifcopenshell_ifc_select_type_destroy(out)
    out = _HandleStructP()
    if (
        lib.ifcopenshell_ifc_declaration_as_enumeration_type(h, byref(out))
        and out
        and out.contents.ptr
    ):
        lib.ifcopenshell_ifc_declaration_destroy(h)
        return enumeration_type(out)
    if out:
        lib.ifcopenshell_ifc_enumeration_destroy(out)
    return declaration(h)


def _wrap_parameter_type(h):
    """Specialise a parameter_type handle into named/simple/aggregation."""
    if not isinstance(h, _HandleStructP):
        if h is None or (isinstance(h, c_void_p) and not h.value):
            return None
        h = ctypes.cast(c_void_p(int(h)) if not isinstance(h, c_void_p) else h, _HandleStructP)
    if not h or not h.contents.ptr:
        if h:
            ifcopenshell._get_lib().ifcopenshell_ifc_parameter_type_destroy(h)
        return None
    lib = _bind()
    out = _HandleStructP()
    if (
        lib.ifcopenshell_ifc_parameter_type_as_named_type(h, byref(out))
        and out
        and out.contents.ptr
    ):
        lib.ifcopenshell_ifc_parameter_type_destroy(h)
        return named_type(out)
    if out:
        lib.ifcopenshell_ifc_named_type_destroy(out)
    out = _HandleStructP()
    if (
        lib.ifcopenshell_ifc_parameter_type_as_simple_type(h, byref(out))
        and out
        and out.contents.ptr
    ):
        lib.ifcopenshell_ifc_parameter_type_destroy(h)
        return simple_type(out)
    if out:
        lib.ifcopenshell_ifc_simple_type_destroy(out)
    out = _HandleStructP()
    if (
        lib.ifcopenshell_ifc_parameter_type_as_aggregation_type(h, byref(out))
        and out
        and out.contents.ptr
    ):
        lib.ifcopenshell_ifc_parameter_type_destroy(h)
        return aggregation_type(out)
    if out:
        lib.ifcopenshell_ifc_aggregation_type_destroy(out)
    return parameter_type(h)


# ---------------------------------------------------------------------------
# parameter_type hierarchy
# ---------------------------------------------------------------------------


class parameter_type(_Handle):
    _destroy_fn_name = "ifcopenshell_ifc_parameter_type_destroy"

    def as_named_type(self) -> Optional["named_type"]:
        out = _HandleStructP()
        if not _bind().ifcopenshell_ifc_parameter_type_as_named_type(self._h, byref(out)):
            return None
        return _opt_handle(out, _bind().ifcopenshell_ifc_named_type_destroy, named_type)

    def as_simple_type(self) -> Optional["simple_type"]:
        out = _HandleStructP()
        if not _bind().ifcopenshell_ifc_parameter_type_as_simple_type(self._h, byref(out)):
            return None
        return _opt_handle(out, _bind().ifcopenshell_ifc_simple_type_destroy, simple_type)

    def as_aggregation_type(self) -> Optional["aggregation_type"]:
        out = _HandleStructP()
        if not _bind().ifcopenshell_ifc_parameter_type_as_aggregation_type(self._h, byref(out)):
            return None
        return _opt_handle(out, _bind().ifcopenshell_ifc_aggregation_type_destroy, aggregation_type)

    def __repr__(self) -> str:
        for cast in (self.as_named_type, self.as_simple_type, self.as_aggregation_type):
            v = cast()
            if v is not None:
                return repr(v)
        return "<?>"

    __str__ = __repr__


class named_type(parameter_type):
    _destroy_fn_name = "ifcopenshell_ifc_named_type_destroy"

    def declared_type(self) -> Optional["declaration"]:
        out = _HandleStructP()
        if not _bind().ifcopenshell_ifc_named_type_declared_type(self._h, byref(out)):
            return None
        return _wrap_decl(out)

    def __repr__(self) -> str:
        d = self.declared_type()
        return repr(d) if d is not None else "<?>"

    __str__ = __repr__


class simple_type(parameter_type):
    _destroy_fn_name = "ifcopenshell_ifc_simple_type_destroy"

    def declared_type(self) -> str:
        v = c_int32(-1)
        if not _bind().ifcopenshell_ifc_simple_type_declared_type(self._h, byref(v)):
            return ""
        return _SIMPLE_NAMES.get(v.value, "")

    def __repr__(self) -> str:
        return "<%s>" % self.declared_type()

    __str__ = __repr__


class aggregation_type(parameter_type):
    _destroy_fn_name = "ifcopenshell_ifc_aggregation_type_destroy"

    def type_of_aggregation(self) -> int:
        v = c_int32(-1)
        if not _bind().ifcopenshell_ifc_aggregation_type_type_of_aggregation(self._h, byref(v)):
            return -1
        return int(v.value)

    def type_of_aggregation_string(self) -> str:
        return _AGG_NAMES.get(self.type_of_aggregation(), "")

    def bound1(self) -> int:
        v = c_int32(-1)
        if not _bind().ifcopenshell_ifc_aggregation_type_bound1(self._h, byref(v)):
            return -1
        return int(v.value)

    def bound2(self) -> int:
        v = c_int32(-1)
        if not _bind().ifcopenshell_ifc_aggregation_type_bound2(self._h, byref(v)):
            return -1
        return int(v.value)

    def type_of_element(self) -> Optional[parameter_type]:
        out = _HandleStructP()
        if not _bind().ifcopenshell_ifc_aggregation_type_type_of_element(self._h, byref(out)):
            return None
        return _wrap_parameter_type(out)

    def __repr__(self) -> str:
        fmt = lambda i: "?" if i == -1 else str(i)
        return "<%s [%s:%s] of %r>" % (
            self.type_of_aggregation_string(),
            fmt(self.bound1()),
            fmt(self.bound2()),
            self.type_of_element(),
        )

    __str__ = __repr__


# ---------------------------------------------------------------------------
# declaration hierarchy
# ---------------------------------------------------------------------------


class declaration(_Handle):
    _destroy_fn_name = "ifcopenshell_ifc_declaration_destroy"

    def name(self) -> str:
        s = ifcopenshell_string_t()
        if not _bind().ifcopenshell_ifc_declaration_name(self._h, byref(s)):
            return ""
        return _take_string(s)

    def is_(self, name: str) -> bool:
        v = c_bool(False)
        if not _bind().ifcopenshell_ifc_declaration_is_a(self._h, name.encode("utf-8"), byref(v)):
            return False
        return bool(v.value)

    # Upstream SWIG renames the C++ `is(...)` method to `_is(...)` in Python.
    _is = is_

    # SWIG exposes the method as `is()` but that's a Python keyword; the real
    # SWIG wrapper works because SWIG renames it. Provide both spellings.
    def __getattr__(self, name):
        if name == "is":
            return self.is_
        raise AttributeError(name)

    def as_entity(self) -> Optional["entity"]:
        out = _HandleStructP()
        if not _bind().ifcopenshell_ifc_declaration_as_entity(self._h, byref(out)):
            return None
        return _opt_handle(out, _bind().ifcopenshell_ifc_entity_destroy, entity)

    def as_type_declaration(self) -> Optional["type_declaration"]:
        out = _HandleStructP()
        if not _bind().ifcopenshell_ifc_declaration_as_type_declaration(self._h, byref(out)):
            return None
        return _opt_handle(out, _bind().ifcopenshell_ifc_type_declaration_destroy, type_declaration)

    def as_select_type(self) -> Optional["select_type"]:
        out = _HandleStructP()
        if not _bind().ifcopenshell_ifc_declaration_as_select_type(self._h, byref(out)):
            return None
        return _opt_handle(out, _bind().ifcopenshell_ifc_select_type_destroy, select_type)

    def as_enumeration_type(self) -> Optional["enumeration_type"]:
        out = _HandleStructP()
        if not _bind().ifcopenshell_ifc_declaration_as_enumeration_type(self._h, byref(out)):
            return None
        return _opt_handle(out, _bind().ifcopenshell_ifc_enumeration_destroy, enumeration_type)

    def schema(self) -> Optional["schema_definition"]:
        out = _HandleStructP()
        if not _bind().ifcopenshell_ifc_declaration_schema(self._h, byref(out)):
            return None
        return _opt_handle(out, _bind().ifcopenshell_ifc_schema_destroy, schema_definition)

    def index_in_schema(self) -> int:
        out = c_int32(-1)
        if not _bind().ifcopenshell_ifc_declaration_index_in_schema(self._h, byref(out)):
            return -1
        return int(out.value)

    def __repr__(self) -> str:
        return "<entity %s>" % self.name() if self.as_entity() else "<declaration %s>" % self.name()


class entity(declaration):
    _destroy_fn_name = "ifcopenshell_ifc_entity_destroy"

    def is_abstract(self) -> bool:
        v = c_bool(False)
        if not _bind().ifcopenshell_ifc_entity_is_abstract(self._h, byref(v)):
            return False
        return bool(v.value)

    def supertype(self) -> Optional["entity"]:
        out = _HandleStructP()
        if not _bind().ifcopenshell_ifc_entity_supertype(self._h, byref(out)):
            return None
        return _opt_handle(out, _bind().ifcopenshell_ifc_entity_destroy, entity)

    def subtypes(self) -> tuple:
        lst = ifcopenshell_ifc_entity_list_t()
        if not _bind().ifcopenshell_ifc_entity_subtypes(self._h, byref(lst)):
            return ()
        return _move_handle_list(lst, _bind().ifcopenshell_ifc_entity_list_destroy, entity)

    def attribute_count(self) -> int:
        v = c_size_t(0)
        if not _bind().ifcopenshell_ifc_entity_attribute_count(self._h, byref(v)):
            return 0
        return int(v.value)

    def attributes(self) -> tuple:
        """This entity's own declared attributes (not inherited)."""
        lst = ifcopenshell_ifc_attribute_list_t()
        if not _bind().ifcopenshell_ifc_entity_attributes(self._h, byref(lst)):
            return ()
        return _move_handle_list(lst, _bind().ifcopenshell_ifc_attribute_list_destroy, attribute)

    def attribute_by_index(self, index: int) -> Optional["attribute"]:
        out = _HandleStructP()
        if not _bind().ifcopenshell_ifc_entity_attribute_by_index(
            self._h, c_size_t(index), byref(out)
        ):
            return None
        return _opt_handle(out, _bind().ifcopenshell_ifc_attribute_destroy, attribute)

    def attribute_index(self, name: str) -> int:
        v = c_size_t(0)
        if not _bind().ifcopenshell_ifc_entity_attribute_index(
            self._h, name.encode("utf-8"), byref(v)
        ):
            return -1
        return int(v.value)

    def all_attributes(self) -> tuple:
        lst = ifcopenshell_ifc_attribute_list_t()
        if not _bind().ifcopenshell_ifc_entity_all_attributes(self._h, byref(lst)):
            return ()
        return _move_handle_list(lst, _bind().ifcopenshell_ifc_attribute_list_destroy, attribute)

    def all_inverse_attributes(self) -> tuple:
        lst = ifcopenshell_ifc_inverse_attribute_list_t()
        if not _bind().ifcopenshell_ifc_entity_all_inverse_attributes(self._h, byref(lst)):
            return ()
        return _move_handle_list(
            lst, _bind().ifcopenshell_ifc_inverse_attribute_list_destroy, inverse_attribute
        )

    def derived(self) -> tuple:
        own = ifcopenshell_bool_list_t()
        if not _bind().ifcopenshell_ifc_entity_derived(self._h, byref(own)):
            own_derived = ()
        else:
            own_derived = _take_bool_list(own)
        if len(own_derived) == len(self.all_attributes()):
            return own_derived
        supertype = self.supertype()
        return (supertype.derived() if supertype is not None else ()) + own_derived

    def __repr__(self) -> str:
        return "<entity %s>" % self.name()


class type_declaration(declaration):
    _destroy_fn_name = "ifcopenshell_ifc_type_declaration_destroy"

    def declared_type(self) -> Optional[parameter_type]:
        out = _HandleStructP()
        if not _bind().ifcopenshell_ifc_type_declaration_declared_type(self._h, byref(out)):
            return None
        return _wrap_parameter_type(out)

    def __repr__(self) -> str:
        return "<type %s: %r>" % (self.name(), self.declared_type())


class enumeration_type(declaration):
    _destroy_fn_name = "ifcopenshell_ifc_enumeration_destroy"

    def enumeration_items(self) -> tuple:
        lst = ifcopenshell_string_list_t()
        if not _bind().ifcopenshell_ifc_enumeration_enumeration_items(self._h, byref(lst)):
            return ()
        return _take_string_list(lst)

    def __repr__(self) -> str:
        return "<enumeration %s: (%s)>" % (self.name(), ", ".join(self.enumeration_items()))


class select_type(declaration):
    _destroy_fn_name = "ifcopenshell_ifc_select_type_destroy"

    def select_list(self) -> tuple:
        lst = ifcopenshell_ifc_declaration_list_t()
        if not _bind().ifcopenshell_ifc_select_type_select_list(self._h, byref(lst)):
            return ()
        return _move_handle_list(
            lst, _bind().ifcopenshell_ifc_declaration_list_destroy, _wrap_decl
        )

    def __repr__(self) -> str:
        return "<select %s: (%s)>" % (self.name(), " | ".join(map(repr, self.select_list())))


class attribute(_Handle):
    _destroy_fn_name = "ifcopenshell_ifc_attribute_destroy"

    def name(self) -> str:
        s = ifcopenshell_string_t()
        if not _bind().ifcopenshell_ifc_attribute_name(self._h, byref(s)):
            return ""
        return _take_string(s)

    def optional(self) -> bool:
        v = c_bool(False)
        if not _bind().ifcopenshell_ifc_attribute_optional(self._h, byref(v)):
            return False
        return bool(v.value)

    def type_of_attribute(self) -> Optional[parameter_type]:
        out = _HandleStructP()
        if not _bind().ifcopenshell_ifc_attribute_type_of_attribute(self._h, byref(out)):
            return None
        return _wrap_parameter_type(out)

    def __repr__(self) -> str:
        return "<attribute %s%s: %s>" % (
            self.name(),
            "?" if self.optional() else "",
            self.type_of_attribute(),
        )


class inverse_attribute(_Handle):
    _destroy_fn_name = "ifcopenshell_ifc_inverse_attribute_destroy"

    def name(self) -> str:
        s = ifcopenshell_string_t()
        if not _bind().ifcopenshell_ifc_inverse_attribute_name(self._h, byref(s)):
            return ""
        return _take_string(s)

    def type_of_aggregation(self) -> int:
        v = c_int32(-1)
        if not _bind().ifcopenshell_ifc_inverse_attribute_type_of_aggregation(self._h, byref(v)):
            return -1
        return int(v.value)

    def type_of_aggregation_string(self) -> str:
        return _INV_AGG_NAMES.get(self.type_of_aggregation(), "")

    def bound1(self) -> int:
        v = c_int32(-1)
        if not _bind().ifcopenshell_ifc_inverse_attribute_bound1(self._h, byref(v)):
            return -1
        return int(v.value)

    def bound2(self) -> int:
        v = c_int32(-1)
        if not _bind().ifcopenshell_ifc_inverse_attribute_bound2(self._h, byref(v)):
            return -1
        return int(v.value)

    def entity_reference(self) -> Optional[entity]:
        out = _HandleStructP()
        if not _bind().ifcopenshell_ifc_inverse_attribute_entity_reference(self._h, byref(out)):
            return None
        return _opt_handle(out, _bind().ifcopenshell_ifc_entity_destroy, entity)

    def attribute_reference(self) -> Optional[attribute]:
        out = _HandleStructP()
        if not _bind().ifcopenshell_ifc_inverse_attribute_attribute_reference(self._h, byref(out)):
            return None
        return _opt_handle(out, _bind().ifcopenshell_ifc_attribute_destroy, attribute)

    def __repr__(self) -> str:
        ref = self.entity_reference()
        aref = self.attribute_reference()
        return "<inverse %s: %s for %s.%s>" % (
            self.name(),
            self.type_of_aggregation_string() or "",
            ref.name() if ref else "?",
            aref.name() if aref else "?",
        )


class schema_definition(_Handle):
    _destroy_fn_name = "ifcopenshell_ifc_schema_destroy"

    def name(self) -> str:
        s = ifcopenshell_string_t()
        if not _bind().ifcopenshell_ifc_schema_name(self._h, byref(s)):
            return ""
        return _take_string(s)

    def declaration_by_name(self, name) -> Optional[declaration]:
        if isinstance(name, int):
            raise NotImplementedError("declaration_by_name(int) not supported")
        out = _HandleStructP()
        if not _bind().ifcopenshell_ifc_schema_declaration_by_name(
            self._h, name.encode("utf-8"), byref(out)
        ):
            return None
        return _wrap_decl(out)

    def declarations(self) -> tuple:
        lst = ifcopenshell_ifc_declaration_list_t()
        if not _bind().ifcopenshell_ifc_schema_declarations(self._h, byref(lst)):
            return ()
        return _move_handle_list(
            lst, _bind().ifcopenshell_ifc_declaration_list_destroy, _wrap_decl
        )

    def entities(self) -> tuple:
        result = []
        for declaration in self.declarations():
            entity_decl = declaration.as_entity()
            if entity_decl is not None:
                result.append(entity_decl)
        return tuple(result)

    def __repr__(self) -> str:
        return "<schema %s>" % self.name()


# ---------------------------------------------------------------------------
# module-level accessors (SWIG parity)
# ---------------------------------------------------------------------------


def schema_by_name(name: str) -> schema_definition:
    out = _HandleStructP()
    if not _bind().ifcopenshell_ifcparse_schema_by_name(name.encode("utf-8"), byref(out)):
        raise RuntimeError("Schema not found: %s" % name)
    if not out or not out.contents.ptr:
        if out:
            _bind().ifcopenshell_ifc_schema_destroy(out)
        raise RuntimeError("Schema not found: %s" % name)
    return schema_definition(out)


def schema_names() -> tuple:
    lst = ifcopenshell_string_list_t()
    if not _bind().ifcopenshell_ifcparse_schema_names(byref(lst)):
        raise RuntimeError(ifcopenshell.get_log() or "Failed to list schemas")
    return _take_string_list(lst)


def register_schema(schema: schema_definition) -> None:
    if not isinstance(schema, schema_definition):
        raise TypeError("register_schema() expects an ifcopenshell_wrapper.schema_definition")
    if not _bind().ifcopenshell_ifcparse_register_schema(schema._h):
        raise RuntimeError(ifcopenshell.get_log() or "Failed to register schema")


def clear_schemas() -> None:
    if not _bind().ifcopenshell_ifcparse_clear_schemas():
        raise RuntimeError(ifcopenshell.get_log() or "Failed to clear schemas")


class _IfcBaseClassInfo:
    INVALID, FORWARD, INVERSE = range(3)

    def __init__(self, schema_name: str, ifc_class: str):
        self.schema_name = schema_name
        self.ifc_class = ifc_class
        declaration = schema_by_name(schema_name).declaration_by_name(ifc_class)
        self.entity = declaration.as_entity() if declaration is not None else None
        self.forward_names = {
            attribute.name().lower() for attribute in (self.entity.all_attributes() if self.entity else ())
        }
        self.inverse_names = {
            attribute.name().lower() for attribute in (self.entity.all_inverse_attributes() if self.entity else ())
        }

    def is_a(self, full=False):
        return f"{self.schema_name}.{self.ifc_class}" if full else self.ifc_class

    def get_attribute_category(self, name: str) -> int:
        lowered = name.lower()
        if lowered in self.forward_names:
            return self.FORWARD
        if lowered in self.inverse_names:
            return self.INVERSE
        return self.INVALID


def new_IfcBaseClass(schema_name: str, ifc_class: str):
    return _IfcBaseClassInfo(schema_name, ifc_class)


def instance_declaration(handle_value) -> declaration:
    """Return the schema declaration for a raw entity instance handle.

    `handle_value` is the int address of an `ifcopenshell_ifc_instance_t*`
    (matches the `_handle` field of `ifcopenshell.entity_instance`)."""
    inst_h = ctypes.cast(c_void_p(int(handle_value)), _HandleStructP)
    out = _HandleStructP()
    if not _bind().ifcopenshell_ifc_instance_declaration(inst_h, byref(out)):
        raise RuntimeError("Instance has no declaration")
    if not out or not out.contents.ptr:
        if out:
            _bind().ifcopenshell_ifc_declaration_destroy(out)
        raise RuntimeError("Instance has no declaration")
    return _wrap_decl(out)


# ---------------------------------------------------------------------------
# Geometry/alignment stubs (no native geometry kernel yet)
# ---------------------------------------------------------------------------


class _FunctionItem:
    def __init__(self, item):
        self._item = item
        self._h = item._h

    def _distance(self, fn_name):
        from ifcopenshell.geom._capi import bind

        out = c_double(0.0)
        if not getattr(bind(), fn_name)(self._h, byref(out)):
            raise RuntimeError(ifcopenshell.get_log() or fn_name)
        return float(out.value)

    def start(self):
        return self._distance("ifcopenshell_taxonomy_function_item_start")

    def end(self):
        return self._distance("ifcopenshell_taxonomy_function_item_end")


class function_item_evaluator:
    def __init__(self, settings, fn):
        from ifcopenshell.geom._capi import HandleP, bind

        out = HandleP()
        if not bind().ifcopenshell_ifcgeom_create_function_item_evaluator(settings._h, fn._h, byref(out)):
            raise RuntimeError(ifcopenshell.get_log() or "Failed to create function_item_evaluator")
        self._h = out

    def __del__(self):
        h = getattr(self, "_h", None)
        if h:
            try:
                from ifcopenshell.geom._capi import bind

                bind().ifcopenshell_ifcgeom_function_item_evaluator_destroy(h)
            except Exception:
                pass
            self._h = None

    def evaluate(self, distance_along):
        from ifcopenshell.geom._capi import bind, ifcopenshell_double_list_t, take_double_list

        out = ifcopenshell_double_list_t()
        if not bind().ifcopenshell_ifcgeom_function_item_evaluator_evaluate_at(
            self._h, float(distance_along), byref(out)
        ):
            raise RuntimeError(ifcopenshell.get_log() or "Failed to evaluate function_item")
        values = take_double_list(out)
        return [values[i : i + 4] for i in range(0, 16, 4)]


def map_shape(settings, wrapped_data):
    import ifcopenshell.geom

    return _FunctionItem(ifcopenshell.geom.map_shape(settings, wrapped_data))


def helmert_curve_point(A0, A1, A2, length):
    from ifcopenshell.geom._capi import bind, ifcopenshell_double_list_t, take_double_list

    out = ifcopenshell_double_list_t()
    if not bind().ifcopenshell_ifcgeom_helmert_curve_point(
        float(A0), float(A1), float(A2), float(length), byref(out)
    ):
        raise RuntimeError(ifcopenshell.get_log() or "Failed to evaluate helmert_curve_point")
    return tuple(take_double_list(out))


def convert_loop_to_function_item(fn):
    from ifcopenshell.geom._capi import HandleP, bind
    from ifcopenshell.geom.main import TaxonomyItem

    out = HandleP()
    if not bind().ifcopenshell_ifcgeom_convert_loop_to_function_item(fn._h, byref(out)):
        raise RuntimeError(ifcopenshell.get_log() or "Failed to convert loop to function_item")
    return _FunctionItem(TaxonomyItem(out))


_GEOM_CLASS_ALIASES = {
    "Element",
    "BRepElement",
    "TriangulationElement",
    "SerializedElement",
    "Triangulation",
    "BRepRepresentation",
    "SerializedRepresentation",
}


def __getattr__(name):
    if name in _GEOM_CLASS_ALIASES:
        import ifcopenshell.geom

        value = getattr(ifcopenshell.geom, name)
        globals()[name] = value
        return value
    raise AttributeError(name)


# ---------------------------------------------------------------------------
# Geometry-settings enum constants exposed for upstream API parity.
#
# Mirrors ``ifcopenshell::geometry::settings::OutputDimensionalityTypes``
# and ``IteratorOutputOptions`` (see ``src/ifcgeom/ConversionSettings.h``).
# Upstream callers reference these as ``ifcopenshell.ifcopenshell_wrapper.*``.
# ---------------------------------------------------------------------------

CURVES = 0
SURFACES_AND_SOLIDS = 1
CURVES_SURFACES_AND_SOLIDS = 2

TRIANGULATED = 0
NATIVE = 1
SERIALIZED = 2

TRIANGLE_MESH = 0
POLYHEDRON_WITHOUT_HOLES = 1
POLYHEDRON_WITH_HOLES = 2


def version():
    """Return the ifcopenshell library version string (parity with SWIG)."""
    return ifcopenshell.version


_FEATURES: dict = {}


class attribute_value_derived:
    """Sentinel for raw SPF ``*`` values when validation requests them."""

    pass


def get_feature(name: str):
    """Return a feature flag value (parity with SWIG get_feature).

    Backed by a process-wide dict; consulted by validate.py and a few other
    upstream code paths to toggle behaviour. Unknown features return None.
    """
    return _FEATURES.get(name)


def set_feature(name: str, value) -> None:
    """Set a feature flag value (parity with SWIG set_feature)."""
    _FEATURES[name] = value


_LOG_BUFFER: list = []
_LOG_FORMAT = "text"


def _split_json_objects(s: str) -> str:
    """Insert newlines between concatenated top-level JSON objects.

    Boost < 1.86 emits property_tree JSON without trailing newlines,
    producing ``}{`` boundaries between log entries. Walk the string
    counting braces (skipping over JSON string literals) and insert a
    newline between completed top-level objects."""
    if not s or "}{" not in s:
        return s
    out = []
    depth = 0
    in_str = False
    escape = False
    for i, ch in enumerate(s):
        out.append(ch)
        if in_str:
            if escape:
                escape = False
            elif ch == "\\":
                escape = True
            elif ch == '"':
                in_str = False
            continue
        if ch == '"':
            in_str = True
        elif ch == "{":
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth == 0 and i + 1 < len(s) and s[i + 1] == "{":
                out.append("\n")
    return "".join(out)


def get_log() -> str:
    """Return the accumulated parser/validator log and clear it (parity with SWIG)."""
    global _LOG_BUFFER
    out = ifcopenshell_string_t()
    if not _bind().ifcopenshell_ifcparse_get_log(byref(out)):
        return ""
    cpp_log = _take_string(out)
    if _LOG_FORMAT == "json":
        cpp_log = _split_json_objects(cpp_log)
    if _LOG_BUFFER:
        py_log = "\n".join(_LOG_BUFFER)
        _LOG_BUFFER = []
        return (cpp_log + ("\n" if cpp_log and py_log else "") + py_log) if (cpp_log or py_log) else ""
    return cpp_log


def turn_on_detailed_logging() -> None:
    _bind().ifcopenshell_ifcparse_turn_on_detailed_logging()


def turn_off_detailed_logging() -> None:
    _bind().ifcopenshell_ifcparse_turn_off_detailed_logging()


def set_log_format_json() -> None:
    global _LOG_FORMAT
    _LOG_FORMAT = "json"
    _bind().ifcopenshell_ifcparse_set_log_format_json()


def set_log_format_text() -> None:
    global _LOG_FORMAT
    _LOG_FORMAT = "text"
    _bind().ifcopenshell_ifcparse_set_log_format_text()


# Type alias for parity with SWIG's ifcopenshell_wrapper.file. Upstream
# pure-Python helper modules use this purely as a type annotation; the
# real Python-facing class lives in ifcopenshell.file. Resolved lazily to
# avoid circular imports during package bootstrap.
class _FileTypeAlias:
    """Forward-ref placeholder for ifcopenshell_wrapper.file (type-only use)."""

    def __class_getitem__(cls, item):  # support `wrapper.file[...]` (rare)
        return cls

file = _FileTypeAlias  # noqa: A001 - intentional shadowing of builtin name
